"""Education, research and humanities vocabulary appearing in Korean text."""
from __future__ import annotations

from typing import Dict

ACADEMIA: Dict[str, str] = {
    "abstract": "앱스트랙트",
    "academic": "아카데믹",
    "academic year": "아카데믹 이어",
    "academy": "아카데미",
    "accent": "악센트",
    "accounting": "어카운팅",
    "achievement": "어치브먼트",
    "admission": "어드미션",
    "advisor": "어드바이저",
    "aesthetic": "에스테틱",
    "aesthetics": "에스테틱스",
    "agriculture": "애그리컬처",
    "allegory": "앨러고리",
    "alphabet": "알파벳",
    "alumni": "앨럼나이",
    "analogy": "애널로지",
    "analysis": "어낼리시스",
    "anarchism": "아나키즘",
    "anatomy": "어내터미",
    "annotation": "어노테이션",
    "anthropology": "앤스러폴로지",
    "anxiety": "앵자이어티",
    "appendix": "어펜딕스",
    "application": "애플리케이션",
    "aptitude": "앱티튜드",
    "archaeology": "아키올로지",
    "architecture": "아키텍처",
    "archive": "아카이브",
    "argument": "아규먼트",
    "aristotle": "아리스토텔레스",
    "art history": "아트 히스토리",
    "assessment": "어세스먼트",
    "assignment": "어사인먼트",
    "astronomy": "어스트로노미",
    "atlas": "아틀라스",
    "attachment": "어태치먼트",
    "attendance": "어텐던스",
    "audit": "오디트",
    "average": "애버리지",
    "bachelor": "배철러",
    "bachelor's degree": "배철러스 디그리",
    "baroque": "바로크",
    "behaviorism": "비헤이비어리즘",
    "benchmark": "벤치마크",
    "berkeley": "버클리",
    "bias": "바이어스",
    "bible": "바이블",
    "bibliography": "비블리오그래피",
    "bilingual": "바이링구얼",
    "biology": "바이올로지",
    "botany": "보터니",
    "buddhism": "불교",
    "burnout": "번아웃",
    "business administration": "비즈니스 애드미니스트레이션",
    "byzantine": "비잔틴",
    "cafeteria": "카페테리아",
    "caltech": "칼텍",
    "cambridge": "케임브리지",
    "campus": "캠퍼스",
    "camus": "카뮈",
    "canon": "캐넌",
    "capitalism": "캐피털리즘",
    "career": "커리어",
    "case study": "케이스 스터디",
    "catalog": "카탈로그",
    "catholic": "가톨릭",
    "certificate": "서티피케이트",
    "certification": "서티피케이션",
    "chapter": "챕터",
    "cheating": "치팅",
    "chemistry": "케미스트리",
    "chomsky": "촘스키",
    "christianity": "기독교",
    "citation": "사이테이션",
    "civil engineering": "시빌 엔지니어링",
    "civilization": "시빌리제이션",
    "class": "클래스",
    "classic": "클래식",
    "classroom": "클래스룸",
    "cognition": "코그니션",
    "cognitive": "코그니티브",
    "cohort": "코호트",
    "college": "칼리지",
    "colonialism": "콜로니얼리즘",
    "colony": "콜로니",
    "columbia": "컬럼비아",
    "comprehension": "컴프리헨션",
    "computer science": "컴퓨터 사이언스",
    "concentration": "컨센트레이션",
    "concept": "콘셉트",
    "conditioning": "컨디셔닝",
    "conference": "콘퍼런스",
    "confirmation bias": "컨퍼메이션 바이어스",
    "confucianism": "유교",
    "confucius": "공자",
    "consciousness": "컨셔스니스",
    "consonant": "컨서넌트",
    "context": "콘텍스트",
    "control group": "컨트롤 그룹",
    "copernicus": "코페르니쿠스",
    "cornell": "코넬",
    "corpus": "코퍼스",
    "correlation": "코릴레이션",
    "counseling": "카운슬링",
    "coursera": "코세라",
    "coursework": "코스워크",
    "credential": "크리덴셜",
    "credit": "크레딧",
    "criminology": "크리미놀로지",
    "criteria": "크라이테리아",
    "critical thinking": "크리티컬 싱킹",
    "criticism": "크리티시즘",
    "critique": "크리티크",
    "crusade": "크루세이드",
    "curriculum": "커리큘럼",
    "darwin": "다윈",
    "data": "데이터",
    "database": "데이터베이스",
    "dataset": "데이터셋",
    "deadline": "데드라인",
    "dean": "딘",
    "debate": "디베이트",
    "deconstruction": "디컨스트럭션",
    "deduction": "디덕션",
    "degree": "디그리",
    "democracy": "데모크라시",
    "demography": "디모그래피",
    "department": "디파트먼트",
    "depression": "디프레션",
    "derrida": "데리다",
    "descartes": "데카르트",
    "determinism": "디터미니즘",
    "deviation": "디비에이션",
    "diagram": "다이어그램",
    "dialect": "다이얼렉트",
    "dialectic": "다이얼렉틱",
    "dictionary": "딕셔너리",
    "diploma": "디플로마",
    "discipline": "디시플린",
    "discourse": "디스코스",
    "discussion": "디스커션",
    "dissertation": "디서테이션",
    "distance learning": "디스턴스 러닝",
    "doctor": "닥터",
    "doctorate": "닥터레이트",
    "dogma": "도그마",
    "doi": "디오아이",
    "dormitory": "도미토리",
    "draft": "드래프트",
    "dualism": "듀얼리즘",
    "durkheim": "뒤르켐",
    "dynasty": "다이너스티",
    "dystopia": "디스토피아",
    "e-learning": "이러닝",
    "economics": "이코노믹스",
    "editor": "에디터",
    "editorial": "에디토리얼",
    "education": "에듀케이션",
    "elective": "일렉티브",
    "elementary school": "엘리멘터리 스쿨",
    "emotion": "이모션",
    "empathy": "엠퍼시",
    "empire": "엠파이어",
    "empirical": "엠피리컬",
    "empiricism": "엠피리시즘",
    "encyclopedia": "엔사이클로피디아",
    "endnote": "엔드노트",
    "engineering": "엔지니어링",
    "enlightenment": "인라이트먼트",
    "enrollment": "인롤먼트",
    "epistemology": "에피스테몰로지",
    "essay": "에세이",
    "essence": "에센스",
    "ethics": "에식스",
    "ethnography": "에스노그래피",
    "etymology": "에티몰로지",
    "evaluation": "이밸류에이션",
    "exam": "이그잼",
    "exchange program": "익스체인지 프로그램",
    "exchange student": "익스체인지 스튜던트",
    "existentialism": "이그지스텐셜리즘",
    "experiment": "익스페리먼트",
    "extracurricular": "엑스트라커리큘러",
    "factor": "팩터",
    "faculty": "패컬티",
    "feedback": "피드백",
    "fellowship": "펠로십",
    "feminism": "페미니즘",
    "feudalism": "퓨덜리즘",
    "field trip": "필드 트립",
    "fieldwork": "필드워크",
    "finance": "파이낸스",
    "findings": "파인딩스",
    "focus group": "포커스 그룹",
    "footnote": "풋노트",
    "foucault": "푸코",
    "framework": "프레임워크",
    "freshman": "프레시맨",
    "freud": "프로이트",
    "fulbright": "풀브라이트",
    "funding": "펀딩",
    "galileo": "갈릴레오",
    "gap year": "갭 이어",
    "genetics": "제네틱스",
    "genre": "장르",
    "geography": "지오그래피",
    "geology": "지올로지",
    "gestalt": "게슈탈트",
    "glossary": "글로서리",
    "gmat": "지맷",
    "gothic": "고딕",
    "gpa": "지피에이",
    "grade": "그레이드",
    "grading": "그레이딩",
    "graduate": "그래주에이트",
    "graduate school": "그래주에이트 스쿨",
    "graduation": "그래주에이션",
    "grammar": "그래머",
    "grant": "그랜트",
    "gre": "지알이",
    "group project": "그룹 프로젝트",
    "guideline": "가이드라인",
    "handbook": "핸드북",
    "harvard": "하버드",
    "hegel": "헤겔",
    "heidegger": "하이데거",
    "high school": "하이 스쿨",
    "highlighter": "하이라이터",
    "hinduism": "힌두교",
    "history": "히스토리",
    "homeschooling": "홈스쿨링",
    "homework": "홈워크",
    "humanism": "휴머니즘",
    "humanities": "휴머니티스",
    "hume": "흄",
    "hypothesis": "하이포서시스",
    "idealism": "아이디얼리즘",
    "ideology": "이데올로기",
    "idiom": "이디엄",
    "ielts": "아이엘츠",
    "impact factor": "임팩트 팩터",
    "induction": "인덕션",
    "industrial revolution": "인더스트리얼 레벌루션",
    "instructor": "인스트럭터",
    "interdisciplinary": "인터디시플리너리",
    "internship": "인턴십",
    "interpretation": "인터프리테이션",
    "interview": "인터뷰",
    "iq": "아이큐",
    "irony": "아이러니",
    "islam": "이슬람",
    "ivy league": "아이비리그",
    "journal": "저널",
    "journalism": "저널리즘",
    "judaism": "유대교",
    "kant": "칸트",
    "keyword": "키워드",
    "khan academy": "칸 아카데미",
    "kindergarten": "킨더가튼",
    "knowledge": "널리지",
    "lab": "랩",
    "laboratory": "래버러토리",
    "law school": "로 스쿨",
    "learning": "러닝",
    "lecture": "렉처",
    "lecture hall": "렉처 홀",
    "lecture note": "렉처 노트",
    "lecturer": "렉처러",
    "lesson": "레슨",
    "lexicon": "렉시콘",
    "liberalism": "리버럴리즘",
    "library": "라이브러리",
    "linguistics": "링귀스틱스",
    "literacy": "리터러시",
    "literature": "리터러처",
    "literature review": "리터러처 리뷰",
    "logic": "로직",
    "logos": "로고스",
    "machiavelli": "마키아벨리",
    "major": "메이저",
    "manifesto": "매니페스토",
    "manual": "매뉴얼",
    "manuscript": "매뉴스크립트",
    "marketing": "마케팅",
    "marxism": "마르크시즘",
    "maslow": "매슬로",
    "master": "마스터",
    "master's degree": "마스터스 디그리",
    "materialism": "머티리얼리즘",
    "mathematics": "매서매틱스",
    "mechanical engineering": "미캐니컬 엔지니어링",
    "median": "미디언",
    "medicine": "메디신",
    "medieval": "미디벌",
    "memo": "메모",
    "memory": "메모리",
    "mental": "멘털",
    "mentor": "멘토",
    "mesopotamia": "메소포타미아",
    "meta analysis": "메타 애널리시스",
    "metaphor": "메타포",
    "metaphysics": "메타피직스",
    "method": "메서드",
    "methodology": "메서돌로지",
    "middle ages": "미들 에이지스",
    "midterm": "미드텀",
    "minor": "마이너",
    "mit": "엠아이티",
    "model": "모델",
    "modernism": "모더니즘",
    "monarchy": "모나키",
    "monograph": "모노그래프",
    "montessori": "몬테소리",
    "mooc": "무크",
    "morality": "모럴리티",
    "motivation": "모티베이션",
    "multiple choice": "멀티플 초이스",
    "mythology": "미솔로지",
    "narrative": "내러티브",
    "native speaker": "네이티브 스피커",
    "neuroscience": "뉴로사이언스",
    "nietzsche": "니체",
    "nihilism": "니힐리즘",
    "nobel": "노벨",
    "nobel prize": "노벨상",
    "notation": "노테이션",
    "notebook": "노트북",
    "nursing": "널싱",
    "observation": "옵저베이션",
    "online class": "온라인 클래스",
    "ontology": "온톨로지",
    "orientation": "오리엔테이션",
    "orthodox": "오소독스",
    "outlier": "아웃라이어",
    "outline": "아웃라인",
    "oxford": "옥스퍼드",
    "p-value": "피 밸류",
    "paper": "페이퍼",
    "paradigm": "패러다임",
    "pavlov": "파블로프",
    "pdf": "피디에프",
    "pedagogy": "페더고지",
    "peer review": "피어 리뷰",
    "percentile": "퍼센타일",
    "perception": "퍼셉션",
    "personality": "퍼스낼리티",
    "pharmacy": "파머시",
    "phd": "피에이치디",
    "philosophy": "필로소피",
    "phonetics": "포네틱스",
    "phonology": "포놀로지",
    "physics": "피직스",
    "piaget": "피아제",
    "pilot study": "파일럿 스터디",
    "placebo": "플라세보",
    "plagiarism": "플레이지어리즘",
    "plato": "플라톤",
    "political science": "폴리티컬 사이언스",
    "portfolio": "포트폴리오",
    "postdoc": "포스닥",
    "postmodernism": "포스트모더니즘",
    "pragmatics": "프래그매틱스",
    "pragmatism": "프래그머티즘",
    "preface": "프레피스",
    "premise": "프레미스",
    "preprint": "프리프린트",
    "presentation": "프레젠테이션",
    "princeton": "프린스턴",
    "principal": "프린시펄",
    "probability": "프로버빌리티",
    "proceedings": "프로시딩스",
    "professor": "프로페서",
    "project": "프로젝트",
    "pronunciation": "프러넌시에이션",
    "proposition": "프로포지션",
    "protestant": "프로테스탄트",
    "psychiatry": "사이카이어트리",
    "psychoanalysis": "사이코애널리시스",
    "psychology": "사이콜로지",
    "public health": "퍼블릭 헬스",
    "publication": "퍼블리케이션",
    "puritan": "퓨리턴",
    "qualitative": "퀄리테이티브",
    "quantitative": "퀀티테이티브",
    "questionnaire": "퀘스처네어",
    "quiz": "퀴즈",
    "quotation": "쿼테이션",
    "random sampling": "랜덤 샘플링",
    "ranking": "랭킹",
    "ratio": "레이시오",
    "rationalism": "래셔널리즘",
    "realism": "리얼리즘",
    "recommendation": "레커멘데이션",
    "reference": "레퍼런스",
    "reformation": "리포메이션",
    "registration": "레지스트레이션",
    "regression": "리그레션",
    "reinforcement": "리인포스먼트",
    "relativism": "렐러티비즘",
    "reliability": "릴라이어빌리티",
    "renaissance": "르네상스",
    "replication": "레플리케이션",
    "report": "리포트",
    "republic": "리퍼블릭",
    "requirement": "리콰이어먼트",
    "research": "리서치",
    "researcher": "리서처",
    "review": "리뷰",
    "revolution": "레벌루션",
    "rhetoric": "레토릭",
    "ritual": "리추얼",
    "romanticism": "로맨티시즘",
    "rousseau": "루소",
    "rubric": "루브릭",
    "sample": "샘플",
    "sample size": "샘플 사이즈",
    "sartre": "사르트르",
    "schedule": "스케줄",
    "scholar": "스칼러",
    "scholarship": "스칼러십",
    "school": "스쿨",
    "score": "스코어",
    "scripture": "스크립처",
    "secular": "세큘러",
    "self esteem": "셀프 에스팀",
    "semantics": "시맨틱스",
    "semester": "세메스터",
    "seminar": "세미나",
    "semiotics": "세미오틱스",
    "senior": "시니어",
    "session": "세션",
    "significance": "시그니피컨스",
    "skepticism": "스켑티시즘",
    "skill": "스킬",
    "slang": "슬랭",
    "socialism": "소셜리즘",
    "sociology": "소시올로지",
    "socrates": "소크라테스",
    "sophomore": "소포모어",
    "spinoza": "스피노자",
    "staff": "스태프",
    "stanford": "스탠퍼드",
    "statistics": "스터티스틱스",
    "stereotype": "스테레오타입",
    "stimulus": "스티뮬러스",
    "stress": "스트레스",
    "structuralism": "스트럭처럴리즘",
    "student": "스튜던트",
    "study group": "스터디 그룹",
    "subconscious": "서브컨셔스",
    "summary": "서머리",
    "survey": "서베이",
    "syllable": "실러블",
    "syllabus": "실러버스",
    "symbolism": "심벌리즘",
    "syntax": "신택스",
    "taoism": "도교",
    "teacher": "티처",
    "ted talk": "테드 토크",
    "temple": "템플",
    "term": "텀",
    "term paper": "텀 페이퍼",
    "test": "테스트",
    "testament": "테스터먼트",
    "text": "텍스트",
    "textbook": "텍스트북",
    "theology": "시올로지",
    "theory": "시어리",
    "therapy": "테라피",
    "thesis": "시시스",
    "toefl": "토플",
    "toeic": "토익",
    "topik": "토픽",
    "training": "트레이닝",
    "transcript": "트랜스크립트",
    "transfer": "트랜스퍼",
    "translation": "트랜슬레이션",
    "trauma": "트라우마",
    "trend": "트렌드",
    "tuition": "튜이션",
    "tuition fee": "튜이션 피",
    "tutor": "튜터",
    "tutorial": "튜토리얼",
    "unconscious": "언컨셔스",
    "undergraduate": "언더그래주에이트",
    "unesco": "유네스코",
    "university": "유니버시티",
    "utilitarianism": "유틸리테리어니즘",
    "utopia": "유토피아",
    "vacation": "베케이션",
    "validity": "밸리디티",
    "variable": "베리어블",
    "variance": "베리언스",
    "vatican": "바티칸",
    "vocabulary": "보캐뷸러리",
    "voltaire": "볼테르",
    "volume": "볼륨",
    "vowel": "바우얼",
    "vygotsky": "비고츠키",
    "weber": "베버",
    "webinar": "웨비나",
    "wittgenstein": "비트겐슈타인",
    "workbook": "워크북",
    "workload": "워크로드",
    "workshop": "워크숍",
    "yale": "예일",
    "zoology": "주올로지",
}

__all__ = ["ACADEMIA"]
