"""Core English words, so a stray English fragment still reads cleanly.

The domain modules deliberately skip function words — they are ambiguous and a
domain table has no business claiming them. But a Korean sentence quoting an
English phrase still contains them, and the transliterator alone renders "the"
as 스. This module is merged last, so any domain reading wins over it.
"""
from __future__ import annotations

from typing import Dict

BASIC: Dict[str, str] = {
    "about": "어바웃", "after": "애프터", "again": "어게인", "against": "어게인스트",
    "all": "올", "almost": "올모스트", "alone": "얼론", "along": "얼롱",
    "already": "올레디", "also": "올소", "always": "올웨이즈", "am": "앰",
    "among": "어몽", "and": "앤드", "another": "어나더", "any": "애니",
    "anyone": "애니원", "anything": "애니싱", "are": "아", "around": "어라운드",
    "as": "애즈", "ask": "애스크", "at": "앳", "away": "어웨이",
    "back": "백", "bad": "배드", "be": "비", "because": "비코즈",
    "become": "비컴", "been": "빈", "before": "비포", "begin": "비긴",
    "behind": "비하인드", "believe": "빌리브", "below": "빌로우", "best": "베스트",
    "better": "베터", "between": "비트윈", "big": "빅", "both": "보스",
    "bring": "브링", "but": "벗", "buy": "바이", "by": "바이",
    "call": "콜", "came": "케임", "can": "캔", "cannot": "캐낫",
    "change": "체인지", "child": "차일드", "children": "칠드런", "city": "시티",
    "close": "클로즈", "cold": "콜드", "come": "컴", "could": "쿠드",
    "country": "컨트리", "day": "데이", "did": "디드", "different": "디퍼런트",
    "do": "두", "does": "더즈", "done": "던", "down": "다운",
    "during": "듀링", "each": "이치", "early": "얼리", "easy": "이지",
    "end": "엔드", "enough": "이너프", "even": "이븐", "ever": "에버",
    "every": "에브리", "everyone": "에브리원", "everything": "에브리싱",
    "example": "이그잼플", "eye": "아이", "face": "페이스", "fact": "팩트",
    "fall": "폴", "family": "패밀리", "far": "파", "fast": "패스트",
    "feel": "필", "few": "퓨", "find": "파인드", "first": "퍼스트",
    "follow": "팔로우", "for": "포", "found": "파운드", "friend": "프렌드",
    "from": "프롬", "full": "풀", "get": "겟", "give": "기브",
    "go": "고", "going": "고잉", "good": "굿", "got": "갓",
    "great": "그레이트", "group": "그룹", "grow": "그로우", "had": "해드",
    "hand": "핸드", "happen": "해픈", "hard": "하드", "has": "해즈",
    "have": "해브", "he": "히", "head": "헤드", "hear": "히어",
    "help": "헬프", "her": "허", "here": "히어", "high": "하이",
    "him": "힘", "his": "히즈", "hold": "홀드", "home": "홈",
    "hot": "핫", "house": "하우스", "how": "하우", "however": "하우에버",
    "important": "임포턴트", "instead": "인스테드", "into": "인투", "its": "이츠",
    "just": "저스트", "keep": "킵", "kind": "카인드", "know": "노우",
    "large": "라지", "last": "라스트", "late": "레이트", "later": "레이터",
    "learn": "런", "leave": "리브", "left": "레프트", "less": "레스",
    "let": "렛", "life": "라이프", "light": "라이트", "like": "라이크",
    "line": "라인", "little": "리틀", "live": "리브", "long": "롱",
    "look": "룩", "lose": "루즈", "lot": "랏", "love": "러브",
    "made": "메이드", "make": "메이크", "man": "맨", "many": "매니",
    "may": "메이", "maybe": "메이비", "me": "미", "mean": "민",
    "might": "마이트", "mind": "마인드", "money": "머니", "more": "모어",
    "most": "모스트", "move": "무브", "much": "머치", "must": "머스트",
    "my": "마이", "name": "네임", "near": "니어", "need": "니드",
    "never": "네버", "new": "뉴", "next": "넥스트", "nice": "나이스",
    "night": "나이트", "nothing": "낫싱", "now": "나우", "number": "넘버",
    "of": "오브", "off": "오프", "often": "오프튼", "old": "올드",
    "once": "원스", "one": "원", "only": "온리", "open": "오픈",
    "or": "오어", "order": "오더", "other": "아더", "our": "아워",
    "out": "아웃", "over": "오버", "own": "오운", "part": "파트",
    "pay": "페이", "people": "피플", "person": "퍼슨", "place": "플레이스",
    "play": "플레이", "point": "포인트", "problem": "프라블럼", "put": "풋",
    "read": "리드", "ready": "레디", "real": "리얼", "really": "리얼리",
    "right": "라이트", "room": "룸", "run": "런", "same": "세임",
    "saw": "소", "say": "세이", "school": "스쿨", "see": "씨",
    "seem": "심", "she": "쉬", "short": "쇼트", "should": "슈드",
    "show": "쇼", "side": "사이드", "since": "신스", "small": "스몰",
    "some": "섬", "someone": "썸원", "something": "썸싱", "sometimes": "썸타임즈",
    "soon": "순", "sorry": "쏘리", "sound": "사운드", "speak": "스피크",
    "start": "스타트", "stay": "스테이", "still": "스틸", "stop": "스톱",
    "story": "스토리", "such": "서치", "sure": "슈어", "take": "테이크",
    "talk": "토크", "tell": "텔", "than": "댄", "thank": "땡크",
    "that": "댓", "the": "더", "their": "데어", "them": "뎀",
    "then": "덴", "there": "데어", "these": "디즈", "they": "데이",
    "thing": "씽", "think": "씽크", "this": "디스", "those": "도즈",
    "though": "도우", "thought": "쏘트", "three": "쓰리", "through": "스루",
    "time": "타임", "today": "투데이", "together": "투게더", "told": "톨드",
    "too": "투", "took": "툭", "true": "트루", "try": "트라이",
    "turn": "턴", "two": "투", "under": "언더", "until": "언틸",
    "upon": "어폰", "very": "베리", "wait": "웨이트", "walk": "워크",
    "want": "원트", "was": "워즈", "watch": "워치", "water": "워터",
    "way": "웨이", "week": "위크", "well": "웰", "went": "웬트",
    "were": "워", "what": "왓", "when": "웬", "where": "웨어",
    "whether": "웨더", "which": "위치", "while": "와일", "who": "후",
    "whole": "홀", "why": "와이", "will": "윌", "with": "위드",
    "within": "위딘", "without": "위드아웃", "woman": "우먼", "word": "워드",
    "work": "워크", "world": "월드", "would": "우드", "write": "라이트",
    "year": "이어", "yes": "예스", "yet": "옛", "you": "유",
    "young": "영", "your": "유어", "yourself": "유어셀프",
}

__all__ = ["BASIC"]
