"""Brand, company, product and service names as Koreans read them aloud."""
from __future__ import annotations

from typing import Dict

BRANDS: Dict[str, str] = {
    "11st": "십일번가",
    "3m": "쓰리엠",
    "7 eleven": "세븐일레븐",
    "7-eleven": "세븐일레븐",
    "abbvie": "애브비",
    "absolut": "앱솔루트",
    "acer": "에이서",
    "acrobat": "아크로뱃",
    "activision": "액티비전",
    "acura": "아큐라",
    "adidas": "아디다스",
    "adobe": "어도비",
    "advil": "애드빌",
    "after effects": "애프터 이펙트",
    "agoda": "아고다",
    "aig": "에이아이지",
    "air asia": "에어아시아",
    "air busan": "에어부산",
    "air canada": "에어캐나다",
    "air france": "에어프랑스",
    "air jordan": "에어 조던",
    "airbnb": "에어비앤비",
    "airbus": "에어버스",
    "airpods": "에어팟",
    "airtag": "에어태그",
    "akamai": "아카마이",
    "aldi": "알디",
    "alexa": "알렉사",
    "alfa romeo": "알파 로메오",
    "alibaba": "알리바바",
    "aliexpress": "알리익스프레스",
    "allianz": "알리안츠",
    "alphabet": "알파벳",
    "amazon": "아마존",
    "amazon prime": "아마존 프라임",
    "amd": "에이엠디",
    "american airlines": "아메리칸 항공",
    "american express": "아메리칸 익스프레스",
    "amex": "아멕스",
    "amg": "에이엠지",
    "amgen": "암젠",
    "amorepacific": "아모레퍼시픽",
    "android": "안드로이드",
    "anker": "앤커",
    "anthropic": "앤스로픽",
    "app store": "앱 스토어",
    "apple": "애플",
    "apple music": "애플 뮤직",
    "apple pay": "애플 페이",
    "apple tv": "애플 티비",
    "apple watch": "애플 워치",
    "aramco": "아람코",
    "arc'teryx": "아크테릭스",
    "arcteryx": "아크테릭스",
    "armani": "아르마니",
    "asahi": "아사히",
    "asana": "아사나",
    "asiana": "아시아나",
    "asiana airlines": "아시아나항공",
    "asics": "아식스",
    "asml": "에이에스엠엘",
    "aspirin": "아스피린",
    "aston martin": "애스턴 마틴",
    "astrazeneca": "아스트라제네카",
    "asus": "에이수스",
    "atari": "아타리",
    "atlassian": "아틀라시안",
    "audemars piguet": "오데마 피게",
    "audi": "아우디",
    "autocad": "오토캐드",
    "autodesk": "오토데스크",
    "avante": "아반떼",
    "aws": "에이더블유에스",
    "axa": "악사",
    "azure": "애저",
    "bacardi": "바카디",
    "baemin": "배민",
    "baileys": "베일리스",
    "balenciaga": "발렌시아가",
    "bandai": "반다이",
    "bandai namco": "반다이 남코",
    "bank of america": "뱅크 오브 아메리카",
    "barbie": "바비",
    "barclays": "바클레이스",
    "baskin robbins": "배스킨라빈스",
    "bayer": "바이엘",
    "bbc": "비비씨",
    "bbq": "비비큐",
    "beats": "비츠",
    "bentley": "벤틀리",
    "benz": "벤츠",
    "berkshire hathaway": "버크셔 해서웨이",
    "best buy": "베스트 바이",
    "bhc": "비에이치씨",
    "bibigo": "비비고",
    "billboard": "빌보드",
    "binance": "바이낸스",
    "bing": "빙",
    "binggrae": "빙그레",
    "birkenstock": "버켄스탁",
    "bitcoin": "비트코인",
    "bithumb": "빗썸",
    "bixby": "빅스비",
    "blackpink": "블랙핑크",
    "blackrock": "블랙록",
    "blizzard": "블리자드",
    "bloomberg": "블룸버그",
    "blue bottle": "블루보틀",
    "blue origin": "블루 오리진",
    "bmw": "비엠더블유",
    "boeing": "보잉",
    "booking.com": "부킹닷컴",
    "bosch": "보쉬",
    "bose": "보스",
    "botox": "보톡스",
    "bottega veneta": "보테가 베네타",
    "bp": "비피",
    "braun": "브라운",
    "breitling": "브라이틀링",
    "bridgestone": "브리지스톤",
    "british airways": "브리티시 에어웨이스",
    "broadcom": "브로드컴",
    "bts": "방탄소년단",
    "budweiser": "버드와이저",
    "bugatti": "부가티",
    "buick": "뷰익",
    "buldak": "불닭",
    "bulgari": "불가리",
    "bumble": "범블",
    "burberry": "버버리",
    "burger king": "버거킹",
    "bvlgari": "불가리",
    "byd": "비와이디",
    "cadillac": "캐딜락",
    "call of duty": "콜 오브 듀티",
    "callaway": "캘러웨이",
    "calvin klein": "캘빈 클라인",
    "campbell's": "캠벨",
    "canada goose": "캐나다 구스",
    "canon": "캐논",
    "canva": "캔바",
    "capcom": "캡콤",
    "carhartt": "칼하트",
    "carnival": "카니발",
    "carrefour": "까르푸",
    "cartier": "까르띠에",
    "casio": "카시오",
    "cass": "카스",
    "caterpillar": "캐터필러",
    "cathay pacific": "캐세이퍼시픽",
    "celine": "셀린느",
    "celltrion": "셀트리온",
    "centrum": "센트룸",
    "cetaphil": "세타필",
    "cgv": "씨지브이",
    "chamisul": "참이슬",
    "chanel": "샤넬",
    "charles schwab": "찰스 슈왑",
    "chatgpt": "챗지피티",
    "cheetos": "치토스",
    "chevrolet": "쉐보레",
    "chevron": "셰브론",
    "chilsung cider": "칠성사이다",
    "chipotle": "치폴레",
    "chivas regal": "시바스 리갈",
    "choco pie": "초코파이",
    "christian dior": "크리스찬 디올",
    "chrome": "크롬",
    "chrysler": "크라이슬러",
    "cisco": "시스코",
    "citibank": "씨티은행",
    "citigroup": "씨티그룹",
    "citroen": "시트로엥",
    "cj": "씨제이",
    "cj enm": "씨제이 이엔엠",
    "claude": "클로드",
    "clinique": "크리니크",
    "cloudflare": "클라우드플레어",
    "cnn": "씨엔엔",
    "coca cola": "코카콜라",
    "coca-cola": "코카콜라",
    "coinbase": "코인베이스",
    "cold stone": "콜드스톤",
    "colgate": "콜게이트",
    "columbia": "컬럼비아",
    "compose coffee": "컴포즈커피",
    "converse": "컨버스",
    "copilot": "코파일럿",
    "corn flakes": "콘플레이크",
    "corsair": "커세어",
    "costa coffee": "코스타 커피",
    "costco": "코스트코",
    "coupang": "쿠팡",
    "coupang play": "쿠팡 플레이",
    "coursera": "코세라",
    "coway": "코웨이",
    "credit suisse": "크레디트 스위스",
    "crocs": "크록스",
    "cu": "씨유",
    "cuchen": "쿠첸",
    "cuckoo": "쿠쿠",
    "cuda": "쿠다",
    "cursor": "커서",
    "cvs": "씨브이에스",
    "cybertruck": "사이버트럭",
    "daihatsu": "다이하쓰",
    "dairy queen": "데어리퀸",
    "daiso": "다이소",
    "dall-e": "달리",
    "danone": "다논",
    "databricks": "데이터브릭스",
    "datadog": "데이터독",
    "daum": "다음",
    "dc comics": "디씨 코믹스",
    "deepmind": "딥마인드",
    "deepseek": "딥시크",
    "dell": "델",
    "delta": "델타",
    "denso": "덴소",
    "descente": "데상트",
    "deutsche bank": "도이체방크",
    "dhl": "디에이치엘",
    "diablo": "디아블로",
    "dior": "디올",
    "discord": "디스코드",
    "disney": "디즈니",
    "disney plus": "디즈니 플러스",
    "dji": "디제이아이",
    "docker": "도커",
    "dodge": "닷지",
    "dogecoin": "도지코인",
    "dolce & gabbana": "돌체 앤 가바나",
    "dolce and gabbana": "돌체 앤 가바나",
    "dom perignon": "돔 페리뇽",
    "domino's": "도미노",
    "domino's pizza": "도미노 피자",
    "dominos": "도미노",
    "dongwon": "동원",
    "doordash": "도어대시",
    "doosan": "두산",
    "doritos": "도리토스",
    "dove": "도브",
    "dow jones": "다우존스",
    "downy": "다우니",
    "dr martens": "닥터마틴",
    "dr pepper": "닥터페퍼",
    "dreamworks": "드림웍스",
    "dropbox": "드롭박스",
    "ducati": "두카티",
    "dunkin": "던킨",
    "dunkin donuts": "던킨 도너츠",
    "duolingo": "듀오링고",
    "durex": "듀렉스",
    "dyson": "다이슨",
    "easyjet": "이지젯",
    "ebay": "이베이",
    "ebs": "이비에스",
    "ediya": "이디야",
    "electrolux": "일렉트로룩스",
    "electronic arts": "일렉트로닉 아츠",
    "eli lilly": "일라이 릴리",
    "emart": "이마트",
    "emirates": "에미레이트 항공",
    "epic games": "에픽게임즈",
    "espn": "이에스피엔",
    "estee lauder": "에스티 로더",
    "ethereum": "이더리움",
    "etihad": "에티하드",
    "etsy": "엣시",
    "etude house": "에뛰드 하우스",
    "evernote": "에버노트",
    "evian": "에비앙",
    "excel": "엑셀",
    "expedia": "익스피디아",
    "exxon mobil": "엑슨모빌",
    "exynos": "엑시노스",
    "facebook": "페이스북",
    "facetime": "페이스타임",
    "fanta": "환타",
    "farfetch": "파페치",
    "febreze": "페브리즈",
    "fedex": "페덱스",
    "fendi": "펜디",
    "ferrari": "페라리",
    "ferrero rocher": "페레로 로쉐",
    "fiat": "피아트",
    "fidelity": "피델리티",
    "fifa": "피파",
    "figma": "피그마",
    "fila": "휠라",
    "firefox": "파이어폭스",
    "fitbit": "핏빗",
    "five guys": "파이브 가이즈",
    "flickr": "플리커",
    "forbes": "포브스",
    "ford": "포드",
    "fortnite": "포트나이트",
    "four seasons": "포시즌스",
    "fox news": "폭스 뉴스",
    "fuji": "후지",
    "fujifilm": "후지필름",
    "g shock": "지샥",
    "galaxy": "갤럭시",
    "galaxy buds": "갤럭시 버즈",
    "galaxy flip": "갤럭시 플립",
    "galaxy fold": "갤럭시 폴드",
    "galaxy note": "갤럭시 노트",
    "galaxy watch": "갤럭시 워치",
    "gap": "갭",
    "garmin": "가민",
    "gatorade": "게토레이",
    "ge": "지이",
    "geforce": "지포스",
    "gemini": "제미나이",
    "general electric": "제너럴 일렉트릭",
    "general mills": "제너럴 밀스",
    "general motors": "제너럴 모터스",
    "genesis": "제네시스",
    "genshin impact": "원신",
    "gentle monster": "젠틀몬스터",
    "ghibli": "지브리",
    "gillette": "질레트",
    "giorgio armani": "조르지오 아르마니",
    "github": "깃허브",
    "gitlab": "깃랩",
    "givenchy": "지방시",
    "glaxosmithkline": "글락소스미스클라인",
    "glenfiddich": "글렌피딕",
    "gm": "지엠",
    "gmail": "지메일",
    "gmarket": "지마켓",
    "godaddy": "고대디",
    "godiva": "고디바",
    "goldman sachs": "골드만삭스",
    "gong cha": "공차",
    "goodyear": "굿이어",
    "google": "구글",
    "google cloud": "구글 클라우드",
    "google drive": "구글 드라이브",
    "google maps": "구글 맵스",
    "google play": "구글 플레이",
    "gopro": "고프로",
    "goyard": "고야드",
    "gpt": "지피티",
    "gq": "지큐",
    "grammarly": "그래머리",
    "grandeur": "그랜저",
    "grok": "그록",
    "gs25": "지에스 이십오",
    "gsk": "지에스케이",
    "gta": "지티에이",
    "gucci": "구찌",
    "guinness": "기네스",
    "h and m": "에이치앤엠",
    "h&m": "에이치앤엠",
    "haagen dazs": "하겐다즈",
    "haier": "하이얼",
    "haitai": "해태",
    "hana bank": "하나은행",
    "hanatour": "하나투어",
    "hanwha": "한화",
    "haribo": "하리보",
    "harley": "할리",
    "harley davidson": "할리데이비슨",
    "harman kardon": "하만카돈",
    "hasbro": "해즈브로",
    "hasselblad": "핫셀블라드",
    "hbo": "에이치비오",
    "hbo max": "에이치비오 맥스",
    "heineken": "하이네켄",
    "heinz": "하인즈",
    "hennessy": "헤네시",
    "hermes": "에르메스",
    "hershey": "허쉬",
    "hershey's": "허쉬",
    "hewlett packard": "휴렛 팩커드",
    "hilton": "힐튼",
    "hisense": "하이센스",
    "hitachi": "히타치",
    "hite": "하이트",
    "hoegaarden": "호가든",
    "hoka": "호카",
    "holiday inn": "홀리데이 인",
    "hollys": "할리스",
    "home depot": "홈디포",
    "homeplus": "홈플러스",
    "homepod": "홈팟",
    "honda": "혼다",
    "honeywell": "하니웰",
    "hotels.com": "호텔스닷컴",
    "hp": "에이치피",
    "hsbc": "에이치에스비씨",
    "huawei": "화웨이",
    "hublot": "위블로",
    "hubspot": "허브스팟",
    "huggies": "하기스",
    "hugging face": "허깅 페이스",
    "hulu": "훌루",
    "hyatt": "하얏트",
    "hybe": "하이브",
    "hynix": "하이닉스",
    "hyundai": "현대",
    "hyundai motor": "현대자동차",
    "ibis": "이비스",
    "ibk": "아이비케이",
    "ibm": "아이비엠",
    "icloud": "아이클라우드",
    "ikea": "이케아",
    "illustrator": "일러스트레이터",
    "imac": "아이맥",
    "in n out": "인앤아웃",
    "in-n-out": "인앤아웃",
    "infiniti": "인피니티",
    "innisfree": "이니스프리",
    "instacart": "인스타카트",
    "instagram": "인스타그램",
    "intel": "인텔",
    "intercontinental": "인터컨티넨탈",
    "ioniq": "아이오닉",
    "ios": "아이오에스",
    "ipad": "아이패드",
    "iphone": "아이폰",
    "isuzu": "이스즈",
    "itunes": "아이튠즈",
    "jack daniel's": "잭 다니엘",
    "jack daniels": "잭 다니엘",
    "jaguar": "재규어",
    "jameson": "제임슨",
    "japan airlines": "일본항공",
    "jbl": "제이비엘",
    "jeep": "지프",
    "jeju air": "제주항공",
    "jin air": "진에어",
    "jinro": "진로",
    "jira": "지라",
    "john deere": "존디어",
    "johnnie walker": "조니 워커",
    "johnson & johnson": "존슨앤드존슨",
    "johnson and johnson": "존슨앤드존슨",
    "jordan": "조던",
    "jp morgan": "제이피모건",
    "jpmorgan": "제이피모건",
    "jtbc": "제이티비씨",
    "jyp": "제이와이피",
    "kakao": "카카오",
    "kakao pay": "카카오페이",
    "kakao talk": "카카오톡",
    "kakaobank": "카카오뱅크",
    "kakaopay": "카카오페이",
    "kakaotalk": "카카오톡",
    "kanu": "카누",
    "kate spade": "케이트 스페이드",
    "kawasaki": "가와사키",
    "kbank": "케이뱅크",
    "kbs": "케이비에스",
    "kellogg's": "켈로그",
    "kelloggs": "켈로그",
    "kfc": "케이에프씨",
    "khan academy": "칸 아카데미",
    "kia": "기아",
    "kiehl's": "키엘",
    "kiehls": "키엘",
    "kikkoman": "기꼬만",
    "kimberly clark": "킴벌리 클라크",
    "kindle": "킨들",
    "kingston": "킹스턴",
    "kirin": "기린",
    "kit kat": "킷캣",
    "kitkat": "킷캣",
    "kleenex": "크리넥스",
    "klm": "케이엘엠",
    "klook": "클룩",
    "knorr": "크노르",
    "kodak": "코닥",
    "koenigsegg": "코닉세그",
    "kolon sport": "코오롱 스포츠",
    "konami": "코나미",
    "korean air": "대한항공",
    "kraft": "크래프트",
    "krafton": "크래프톤",
    "krispy kreme": "크리스피 크림",
    "kroger": "크로거",
    "kt": "케이티",
    "ktm": "케이티엠",
    "kubernetes": "쿠버네티스",
    "kumho": "금호",
    "kurly": "컬리",
    "kyochon": "교촌",
    "l'oreal": "로레알",
    "la mer": "라메르",
    "lacoste": "라코스테",
    "lamborghini": "람보르기니",
    "lancome": "랑콤",
    "land rover": "랜드로버",
    "laneige": "라네즈",
    "lay's": "레이즈",
    "lays": "레이즈",
    "lazada": "라자다",
    "league of legends": "리그 오브 레전드",
    "lego": "레고",
    "leica": "라이카",
    "lenovo": "레노버",
    "levi's": "리바이스",
    "levis": "리바이스",
    "lexus": "렉서스",
    "lg": "엘지",
    "lg electronics": "엘지전자",
    "lg uplus": "엘지유플러스",
    "lidl": "리들",
    "lightroom": "라이트룸",
    "lincoln": "링컨",
    "lindt": "린트",
    "linkedin": "링크드인",
    "linux": "리눅스",
    "lionsgate": "라이온스게이트",
    "lipton": "립톤",
    "listerine": "리스테린",
    "llama": "라마",
    "lockheed martin": "록히드 마틴",
    "loewe": "로에베",
    "logitech": "로지텍",
    "longchamp": "롱샴",
    "longines": "론진",
    "loreal": "로레알",
    "lotte": "롯데",
    "lotte cinema": "롯데시네마",
    "lotte hotel": "롯데호텔",
    "lotte mart": "롯데마트",
    "lotteria": "롯데리아",
    "louis vuitton": "루이비통",
    "lucid": "루시드",
    "lufthansa": "루프트한자",
    "lululemon": "룰루레몬",
    "lyft": "리프트",
    "mac": "맥",
    "macallan": "맥캘란",
    "macbook": "맥북",
    "macbook air": "맥북 에어",
    "macbook pro": "맥북 프로",
    "macos": "맥오에스",
    "magsafe": "맥세이프",
    "mailchimp": "메일침프",
    "mammut": "마무트",
    "mario": "마리오",
    "market kurly": "마켓컬리",
    "marriott": "메리어트",
    "marshall": "마샬",
    "marvel": "마블",
    "maserati": "마세라티",
    "mastercard": "마스터카드",
    "matlab": "매트랩",
    "mattel": "마텔",
    "maxim": "맥심",
    "maxwell house": "맥스웰 하우스",
    "maybach": "마이바흐",
    "maybelline": "메이블린",
    "mazda": "마쓰다",
    "mbc": "엠비씨",
    "mcdonald's": "맥도날드",
    "mcdonalds": "맥도날드",
    "mclaren": "맥라렌",
    "mcm": "엠씨엠",
    "mega coffee": "메가커피",
    "megabox": "메가박스",
    "mentos": "멘토스",
    "mercedes": "메르세데스",
    "mercedes benz": "메르세데스 벤츠",
    "merck": "머크",
    "messenger": "메신저",
    "meta": "메타",
    "metamask": "메타마스크",
    "mgm": "엠지엠",
    "michael kors": "마이클 코어스",
    "michelin": "미쉐린",
    "micron": "마이크론",
    "microsoft": "마이크로소프트",
    "midjourney": "미드저니",
    "miele": "밀레",
    "milka": "밀카",
    "minecraft": "마인크래프트",
    "mini": "미니",
    "mistral": "미스트랄",
    "mitsubishi": "미쓰비시",
    "mizuno": "미즈노",
    "mlb": "엠엘비",
    "mnet": "엠넷",
    "moderna": "모더나",
    "moet": "모엣",
    "mom's touch": "맘스터치",
    "moms touch": "맘스터치",
    "moncler": "몽클레르",
    "mondelez": "몬델리즈",
    "mongodb": "몽고디비",
    "monster energy": "몬스터 에너지",
    "montblanc": "몽블랑",
    "moody's": "무디스",
    "moodys": "무디스",
    "morgan stanley": "모건스탠리",
    "mountain dew": "마운틴듀",
    "mozilla": "모질라",
    "mr pizza": "미스터피자",
    "msi": "엠에스아이",
    "muji": "무지",
    "musinsa": "무신사",
    "mustang": "머스탱",
    "myrealtrip": "마이리얼트립",
    "nars": "나스",
    "nasa": "나사",
    "nasdaq": "나스닥",
    "national geographic": "내셔널 지오그래픽",
    "naver": "네이버",
    "nba": "엔비에이",
    "ncsoft": "엔씨소프트",
    "nene chicken": "네네치킨",
    "nescafe": "네스카페",
    "nespresso": "네스프레소",
    "nestle": "네슬레",
    "netflix": "넷플릭스",
    "netmarble": "넷마블",
    "neuralink": "뉴럴링크",
    "new balance": "뉴발란스",
    "new york times": "뉴욕 타임스",
    "nexon": "넥슨",
    "nfl": "엔에프엘",
    "nike": "나이키",
    "nikon": "니콘",
    "nintendo": "닌텐도",
    "nintendo switch": "닌텐도 스위치",
    "nio": "니오",
    "nissan": "닛산",
    "nivea": "니베아",
    "nongshim": "농심",
    "north face": "노스페이스",
    "notion": "노션",
    "novartis": "노바티스",
    "novo nordisk": "노보 노디스크",
    "novotel": "노보텔",
    "nutella": "누텔라",
    "nvidia": "엔비디아",
    "oakley": "오클리",
    "oculus": "오큘러스",
    "office": "오피스",
    "olive young": "올리브영",
    "olympus": "올림푸스",
    "omega": "오메가",
    "onedrive": "원드라이브",
    "oneplus": "원플러스",
    "opel": "오펠",
    "openai": "오픈에이아이",
    "opensea": "오픈씨",
    "oppo": "오포",
    "oracle": "오라클",
    "oral b": "오랄비",
    "oreo": "오레오",
    "orion": "오리온",
    "ottogi": "오뚜기",
    "outback": "아웃백",
    "outlook": "아웃룩",
    "overwatch": "오버워치",
    "ozempic": "오젬픽",
    "p and g": "피앤지",
    "p&g": "피앤지",
    "pagani": "파가니",
    "palantir": "팔란티어",
    "palisade": "팰리세이드",
    "pampers": "팸퍼스",
    "panasonic": "파나소닉",
    "pandora": "판도라",
    "panerai": "파네라이",
    "papa john's": "파파존스",
    "papa johns": "파파존스",
    "paramount": "파라마운트",
    "paris baguette": "파리바게뜨",
    "patagonia": "파타고니아",
    "patek philippe": "파텍 필립",
    "patreon": "패트리온",
    "paypal": "페이팔",
    "pearl abyss": "펄어비스",
    "peloton": "펠로톤",
    "pentax": "펜탁스",
    "pepsi": "펩시",
    "perplexity": "퍼플렉시티",
    "perrier": "페리에",
    "peugeot": "푸조",
    "pfizer": "화이자",
    "philips": "필립스",
    "photoshop": "포토샵",
    "pinduoduo": "핀둬둬",
    "pinterest": "핀터레스트",
    "pirelli": "피렐리",
    "pixar": "픽사",
    "pixel": "픽셀",
    "pizza hut": "피자헛",
    "playstation": "플레이스테이션",
    "pocari sweat": "포카리스웨트",
    "pokemon": "포켓몬",
    "polaroid": "폴라로이드",
    "polestar": "폴스타",
    "polo ralph lauren": "폴로 랄프 로렌",
    "popeyes": "파파이스",
    "porsche": "포르쉐",
    "posco": "포스코",
    "powerade": "파워에이드",
    "powerpoint": "파워포인트",
    "prada": "프라다",
    "premier league": "프리미어 리그",
    "premiere pro": "프리미어 프로",
    "prime video": "프라임 비디오",
    "pringles": "프링글스",
    "procter and gamble": "프록터 앤 갬블",
    "prudential": "푸르덴셜",
    "pulmuone": "풀무원",
    "puma": "푸마",
    "qantas": "콴타스",
    "qatar airways": "카타르항공",
    "quaker": "퀘이커",
    "qualcomm": "퀄컴",
    "quora": "쿼라",
    "radeon": "라데온",
    "rakuten": "라쿠텐",
    "ralph lauren": "랄프 로렌",
    "range rover": "레인지로버",
    "ray ban": "레이밴",
    "ray-ban": "레이밴",
    "raytheon": "레이시온",
    "razer": "레이저",
    "red bull": "레드불",
    "red hat": "레드햇",
    "reddit": "레딧",
    "reebok": "리복",
    "remy martin": "레미 마르탱",
    "renault": "르노",
    "replit": "레플릿",
    "reuters": "로이터",
    "riot games": "라이엇 게임즈",
    "ritz": "리츠",
    "ritz carlton": "리츠칼튼",
    "rivian": "리비안",
    "robinhood": "로빈후드",
    "roblox": "로블록스",
    "roche": "로슈",
    "rocket lab": "로켓 랩",
    "rockstar games": "락스타 게임즈",
    "rolex": "롤렉스",
    "rolls royce": "롤스로이스",
    "royal enfield": "로열 엔필드",
    "rtx": "알티엑스",
    "ryanair": "라이언에어",
    "ryzen": "라이젠",
    "s and p": "에스앤피",
    "s&p": "에스앤피",
    "saab": "사브",
    "safari": "사파리",
    "saint laurent": "생로랑",
    "salesforce": "세일즈포스",
    "salomon": "살로몬",
    "samsung": "삼성",
    "samsung biologics": "삼성바이오로직스",
    "samsung electronics": "삼성전자",
    "samsung pay": "삼성 페이",
    "samyang": "삼양",
    "sandisk": "샌디스크",
    "sanofi": "사노피",
    "santa fe": "싼타페",
    "sap": "에스에이피",
    "sapporo": "삿포로",
    "sbs": "에스비에스",
    "seagate": "씨게이트",
    "sega": "세가",
    "seiko": "세이코",
    "sennheiser": "젠하이저",
    "sensodyne": "센소다인",
    "seoul milk": "서울우유",
    "sephora": "세포라",
    "servicenow": "서비스나우",
    "shake shack": "쉐이크쉑",
    "sharp": "샤프",
    "shazam": "샤잠",
    "shein": "쉬인",
    "sheraton": "쉐라톤",
    "shin ramyun": "신라면",
    "shinhan": "신한",
    "shinsegae": "신세계",
    "shiseido": "시세이도",
    "shopee": "쇼피",
    "shopify": "쇼피파이",
    "siemens": "지멘스",
    "sigma": "시그마",
    "singapore airlines": "싱가포르항공",
    "siri": "시리",
    "sk": "에스케이",
    "sk hynix": "에스케이 하이닉스",
    "sk telecom": "에스케이텔레콤",
    "skechers": "스케쳐스",
    "skittles": "스키틀즈",
    "skoda": "스코다",
    "skype": "스카이프",
    "skyscanner": "스카이스캐너",
    "slack": "슬랙",
    "smilegate": "스마일게이트",
    "smirnoff": "스미노프",
    "snapchat": "스냅챗",
    "snapdragon": "스냅드래곤",
    "snickers": "스니커즈",
    "snowflake": "스노우플레이크",
    "socar": "쏘카",
    "solana": "솔라나",
    "sonata": "쏘나타",
    "sonos": "소노스",
    "sony": "소니",
    "sony pictures": "소니 픽처스",
    "sora": "소라",
    "sorento": "쏘렌토",
    "soundcloud": "사운드클라우드",
    "southwest": "사우스웨스트",
    "spacex": "스페이스엑스",
    "spao": "스파오",
    "spotify": "스포티파이",
    "sprite": "스프라이트",
    "square enix": "스퀘어 에닉스",
    "squarespace": "스퀘어스페이스",
    "ssangyong": "쌍용",
    "ssg": "에스에스지",
    "stable diffusion": "스테이블 디퓨전",
    "stack overflow": "스택 오버플로",
    "starbucks": "스타벅스",
    "starcraft": "스타크래프트",
    "starlink": "스타링크",
    "steam": "스팀",
    "stella artois": "스텔라 아르투아",
    "strava": "스트라바",
    "stripe": "스트라이프",
    "studio ghibli": "스튜디오 지브리",
    "stussy": "스투시",
    "subaru": "스바루",
    "substack": "서브스택",
    "subway": "서브웨이",
    "sulwhasoo": "설화수",
    "super mario": "슈퍼 마리오",
    "suzuki": "스즈키",
    "swarovski": "스와로브스키",
    "swatch": "스와치",
    "t way": "티웨이",
    "tabasco": "타바스코",
    "taco bell": "타코벨",
    "tag heuer": "태그호이어",
    "tamron": "탐론",
    "taobao": "타오바오",
    "tcl": "티씨엘",
    "telegram": "텔레그램",
    "temu": "테무",
    "tesco": "테스코",
    "tesla": "테슬라",
    "tether": "테더",
    "texas instruments": "텍사스 인스트루먼츠",
    "the body shop": "바디샵",
    "the north face": "노스페이스",
    "tic tac": "틱택",
    "tiffany": "티파니",
    "tiktok": "틱톡",
    "tim hortons": "팀 호튼스",
    "timberland": "팀버랜드",
    "tinder": "틴더",
    "tissot": "티쏘",
    "titleist": "타이틀리스트",
    "tizen": "타이젠",
    "tmon": "티몬",
    "toblerone": "토블론",
    "tommy hilfiger": "타미 힐피거",
    "topten": "탑텐",
    "toshiba": "도시바",
    "toss": "토스",
    "toss bank": "토스뱅크",
    "tous les jours": "뚜레쥬르",
    "toyota": "도요타",
    "trello": "트렐로",
    "tripadvisor": "트립어드바이저",
    "triumph": "트라이엄프",
    "trivago": "트리바고",
    "tsingtao": "칭따오",
    "tsmc": "티에스엠씨",
    "tucson": "투싼",
    "tumblr": "텀블러",
    "turkish airlines": "터키항공",
    "tving": "티빙",
    "tvn": "티비엔",
    "twilio": "트윌리오",
    "twinings": "트와이닝",
    "twitch": "트위치",
    "twitter": "트위터",
    "twix": "트윅스",
    "twosome place": "투썸플레이스",
    "tylenol": "타이레놀",
    "tyson": "타이슨",
    "uber": "우버",
    "uber eats": "우버 이츠",
    "ubisoft": "유비소프트",
    "ubs": "유비에스",
    "ubuntu": "우분투",
    "udemy": "유데미",
    "uefa": "유에파",
    "ugg": "어그",
    "under armour": "언더 아머",
    "unilever": "유니레버",
    "uniqlo": "유니클로",
    "united airlines": "유나이티드 항공",
    "unity": "유니티",
    "universal": "유니버설",
    "unreal engine": "언리얼 엔진",
    "upbit": "업비트",
    "ups": "유피에스",
    "valentino": "발렌티노",
    "valorant": "발로란트",
    "valve": "밸브",
    "vanguard": "뱅가드",
    "vans": "반스",
    "vaseline": "바세린",
    "venmo": "벤모",
    "versace": "베르사체",
    "vespa": "베스파",
    "viagra": "비아그라",
    "viber": "바이버",
    "victoria's secret": "빅토리아 시크릿",
    "victorias secret": "빅토리아 시크릿",
    "vietnam airlines": "베트남항공",
    "vimeo": "비메오",
    "vips": "빕스",
    "visa": "비자",
    "vision pro": "비전 프로",
    "visual studio": "비주얼 스튜디오",
    "vmware": "브이엠웨어",
    "vogue": "보그",
    "volkswagen": "폭스바겐",
    "volvo": "볼보",
    "vs code": "브이에스 코드",
    "walgreens": "월그린",
    "wall street journal": "월스트리트 저널",
    "walmart": "월마트",
    "walt disney": "월트 디즈니",
    "warner bros": "워너 브라더스",
    "watcha": "왓챠",
    "watson": "왓슨",
    "wavve": "웨이브",
    "waymo": "웨이모",
    "waze": "웨이즈",
    "wechat": "위챗",
    "weibo": "웨이보",
    "wells fargo": "웰스파고",
    "wendy's": "웬디스",
    "wendys": "웬디스",
    "western digital": "웨스턴 디지털",
    "wework": "위워크",
    "whatsapp": "왓츠앱",
    "whirlpool": "월풀",
    "wikipedia": "위키피디아",
    "wilson": "윌슨",
    "windows": "윈도우",
    "winix": "위닉스",
    "wix": "윅스",
    "wolfram alpha": "울프럼 알파",
    "woori bank": "우리은행",
    "wordpress": "워드프레스",
    "workday": "워크데이",
    "world of warcraft": "월드 오브 워크래프트",
    "wrangler": "랭글러",
    "wrigley": "리글리",
    "xbox": "엑스박스",
    "xiaomi": "샤오미",
    "xpeng": "샤오펑",
    "yakult": "야쿠르트",
    "yamaha": "야마하",
    "yanolja": "야놀자",
    "yelp": "옐프",
    "yogiyo": "요기요",
    "yonex": "요넥스",
    "youtube": "유튜브",
    "youtube music": "유튜브 뮤직",
    "yves saint laurent": "이브 생로랑",
    "zara": "자라",
    "zelda": "젤다",
    "zoom": "줌",
}

__all__ = ["BRANDS"]
