"""Business, finance, law and workplace vocabulary for Korean TTS."""
from __future__ import annotations

from typing import Dict

BUSINESS: Dict[str, str] = {
    "accelerator": "액셀러레이터",
    "accountant": "어카운턴트",
    "accounting": "어카운팅",
    "acquisition": "애퀴지션",
    "administrator": "어드미니스트레이터",
    "advertising": "애드버타이징",
    "advisor": "어드바이저",
    "agency": "에이전시",
    "agenda": "어젠다",
    "agent": "에이전트",
    "agreement": "어그리먼트",
    "alliance": "얼라이언스",
    "analyst": "애널리스트",
    "angel investor": "엔젤 인베스터",
    "annual": "애뉴얼",
    "annual report": "애뉴얼 리포트",
    "appeal": "어필",
    "arbitrage": "아비트리지",
    "arbitration": "아비트레이션",
    "architect": "아키텍트",
    "asset": "애셋",
    "asset management": "애셋 매니지먼트",
    "assistant": "어시스턴트",
    "associate": "어소시에이트",
    "association": "어소시에이션",
    "atm": "에이티엠",
    "audit": "오디트",
    "auditor": "오디터",
    "b2b": "비투비",
    "b2c": "비투씨",
    "back office": "백 오피스",
    "bailout": "베일아웃",
    "balance": "밸런스",
    "balance sheet": "밸런스 시트",
    "bank": "뱅크",
    "bank account": "뱅크 어카운트",
    "banker": "뱅커",
    "banking": "뱅킹",
    "bankruptcy": "뱅크럽시",
    "bear market": "베어 마켓",
    "bearish": "베어리시",
    "benchmark": "벤치마크",
    "benchmarking": "벤치마킹",
    "benefit": "베네핏",
    "benefits": "베네피츠",
    "blue chip": "블루칩",
    "board": "보드",
    "board meeting": "보드 미팅",
    "board member": "보드 멤버",
    "bond": "본드",
    "bonus": "보너스",
    "bookkeeping": "북키핑",
    "boom": "붐",
    "bootstrapping": "부트스트래핑",
    "boss": "보스",
    "brainstorming": "브레인스토밍",
    "branch": "브랜치",
    "brand": "브랜드",
    "branding": "브랜딩",
    "break-even": "브레이크 이븐",
    "briefing": "브리핑",
    "broker": "브로커",
    "bubble": "버블",
    "budget": "버짓",
    "building": "빌딩",
    "bull market": "불 마켓",
    "bullish": "불리시",
    "burn rate": "번 레이트",
    "business": "비즈니스",
    "business card": "비즈니스 카드",
    "business model": "비즈니스 모델",
    "business plan": "비즈니스 플랜",
    "buyback": "바이백",
    "calendar": "캘린더",
    "campaign": "캠페인",
    "candidate": "캔디데이트",
    "cap table": "캡 테이블",
    "capex": "캐펙스",
    "capital": "캐피털",
    "capital gain": "캐피털 게인",
    "capital market": "캐피털 마켓",
    "capitalism": "캐피털리즘",
    "career": "커리어",
    "cargo": "카고",
    "carrier": "캐리어",
    "case study": "케이스 스터디",
    "cash": "캐시",
    "cash flow": "캐시 플로",
    "cashback": "캐시백",
    "cashier": "캐셔",
    "central bank": "센트럴 뱅크",
    "ceo": "씨이오",
    "cfo": "씨에프오",
    "chain": "체인",
    "chairman": "체어맨",
    "checklist": "체크리스트",
    "chief": "치프",
    "chief executive officer": "치프 이그제큐티브 오피서",
    "clause": "클로즈",
    "clerk": "클러크",
    "click": "클릭",
    "client": "클라이언트",
    "cmo": "씨엠오",
    "coffee break": "커피 브레이크",
    "collaboration": "컬래버레이션",
    "collateral": "컬래터럴",
    "colleague": "컬리그",
    "commercial": "커머셜",
    "commodity": "커모디티",
    "company": "컴퍼니",
    "compensation": "컴펜세이션",
    "competition": "컴피티션",
    "competitor": "컴페티터",
    "compliance": "컴플라이언스",
    "condo": "콘도",
    "conference": "콘퍼런스",
    "conference call": "콘퍼런스 콜",
    "consent": "컨센트",
    "construction": "컨스트럭션",
    "consultant": "컨설턴트",
    "consulting": "컨설팅",
    "consumer": "컨슈머",
    "consumption": "컨섬션",
    "container": "컨테이너",
    "content marketing": "콘텐츠 마케팅",
    "contract": "컨트랙트",
    "contractor": "컨트랙터",
    "conversion": "컨버전",
    "conversion rate": "컨버전 레이트",
    "coo": "씨오오",
    "coordinator": "코디네이터",
    "copyright": "카피라이트",
    "copywriting": "카피라이팅",
    "corporate": "코퍼릿",
    "corporation": "코퍼레이션",
    "correction": "커렉션",
    "cost": "코스트",
    "court": "코트",
    "cover letter": "커버 레터",
    "coworker": "코워커",
    "crash": "크래시",
    "credit": "크레디트",
    "credit card": "크레디트 카드",
    "credit rating": "크레디트 레이팅",
    "credit score": "크레디트 스코어",
    "crisis": "크라이시스",
    "crm": "씨알엠",
    "cto": "씨티오",
    "currency": "커런시",
    "customer": "커스터머",
    "customer service": "커스터머 서비스",
    "customs": "커스텀스",
    "dashboard": "대시보드",
    "deadline": "데드라인",
    "deal": "딜",
    "debit card": "데빗 카드",
    "debt": "데트",
    "default": "디폴트",
    "defendant": "디펜던트",
    "deflation": "디플레이션",
    "delivery": "딜리버리",
    "demand": "디맨드",
    "demo": "데모",
    "department": "디파트먼트",
    "deposit": "디파짓",
    "depreciation": "디프리시에이션",
    "depression": "디프레션",
    "derivative": "디리버티브",
    "designer": "디자이너",
    "desk": "데스크",
    "developer": "디벨로퍼",
    "director": "디렉터",
    "disclaimer": "디스클레이머",
    "discount": "디스카운트",
    "dispute": "디스퓨트",
    "distribution": "디스트리뷰션",
    "distributor": "디스트리뷰터",
    "diversity": "다이버시티",
    "dividend": "디비던드",
    "document": "도큐먼트",
    "dow jones": "다우존스",
    "downsizing": "다운사이징",
    "draft": "드래프트",
    "due diligence": "듀 딜리전스",
    "earnings": "어닝스",
    "earnings call": "어닝스 콜",
    "economics": "이코노믹스",
    "economy": "이코노미",
    "efficiency": "이피션시",
    "email": "이메일",
    "employee": "임플로이",
    "employer": "임플로이어",
    "employment": "임플로이먼트",
    "engagement": "인게이지먼트",
    "engineer": "엔지니어",
    "enterprise": "엔터프라이즈",
    "equity": "에쿼티",
    "escrow": "에스크로",
    "esg": "이에스지",
    "etf": "이티에프",
    "event": "이벤트",
    "evidence": "에비던스",
    "exchange": "익스체인지",
    "exchange rate": "익스체인지 레이트",
    "executive": "이그제큐티브",
    "exit": "엑시트",
    "expense": "익스펜스",
    "export": "익스포트",
    "federal reserve": "페더럴 리저브",
    "feedback": "피드백",
    "firm": "펌",
    "fiscal policy": "피스컬 폴리시",
    "fiscal year": "피스컬 이어",
    "follow-up": "팔로업",
    "forecast": "포캐스트",
    "founder": "파운더",
    "franchise": "프랜차이즈",
    "fraud": "프로드",
    "freelance": "프리랜스",
    "freelancer": "프리랜서",
    "freight": "프레이트",
    "fulfillment": "풀필먼트",
    "fund": "펀드",
    "fund manager": "펀드 매니저",
    "funding": "펀딩",
    "funnel": "퍼널",
    "futures": "퓨처스",
    "gdp": "지디피",
    "globalization": "글로벌라이제이션",
    "governance": "거버넌스",
    "gross": "그로스",
    "gross domestic product": "그로스 도메스틱 프로덕트",
    "gross margin": "그로스 마진",
    "growth": "그로스",
    "growth rate": "그로스 레이트",
    "guarantee": "개런티",
    "guideline": "가이드라인",
    "headhunter": "헤드헌터",
    "headhunting": "헤드헌팅",
    "headquarters": "헤드쿼터스",
    "hedge": "헤지",
    "hedge fund": "헤지 펀드",
    "hiring": "하이어링",
    "holding company": "홀딩 컴퍼니",
    "hr": "에이치알",
    "human resources": "휴먼 리소스",
    "hybrid work": "하이브리드 워크",
    "imf": "아이엠에프",
    "import": "임포트",
    "in-house": "인하우스",
    "income": "인컴",
    "incubator": "인큐베이터",
    "index": "인덱스",
    "index fund": "인덱스 펀드",
    "industry": "인더스트리",
    "inflation": "인플레이션",
    "influencer": "인플루언서",
    "infra": "인프라",
    "infrastructure": "인프라스트럭처",
    "innovation": "이노베이션",
    "installment": "인스톨먼트",
    "institution": "인스티튜션",
    "insurance": "인슈어런스",
    "intellectual property": "인텔렉추얼 프로퍼티",
    "interest": "인터레스트",
    "interest rate": "인터레스트 레이트",
    "intern": "인턴",
    "interview": "인터뷰",
    "inventory": "인벤토리",
    "investment": "인베스트먼트",
    "investor": "인베스터",
    "invoice": "인보이스",
    "ipo": "아이피오",
    "issue": "이슈",
    "job description": "잡 디스크립션",
    "job fair": "잡 페어",
    "joint venture": "조인트 벤처",
    "judge": "저지",
    "jury": "주리",
    "kickoff": "킥오프",
    "kpi": "케이피아이",
    "labor": "레이버",
    "labor union": "레이버 유니언",
    "landing page": "랜딩 페이지",
    "landlord": "랜드로드",
    "lawyer": "로이어",
    "layoff": "레이오프",
    "lead time": "리드 타임",
    "leadership": "리더십",
    "lease": "리스",
    "ledger": "레저",
    "legal": "리걸",
    "leverage": "레버리지",
    "liability": "라이어빌리티",
    "license": "라이선스",
    "liquidity": "리퀴디티",
    "litigation": "리티게이션",
    "loan": "론",
    "logistics": "로지스틱스",
    "loyalty": "로열티",
    "m&a": "엠앤에이",
    "management": "매니지먼트",
    "manager": "매니저",
    "manual": "매뉴얼",
    "manufacturer": "매뉴팩처러",
    "manufacturing": "매뉴팩처링",
    "margin": "마진",
    "market": "마켓",
    "market cap": "마켓 캡",
    "market research": "마켓 리서치",
    "market share": "마켓 셰어",
    "marketer": "마케터",
    "marketing": "마케팅",
    "meeting": "미팅",
    "memo": "메모",
    "mentor": "멘토",
    "mentoring": "멘토링",
    "merger": "머저",
    "milestone": "마일스톤",
    "mission": "미션",
    "monetary policy": "머니터리 폴리시",
    "monopoly": "모노폴리",
    "mortgage": "모기지",
    "mutual fund": "뮤추얼 펀드",
    "mvp": "엠브이피",
    "nasdaq": "나스닥",
    "nda": "엔디에이",
    "negotiation": "니고시에이션",
    "net income": "넷 인컴",
    "net profit": "넷 프로핏",
    "network": "네트워크",
    "networking": "네트워킹",
    "newsletter": "뉴스레터",
    "niche": "니치",
    "oecd": "오이씨디",
    "office": "오피스",
    "offsite": "오프사이트",
    "onboarding": "온보딩",
    "operation": "오퍼레이션",
    "operator": "오퍼레이터",
    "opportunity": "오퍼추니티",
    "option": "옵션",
    "order": "오더",
    "organization": "오거나이제이션",
    "orientation": "오리엔테이션",
    "output": "아웃풋",
    "outsourcing": "아웃소싱",
    "overdraft": "오버드래프트",
    "overhead": "오버헤드",
    "overtime": "오버타임",
    "packaging": "패키징",
    "partner": "파트너",
    "partnership": "파트너십",
    "patent": "페이턴트",
    "payment": "페이먼트",
    "payroll": "페이롤",
    "penalty": "페널티",
    "pension": "펜션",
    "pension fund": "펜션 펀드",
    "performance": "퍼포먼스",
    "performance review": "퍼포먼스 리뷰",
    "pitch": "피치",
    "pitch deck": "피치 덱",
    "pivot": "피벗",
    "policy": "폴리시",
    "portfolio": "포트폴리오",
    "position": "포지션",
    "positioning": "포지셔닝",
    "pr": "피알",
    "premium": "프리미엄",
    "presentation": "프레젠테이션",
    "president": "프레지던트",
    "press release": "프레스 릴리스",
    "price": "프라이스",
    "principal": "프린시펄",
    "priority": "프라이오리티",
    "private equity": "프라이빗 에쿼티",
    "probation": "프로베이션",
    "process": "프로세스",
    "procurement": "프로큐어먼트",
    "producer": "프로듀서",
    "product": "프로덕트",
    "productivity": "프로덕티비티",
    "profit": "프로핏",
    "programmer": "프로그래머",
    "project": "프로젝트",
    "promotion": "프로모션",
    "property": "프로퍼티",
    "proposal": "프로포절",
    "prosecutor": "프로시큐터",
    "protocol": "프로토콜",
    "public relations": "퍼블릭 릴레이션스",
    "purchase": "퍼처스",
    "quality": "퀄리티",
    "quality control": "퀄리티 컨트롤",
    "quarter": "쿼터",
    "quarterly": "쿼털리",
    "quarterly report": "쿼털리 리포트",
    "quota": "쿼터",
    "rally": "랠리",
    "real estate": "리얼 에스테이트",
    "realtor": "리얼터",
    "receipt": "리시트",
    "recession": "리세션",
    "recruiter": "리크루터",
    "recruiting": "리크루팅",
    "recruitment": "리크루트먼트",
    "refund": "리펀드",
    "regulation": "레귤레이션",
    "remote work": "리모트 워크",
    "rent": "렌트",
    "rental": "렌털",
    "report": "리포트",
    "researcher": "리서처",
    "residential": "레지덴셜",
    "resource": "리소스",
    "restructuring": "리스트럭처링",
    "retail": "리테일",
    "retailer": "리테일러",
    "retention": "리텐션",
    "retirement": "리타이어먼트",
    "return": "리턴",
    "revenue": "레비뉴",
    "risk": "리스크",
    "roadmap": "로드맵",
    "roi": "알오아이",
    "royalty": "로열티",
    "runway": "런웨이",
    "s&p 500": "에스앤피 오백",
    "salary": "샐러리",
    "sales": "세일즈",
    "savings": "세이빙스",
    "scale-up": "스케일업",
    "schedule": "스케줄",
    "sector": "섹터",
    "securities": "시큐리티스",
    "seed round": "시드 라운드",
    "segment": "세그먼트",
    "segmentation": "세그먼테이션",
    "seminar": "세미나",
    "series a": "시리즈 에이",
    "series b": "시리즈 비",
    "series c": "시리즈 씨",
    "service": "서비스",
    "session": "세션",
    "settlement": "세틀먼트",
    "severance": "세버런스",
    "share": "셰어",
    "shareholder": "셰어홀더",
    "shipment": "시프먼트",
    "shipping": "시핑",
    "short selling": "쇼트 셀링",
    "signature": "시그니처",
    "slogan": "슬로건",
    "solution": "솔루션",
    "sourcing": "소싱",
    "specialist": "스페셜리스트",
    "spin-off": "스핀오프",
    "sponsor": "스폰서",
    "sponsorship": "스폰서십",
    "staff": "스태프",
    "staffing": "스태핑",
    "stagflation": "스태그플레이션",
    "stakeholder": "스테이크홀더",
    "standard": "스탠더드",
    "startup": "스타트업",
    "statement": "스테이트먼트",
    "stimulus": "스티뮬러스",
    "stock": "스톡",
    "stock market": "스톡 마켓",
    "strategy": "스트래티지",
    "strike": "스트라이크",
    "subsidiary": "서브시디어리",
    "subsidy": "서브시디",
    "summary": "서머리",
    "supervisor": "슈퍼바이저",
    "supplier": "서플라이어",
    "supply": "서플라이",
    "supply and demand": "서플라이 앤드 디맨드",
    "supply chain": "서플라이 체인",
    "survey": "서베이",
    "sustainability": "서스테이너빌리티",
    "swap": "스와프",
    "synergy": "시너지",
    "takeover": "테이크오버",
    "talent": "탤런트",
    "target": "타깃",
    "target audience": "타깃 오디언스",
    "tariff": "태리프",
    "task": "태스크",
    "tax": "택스",
    "team leader": "팀 리더",
    "teamwork": "팀워크",
    "technician": "테크니션",
    "template": "템플릿",
    "tenant": "테넌트",
    "term sheet": "텀 시트",
    "terms and conditions": "텀스 앤드 컨디션스",
    "timeline": "타임라인",
    "tracking": "트래킹",
    "trade": "트레이드",
    "trade deficit": "트레이드 데피시트",
    "trademark": "트레이드마크",
    "trader": "트레이더",
    "trading": "트레이딩",
    "traffic": "트래픽",
    "trainee": "트레이니",
    "training": "트레이닝",
    "transaction": "트랜잭션",
    "transfer": "트랜스퍼",
    "treasury": "트레저리",
    "trend": "트렌드",
    "trial": "트라이얼",
    "turnover": "턴오버",
    "underwriting": "언더라이팅",
    "unemployment": "언임플로이먼트",
    "unicorn": "유니콘",
    "union": "유니언",
    "vacancy": "베이컨시",
    "valuation": "밸류에이션",
    "value": "밸류",
    "value chain": "밸류 체인",
    "vc": "브이씨",
    "vendor": "벤더",
    "venture": "벤처",
    "venture capital": "벤처 캐피털",
    "verdict": "버딕트",
    "vertical": "버티컬",
    "vice president": "바이스 프레지던트",
    "viral": "바이럴",
    "vision": "비전",
    "volatility": "볼래틸리티",
    "volume": "볼륨",
    "wage": "웨이지",
    "wall street": "월가",
    "warehouse": "웨어하우스",
    "warranty": "워런티",
    "welfare": "웰페어",
    "white paper": "화이트 페이퍼",
    "whiteboard": "화이트보드",
    "wholesale": "홀세일",
    "wholesaler": "홀세일러",
    "witness": "위트니스",
    "work life balance": "워크 라이프 밸런스",
    "workflow": "워크플로",
    "workforce": "워크포스",
    "workshop": "워크숍",
    "world bank": "월드 뱅크",
    "write-off": "라이트 오프",
    "wto": "더블유티오",
    "yield": "일드",
    "zoning": "조닝",
}

__all__ = ["BUSINESS"]
