"""Sports, entertainment, and arts vocabulary appearing in Korean text."""
from __future__ import annotations

from typing import Dict

CULTURE: Dict[str, str] = {
    "3d": "쓰리디",
    "accessory": "액세서리",
    "accordion": "아코디언",
    "ace": "에이스",
    "acoustic": "어쿠스틱",
    "acrylic": "아크릴",
    "action": "액션",
    "actor": "배우",
    "actress": "여배우",
    "aesthetic": "에스테틱",
    "agency": "에이전시",
    "albatross": "앨버트로스",
    "album": "앨범",
    "all star": "올스타",
    "allstar": "올스타",
    "alto": "알토",
    "amateur": "아마추어",
    "american football": "미식축구",
    "amp": "앰프",
    "animation": "애니메이션",
    "anniversary": "애니버서리",
    "aperture": "조리개",
    "aquarium": "아쿠아리움",
    "arcade": "아케이드",
    "archery": "양궁",
    "architecture": "아키텍처",
    "arena": "아레나",
    "aria": "아리아",
    "art": "아트",
    "artist": "아티스트",
    "artwork": "아트워크",
    "assist": "어시스트",
    "atelier": "아틀리에",
    "athlete": "애슬리트",
    "auction": "옥션",
    "audiobook": "오디오북",
    "audition": "오디션",
    "author": "저자",
    "avant-garde": "아방가르드",
    "avatar": "아바타",
    "award": "어워드",
    "away": "어웨이",
    "backhand": "백핸드",
    "backpacking": "백패킹",
    "backstage": "백스테이지",
    "badminton": "배드민턴",
    "baking": "베이킹",
    "ball": "볼",
    "ballad": "발라드",
    "ballerina": "발레리나",
    "ballet": "발레",
    "band": "밴드",
    "barbecue": "바비큐",
    "baritone": "바리톤",
    "baroque": "바로크",
    "base": "베이스",
    "baseball": "야구",
    "basketball": "농구",
    "bass": "베이스",
    "bat": "배트",
    "batter": "배터",
    "beanie": "비니",
    "beat": "비트",
    "beauty": "뷰티",
    "belt": "벨트",
    "bestseller": "베스트셀러",
    "beta": "베타",
    "biennale": "비엔날레",
    "billboard": "빌보드",
    "billiards": "당구",
    "birdie": "버디",
    "birthday": "생일",
    "black friday": "블랙 프라이데이",
    "block": "블록",
    "blockbuster": "블록버스터",
    "blocking": "블로킹",
    "blouse": "블라우스",
    "blues": "블루스",
    "blusher": "블러셔",
    "board game": "보드게임",
    "bobsleigh": "봅슬레이",
    "bogey": "보기",
    "bollywood": "발리우드",
    "bookstore": "서점",
    "boots": "부츠",
    "boss": "보스",
    "bowling": "볼링",
    "box office": "박스오피스",
    "boxer": "복서",
    "boxing": "복싱",
    "bpm": "비피엠",
    "brand": "브랜드",
    "breakdance": "브레이크댄스",
    "bridge": "브리지",
    "broadcast": "브로드캐스트",
    "broadway": "브로드웨이",
    "bronze medal": "동메달",
    "brush": "브러시",
    "bullpen": "불펜",
    "bundesliga": "분데스리가",
    "bungee jumping": "번지점프",
    "bunker": "벙커",
    "bunt": "번트",
    "busking": "버스킹",
    "butterfly": "버터플라이",
    "buzzer beater": "버저비터",
    "caddie": "캐디",
    "calligraphy": "캘리그래피",
    "cameo": "카메오",
    "camera": "카메라",
    "camp": "캠프",
    "camping": "캠핑",
    "canoe": "카누",
    "canvas": "캔버스",
    "captain": "캡틴",
    "card game": "카드 게임",
    "cardigan": "카디건",
    "carnival": "카니발",
    "cartoon": "카툰",
    "casino": "카지노",
    "cassette": "카세트",
    "cast": "캐스트",
    "casting": "캐스팅",
    "casual": "캐주얼",
    "catcher": "캐처",
    "catwalk": "캣워크",
    "cd": "시디",
    "celebrity": "셀러브리티",
    "cello": "첼로",
    "center": "센터",
    "ceramic": "세라믹",
    "ceremony": "세리머니",
    "cgi": "시지아이",
    "champion": "챔피언",
    "champions league": "챔피언스리그",
    "championship": "챔피언십",
    "changeup": "체인지업",
    "channel": "채널",
    "chapter": "챕터",
    "character": "캐릭터",
    "chart": "차트",
    "cheat": "치트",
    "checkpoint": "체크포인트",
    "cheerleader": "치어리더",
    "chess": "체스",
    "chord": "코드",
    "choreographer": "안무가",
    "choreography": "안무",
    "chorus": "코러스",
    "christmas": "크리스마스",
    "cinema": "시네마",
    "cinematography": "시네마토그래피",
    "circus": "서커스",
    "clarinet": "클라리넷",
    "classic": "클래식",
    "classical": "클래식",
    "cleanser": "클렌저",
    "climbing": "클라이밍",
    "clip": "클립",
    "close up": "클로즈업",
    "closer": "클로저",
    "coach": "코치",
    "coat": "코트",
    "collage": "콜라주",
    "collection": "컬렉션",
    "collector": "컬렉터",
    "column": "칼럼",
    "combo": "콤보",
    "comeback": "컴백",
    "comedian": "코미디언",
    "comedy": "코미디",
    "comic": "코믹",
    "comics": "코믹스",
    "composition": "컴포지션",
    "concealer": "컨실러",
    "concept": "콘셉트",
    "concept art": "콘셉트 아트",
    "concert": "콘서트",
    "concerto": "콘체르토",
    "conductor": "지휘자",
    "console": "콘솔",
    "contrast": "콘트라스트",
    "controller": "컨트롤러",
    "cooking": "쿠킹",
    "copyright": "저작권",
    "corner": "코너",
    "corner kick": "코너킥",
    "cosmetics": "코스메틱",
    "costume": "코스튬",
    "cotton": "코튼",
    "countdown": "카운트다운",
    "court": "코트",
    "couture": "쿠튀르",
    "cover": "커버",
    "craft": "크래프트",
    "creator": "크리에이터",
    "credits": "크레디트",
    "cricket": "크리켓",
    "crossfit": "크로스핏",
    "cubism": "큐비즘",
    "curator": "큐레이터",
    "curling": "컬링",
    "curtain call": "커튼콜",
    "curveball": "커브볼",
    "cushion": "쿠션",
    "cut": "컷",
    "cycling": "사이클링",
    "dance": "댄스",
    "dancer": "댄서",
    "dancing": "댄싱",
    "darts": "다트",
    "debut": "데뷔",
    "defender": "디펜더",
    "demo": "데모",
    "denim": "데님",
    "derby": "더비",
    "design": "디자인",
    "designer": "디자이너",
    "deuce": "듀스",
    "dice": "다이스",
    "director": "디렉터",
    "disco": "디스코",
    "disney": "디즈니",
    "diving": "다이빙",
    "diy": "디아이와이",
    "dj": "디제이",
    "dlc": "디엘시",
    "documentary": "다큐멘터리",
    "doping": "도핑",
    "double play": "더블 플레이",
    "draft": "드래프트",
    "drama": "드라마",
    "draw": "드로",
    "drawing": "드로잉",
    "dress": "드레스",
    "dribble": "드리블",
    "driver": "드라이버",
    "drone": "드론",
    "drum": "드럼",
    "drums": "드럼",
    "dubbing": "더빙",
    "duet": "듀엣",
    "dugout": "더그아웃",
    "dumbbell": "덤벨",
    "dungeon": "던전",
    "dunk": "덩크",
    "e-book": "이북",
    "e-sports": "이스포츠",
    "eagle": "이글",
    "earphone": "이어폰",
    "easter": "부활절",
    "ebook": "이북",
    "echo": "에코",
    "editing": "에디팅",
    "edition": "에디션",
    "editor": "에디터",
    "edm": "이디엠",
    "electric guitar": "일렉트릭 기타",
    "encore": "앙코르",
    "ending": "엔딩",
    "ensemble": "앙상블",
    "entertainment": "엔터테인먼트",
    "ep": "이피",
    "epilogue": "에필로그",
    "episode": "에피소드",
    "equalizer": "이퀄라이저",
    "error": "에러",
    "esports": "이스포츠",
    "essay": "에세이",
    "essence": "에센스",
    "exhibition": "전시회",
    "extra": "엑스트라",
    "eyeliner": "아이라이너",
    "eyeshadow": "아이섀도",
    "fabric": "패브릭",
    "fair play": "페어플레이",
    "fairway": "페어웨이",
    "falsetto": "팔세토",
    "fan": "팬",
    "fan club": "팬클럽",
    "fandom": "팬덤",
    "fantasy": "판타지",
    "fashion": "패션",
    "fastball": "패스트볼",
    "fencing": "펜싱",
    "festival": "페스티벌",
    "fiction": "픽션",
    "fifa": "피파",
    "figure skating": "피겨 스케이팅",
    "film": "필름",
    "filter": "필터",
    "finale": "피날레",
    "finals": "결승전",
    "fireworks": "불꽃놀이",
    "fishing": "낚시",
    "fitness": "피트니스",
    "fitting": "피팅",
    "flash": "플래시",
    "flute": "플루트",
    "focus": "포커스",
    "footage": "푸티지",
    "football": "축구",
    "forehand": "포핸드",
    "fork ball": "포크볼",
    "formal": "포멀",
    "formation": "포메이션",
    "forward": "포워드",
    "foul": "파울",
    "foul ball": "파울볼",
    "foundation": "파운데이션",
    "fps": "에프피에스",
    "frame": "프레임",
    "frame rate": "프레임 레이트",
    "free kick": "프리킥",
    "free throw": "자유투",
    "freestyle": "프리스타일",
    "funk": "펑크",
    "gallery": "갤러리",
    "game": "게임",
    "gamer": "게이머",
    "gaming": "게이밍",
    "gardening": "가드닝",
    "gayageum": "가야금",
    "genre": "장르",
    "gift": "기프트",
    "gimbal": "짐벌",
    "glove": "글러브",
    "goal": "골",
    "goalkeeper": "골키퍼",
    "gold medal": "금메달",
    "golf": "골프",
    "gothic": "고딕",
    "graffiti": "그라피티",
    "grammy": "그래미",
    "grand slam": "그랜드슬램",
    "graphic design": "그래픽 디자인",
    "green": "그린",
    "green screen": "그린 스크린",
    "guild": "길드",
    "guitar": "기타",
    "gym": "짐",
    "gymnastics": "체조",
    "hairstyle": "헤어스타일",
    "halfpipe": "하프파이프",
    "halftime": "하프타임",
    "halloween": "핼러윈",
    "handbag": "핸드백",
    "handicap": "핸디캡",
    "hardcover": "하드커버",
    "harmonica": "하모니카",
    "harmony": "하모니",
    "harp": "하프",
    "hat trick": "해트트릭",
    "haute couture": "오트 쿠튀르",
    "header": "헤더",
    "headphone": "헤드폰",
    "heavy metal": "헤비메탈",
    "heels": "힐",
    "helmet": "헬멧",
    "hero": "히어로",
    "heroine": "히로인",
    "highlight": "하이라이트",
    "highlighter": "하이라이터",
    "hiking": "하이킹",
    "hip hop": "힙합",
    "hip hop dance": "힙합 댄스",
    "hiphop": "힙합",
    "hobby": "취미",
    "hockey": "하키",
    "hole in one": "홀인원",
    "holiday": "홀리데이",
    "hollywood": "할리우드",
    "home": "홈",
    "home run": "홈런",
    "homerun": "홈런",
    "honeymoon": "허니문",
    "hoodie": "후디",
    "hook": "훅",
    "horror": "호러",
    "hurdle": "허들",
    "ice hockey": "아이스하키",
    "idol": "아이돌",
    "illustration": "일러스트레이션",
    "illustrator": "일러스트레이터",
    "imax": "아이맥스",
    "impressionism": "인상주의",
    "indie": "인디",
    "infield": "인필드",
    "influencer": "인플루언서",
    "inning": "이닝",
    "instagram": "인스타그램",
    "intro": "인트로",
    "inventory": "인벤토리",
    "iron": "아이언",
    "iso": "아이에스오",
    "item": "아이템",
    "j-pop": "제이팝",
    "jab": "잽",
    "jacket": "재킷",
    "jazz": "재즈",
    "jeans": "진",
    "jewelry": "주얼리",
    "jogging": "조깅",
    "journal": "저널",
    "joystick": "조이스틱",
    "judo": "유도",
    "k league": "케이리그",
    "k-pop": "케이팝",
    "karaoke": "가라오케",
    "karate": "가라테",
    "kayak": "카약",
    "kbo": "케이비오",
    "keyboard": "키보드",
    "kickboxing": "킥복싱",
    "kickoff": "킥오프",
    "knit": "니트",
    "knitting": "뜨개질",
    "knockout": "녹아웃",
    "knuckleball": "너클볼",
    "kpop": "케이팝",
    "la liga": "라리가",
    "lace": "레이스",
    "lag": "랙",
    "landscape": "랜드스케이프",
    "lane": "레인",
    "layout": "레이아웃",
    "layup": "레이업",
    "league": "리그",
    "leather": "레더",
    "legend": "레전드",
    "lego": "레고",
    "lens": "렌즈",
    "level up": "레벨 업",
    "levelup": "레벨업",
    "libero": "리베로",
    "lighting": "라이팅",
    "linen": "리넨",
    "lineup": "라인업",
    "lip balm": "립밤",
    "lipstick": "립스틱",
    "literature": "문학",
    "live": "라이브",
    "logo": "로고",
    "lookbook": "룩북",
    "loser": "루저",
    "lotion": "로션",
    "lp": "엘피",
    "luge": "루지",
    "luxury": "럭셔리",
    "lyrics": "가사",
    "magazine": "매거진",
    "magic": "매직",
    "magic show": "매직쇼",
    "makeup": "메이크업",
    "manager": "매니저",
    "manga": "망가",
    "manicure": "매니큐어",
    "manuscript": "원고",
    "marathon": "마라톤",
    "martial arts": "무술",
    "marvel": "마블",
    "mascara": "마스카라",
    "mascot": "마스코트",
    "mastering": "마스터링",
    "masterpiece": "마스터피스",
    "match": "매치",
    "match point": "매치 포인트",
    "matchmaking": "매치메이킹",
    "mc": "엠시",
    "medal": "메달",
    "meditation": "명상",
    "melody": "멜로디",
    "metal": "메탈",
    "metaphor": "메타포",
    "metronome": "메트로놈",
    "mic": "마이크",
    "microphone": "마이크",
    "midfielder": "미드필더",
    "minimal": "미니멀",
    "minimalism": "미니멀리즘",
    "mixing": "믹싱",
    "mixtape": "믹스테이프",
    "mlb": "엠엘비",
    "mma": "엠엠에이",
    "mmorpg": "엠엠오알피지",
    "mod": "모드",
    "model": "모델",
    "modernism": "모더니즘",
    "moisturizer": "모이스처라이저",
    "monochrome": "모노크롬",
    "montage": "몽타주",
    "mosaic": "모자이크",
    "motif": "모티프",
    "mound": "마운드",
    "movie": "무비",
    "muse": "뮤즈",
    "museum": "뮤지엄",
    "music": "뮤직",
    "musical": "뮤지컬",
    "musician": "뮤지션",
    "mvp": "엠브이피",
    "mystery": "미스터리",
    "nail art": "네일 아트",
    "narrative": "내러티브",
    "narrator": "내레이터",
    "nba": "엔비에이",
    "neon": "네온",
    "net": "네트",
    "netflix": "넷플릭스",
    "new year": "새해",
    "nfl": "엔에프엘",
    "no hitter": "노히터",
    "non-fiction": "논픽션",
    "nonfiction": "논픽션",
    "noraebang": "노래방",
    "note": "노트",
    "novel": "소설",
    "novelist": "소설가",
    "npc": "엔피시",
    "octave": "옥타브",
    "offside": "오프사이드",
    "olympic": "올림픽",
    "olympics": "올림픽",
    "open world": "오픈 월드",
    "opening": "오프닝",
    "opera": "오페라",
    "orchestra": "오케스트라",
    "origami": "종이접기",
    "oscar": "오스카",
    "ost": "오에스티",
    "out": "아웃",
    "outfield": "아웃필드",
    "outfit": "아웃핏",
    "outro": "아웃트로",
    "overtime": "오버타임",
    "painting": "페인팅",
    "palette": "팔레트",
    "pansori": "판소리",
    "pantomime": "팬터마임",
    "paperback": "페이퍼백",
    "par": "파",
    "parade": "퍼레이드",
    "paragliding": "패러글라이딩",
    "paralympic": "패럴림픽",
    "party": "파티",
    "pass": "패스",
    "pastel": "파스텔",
    "patch": "패치",
    "patch note": "패치 노트",
    "pattern": "패턴",
    "pedicure": "페디큐어",
    "penalty": "페널티",
    "penalty kick": "페널티킥",
    "perfect game": "퍼펙트게임",
    "performance": "퍼포먼스",
    "perfume": "향수",
    "perm": "파마",
    "personal trainer": "퍼스널 트레이너",
    "pet": "펫",
    "photo": "포토",
    "photographer": "포토그래퍼",
    "photography": "포토그래피",
    "piano": "피아노",
    "picnic": "피크닉",
    "pilates": "필라테스",
    "pilot": "파일럿",
    "pinch hitter": "핀치히터",
    "ping": "핑",
    "ping pong": "탁구",
    "pitcher": "피처",
    "pixar": "픽사",
    "pixel": "픽셀",
    "playlist": "플레이리스트",
    "playoff": "플레이오프",
    "plot": "플롯",
    "podcast": "팟캐스트",
    "podium": "포디움",
    "poem": "시",
    "poet": "시인",
    "poetry": "시",
    "point guard": "포인트 가드",
    "poker": "포커",
    "pool": "풀",
    "pop": "팝",
    "pop art": "팝아트",
    "portrait": "포트레이트",
    "poster": "포스터",
    "postmodernism": "포스트모더니즘",
    "power forward": "파워 포워드",
    "premier league": "프리미어리그",
    "premiere": "프리미어",
    "prequel": "프리퀄",
    "primer": "프라이머",
    "print": "프린트",
    "prize": "프라이즈",
    "pro": "프로",
    "producer": "프로듀서",
    "professional": "프로페셔널",
    "prologue": "프롤로그",
    "prose": "산문",
    "publisher": "퍼블리셔",
    "publishing": "퍼블리싱",
    "punk": "펑크",
    "putt": "퍼트",
    "putter": "퍼터",
    "puzzle": "퍼즐",
    "pvp": "피브이피",
    "quarterfinal": "준준결승",
    "quartet": "콰르텟",
    "quest": "퀘스트",
    "r&b": "알앤비",
    "racket": "라켓",
    "rafting": "래프팅",
    "raid": "레이드",
    "rally": "랠리",
    "rank": "랭크",
    "ranked": "랭크드",
    "ranking": "랭킹",
    "rap": "랩",
    "rapper": "래퍼",
    "realism": "리얼리즘",
    "reality show": "리얼리티 쇼",
    "rebound": "리바운드",
    "receive": "리시브",
    "record": "레코드",
    "red card": "레드카드",
    "red carpet": "레드카펫",
    "referee": "레퍼리",
    "reggae": "레게",
    "rehearsal": "리허설",
    "relay": "릴레이",
    "remake": "리메이크",
    "remix": "리믹스",
    "renaissance": "르네상스",
    "render": "렌더",
    "rendering": "렌더링",
    "replay": "리플레이",
    "replica": "레플리카",
    "respawn": "리스폰",
    "retouch": "리터치",
    "retro": "레트로",
    "reverb": "리버브",
    "review": "리뷰",
    "rhythm": "리듬",
    "rock": "록",
    "rococo": "로코코",
    "romance": "로맨스",
    "romantic comedy": "로맨틱 코미디",
    "rookie": "루키",
    "roster": "로스터",
    "round": "라운드",
    "rpg": "알피지",
    "rugby": "럭비",
    "runway": "런웨이",
    "safe": "세이프",
    "salon": "살롱",
    "salsa": "살사",
    "sample": "샘플",
    "sampling": "샘플링",
    "samulnori": "사물놀이",
    "sandal": "샌들",
    "sandbox": "샌드박스",
    "santa": "산타",
    "santa claus": "산타클로스",
    "saxophone": "색소폰",
    "scale": "스케일",
    "scarf": "스카프",
    "scenario": "시나리오",
    "scene": "씬",
    "score": "스코어",
    "scoreboard": "스코어보드",
    "script": "스크립트",
    "scuba diving": "스쿠버 다이빙",
    "sculpture": "조각",
    "season": "시즌",
    "selfie": "셀피",
    "semifinal": "준결승",
    "sequel": "속편",
    "sequence": "시퀀스",
    "series": "시리즈",
    "serum": "세럼",
    "serve": "서브",
    "server": "서버",
    "service": "서비스",
    "set point": "세트 포인트",
    "setlist": "세트리스트",
    "setter": "세터",
    "shirt": "셔츠",
    "shoot": "슛",
    "shooting": "슈팅",
    "shot": "샷",
    "shutter": "셔터",
    "shutter speed": "셔터 스피드",
    "shuttlecock": "셔틀콕",
    "silhouette": "실루엣",
    "silk": "실크",
    "silver medal": "은메달",
    "simulation": "시뮬레이션",
    "singer": "싱어",
    "single": "싱글",
    "sitcom": "시트콤",
    "skateboard": "스케이트보드",
    "skating": "스케이팅",
    "sketch": "스케치",
    "ski": "스키",
    "skiing": "스키",
    "skin": "스킨",
    "skincare": "스킨케어",
    "skirt": "스커트",
    "skydiving": "스카이다이빙",
    "slam dunk": "슬램덩크",
    "slider": "슬라이더",
    "slow motion": "슬로 모션",
    "smash": "스매시",
    "snapshot": "스냅숏",
    "sneakers": "스니커즈",
    "snorkeling": "스노클링",
    "snowboard": "스노보드",
    "snowboarding": "스노보딩",
    "soccer": "축구",
    "solo": "솔로",
    "sonata": "소나타",
    "songwriter": "송라이터",
    "soprano": "소프라노",
    "soul": "소울",
    "soundtrack": "사운드트랙",
    "souvenir": "기념품",
    "sparring": "스파링",
    "speaker": "스피커",
    "speed skating": "스피드 스케이팅",
    "speedrun": "스피드런",
    "spike": "스파이크",
    "spinoff": "스핀오프",
    "spoiler": "스포일러",
    "sport": "스포츠",
    "sports": "스포츠",
    "sportsmanship": "스포츠맨십",
    "spotify": "스포티파이",
    "spotlight": "스포트라이트",
    "sprint": "스프린트",
    "squad": "스쿼드",
    "stadium": "스타디움",
    "stage": "스테이지",
    "standup comedy": "스탠드업 코미디",
    "star": "스타",
    "steal": "스틸",
    "storyboard": "스토리보드",
    "streamer": "스트리머",
    "streaming": "스트리밍",
    "street dance": "스트리트 댄스",
    "streetwear": "스트리트웨어",
    "stretching": "스트레칭",
    "strike": "스트라이크",
    "strikeout": "스트라이크 아웃",
    "striker": "스트라이커",
    "stripe": "스트라이프",
    "studio": "스튜디오",
    "stunt": "스턴트",
    "style": "스타일",
    "styling": "스타일링",
    "stylist": "스타일리스트",
    "subtitle": "자막",
    "suit": "슈트",
    "sunglasses": "선글라스",
    "sunscreen": "선스크린",
    "superhero": "슈퍼히어로",
    "surfing": "서핑",
    "surrealism": "초현실주의",
    "swimming": "수영",
    "swing": "스윙",
    "symphony": "심포니",
    "synthesizer": "신시사이저",
    "table tennis": "탁구",
    "tackle": "태클",
    "taekwondo": "태권도",
    "tailor": "테일러",
    "talk show": "토크쇼",
    "tango": "탱고",
    "tap dance": "탭댄스",
    "team": "팀",
    "teaser": "티저",
    "techno": "테크노",
    "tee": "티",
    "tempo": "템포",
    "tennis": "테니스",
    "tenor": "테너",
    "tent": "텐트",
    "texture": "텍스처",
    "thanksgiving": "추수감사절",
    "theater": "극장",
    "theatre": "극장",
    "theme": "테마",
    "three point": "쓰리 포인트",
    "thriller": "스릴러",
    "thumbnail": "썸네일",
    "ticket": "티켓",
    "tie": "타이",
    "tiebreak": "타이브레이크",
    "tiktok": "틱톡",
    "timelapse": "타임랩스",
    "timeout": "타임아웃",
    "toner": "토너",
    "toss": "토스",
    "tour": "투어",
    "tournament": "토너먼트",
    "track": "트랙",
    "trade": "트레이드",
    "trailer": "트레일러",
    "training": "트레이닝",
    "transfer": "트랜스퍼",
    "travel": "여행",
    "treadmill": "트레드밀",
    "trekking": "트레킹",
    "trend": "트렌드",
    "trendy": "트렌디",
    "triathlon": "트라이애슬론",
    "trio": "트리오",
    "tripod": "삼각대",
    "trombone": "트롬본",
    "trophy": "트로피",
    "trot": "트로트",
    "trumpet": "트럼펫",
    "tune": "튠",
    "turnover": "턴오버",
    "turntable": "턴테이블",
    "twitch": "트위치",
    "typography": "타이포그래피",
    "ukulele": "우쿨렐레",
    "umpire": "엄파이어",
    "unplugged": "언플러그드",
    "update": "업데이트",
    "uppercut": "어퍼컷",
    "valentine": "밸런타인",
    "valentine's day": "밸런타인데이",
    "variety show": "버라이어티 쇼",
    "velvet": "벨벳",
    "verse": "벌스",
    "veteran": "베테랑",
    "vfx": "브이에프엑스",
    "vibrato": "비브라토",
    "victory": "빅토리",
    "villain": "빌런",
    "vintage": "빈티지",
    "vinyl": "바이닐",
    "viola": "비올라",
    "violin": "바이올린",
    "vlog": "브이로그",
    "vocal": "보컬",
    "vocalist": "보컬리스트",
    "volley": "발리",
    "volleyball": "배구",
    "waltz": "왈츠",
    "warm up": "웜업",
    "webtoon": "웹툰",
    "wedding": "웨딩",
    "wedge": "웨지",
    "weightlifting": "역도",
    "winger": "윙어",
    "winner": "위너",
    "wool": "울",
    "workout": "워크아웃",
    "world cup": "월드컵",
    "wrestling": "레슬링",
    "writer": "라이터",
    "xylophone": "실로폰",
    "yellow card": "옐로카드",
    "yoga": "요가",
    "youtube": "유튜브",
    "youtuber": "유튜버",
    "zoom": "줌",
}

__all__ = ["CULTURE"]
