"""English phrases, interjections and Konglish compounds used inside Korean sentences."""
from __future__ import annotations

from typing import Dict

EXPRESSIONS: Dict[str, str] = {
    "absolutely": "앱솔루틀리",
    "after service": "애프터서비스",
    "air con": "에어컨",
    "air conditioner": "에어컨디셔너",
    "aircon": "에어컨",
    "all day": "올 데이",
    "all in": "올인",
    "all kill": "올킬",
    "all right": "올 라이트",
    "all star": "올스타",
    "all the best": "올 더 베스트",
    "amazing": "어메이징",
    "anytime": "애니타임",
    "anyway": "애니웨이",
    "apart": "아파트",
    "apartment": "아파트",
    "asap": "에이에스에이피",
    "asmr": "에이에스엠알",
    "awesome": "어썸",
    "back mirror": "백미러",
    "back number": "백넘버",
    "back to back": "백 투 백",
    "before and after": "비포 앤 애프터",
    "believe me": "빌리브 미",
    "best of the best": "베스트 오브 베스트",
    "best seller": "베스트셀러",
    "big deal": "빅딜",
    "black and white": "블랙 앤 화이트",
    "black list": "블랙리스트",
    "bless you": "블레스 유",
    "blind date": "블라인드 데이트",
    "boring": "보링",
    "brain storming": "브레인스토밍",
    "brand new": "브랜드 뉴",
    "bravo": "브라보",
    "brb": "비알비",
    "break time": "브레이크 타임",
    "btw": "비티더블유",
    "buy one get one": "바이 원 겟 원",
    "by the way": "바이 더 웨이",
    "bye": "바이",
    "bye bye": "바이 바이",
    "call me": "콜 미",
    "carrier": "캐리어",
    "case by case": "케이스 바이 케이스",
    "cash back": "캐시백",
    "check in": "체크인",
    "check it out": "체크 잇 아웃",
    "check out": "체크아웃",
    "cheers": "치어스",
    "cider": "사이다",
    "close up": "클로즈업",
    "come back": "컴백",
    "come here": "컴 히어",
    "come on": "컴온",
    "comeback": "컴백",
    "congrats": "콩그레츠",
    "congratulations": "콩그레츄레이션스",
    "cool": "쿨",
    "cost down": "코스트 다운",
    "cover story": "커버스토리",
    "crazy": "크레이지",
    "credit card": "크레디트 카드",
    "cross check": "크로스 체크",
    "cunning": "커닝",
    "cup ramen": "컵라면",
    "curtain call": "커튼콜",
    "cut off": "컷오프",
    "day by day": "데이 바이 데이",
    "day off": "데이 오프",
    "dead line": "데드라인",
    "definitely": "데피니틀리",
    "diy": "디아이와이",
    "dm": "디엠",
    "dm me": "디엠 미",
    "do it yourself": "두 잇 유어셀프",
    "don't worry": "돈트 워리",
    "double check": "더블 체크",
    "dream team": "드림팀",
    "dress code": "드레스 코드",
    "drive through": "드라이브 스루",
    "drive thru": "드라이브 스루",
    "drop out": "드롭아웃",
    "dutch pay": "더치페이",
    "easy": "이지",
    "enjoy": "인조이",
    "exactly": "이그잭틀리",
    "excellent": "엑설런트",
    "excuse me": "익스큐즈 미",
    "eye shopping": "아이쇼핑",
    "face to face": "페이스 투 페이스",
    "fan service": "팬서비스",
    "fantastic": "판타스틱",
    "faq": "에프에이큐",
    "fast track": "패스트트랙",
    "feed back": "피드백",
    "fighting": "파이팅",
    "first class": "퍼스트 클래스",
    "follow up": "팔로업",
    "fomo": "포모",
    "for real": "포 리얼",
    "forget it": "포겟 잇",
    "free pass": "프리패스",
    "free size": "프리 사이즈",
    "free style": "프리스타일",
    "full course": "풀코스",
    "full house": "풀하우스",
    "full time": "풀타임",
    "fyi": "에프와이아이",
    "gag man": "개그맨",
    "gag woman": "개그우먼",
    "game changer": "게임 체인저",
    "game over": "게임 오버",
    "gg": "지지",
    "give and take": "기브 앤 테이크",
    "glamour": "글래머",
    "go ahead": "고 어헤드",
    "go for it": "고 포 잇",
    "goal in": "골인",
    "good": "굿",
    "good afternoon": "굿 애프터눈",
    "good bye": "굿바이",
    "good day": "굿 데이",
    "good evening": "굿 이브닝",
    "good job": "굿 잡",
    "good luck": "굿 럭",
    "good morning": "굿 모닝",
    "good night": "굿 나이트",
    "goodbye": "굿바이",
    "great": "그레이트",
    "guest house": "게스트하우스",
    "haha": "하하",
    "hair band": "헤어밴드",
    "hair shop": "헤어숍",
    "hand cream": "핸드크림",
    "hand made": "핸드메이드",
    "hand phone": "핸드폰",
    "handle": "핸들",
    "handphone": "핸드폰",
    "hands on": "핸즈 온",
    "hands up": "핸즈 업",
    "happy birthday": "해피 버스데이",
    "happy ending": "해피엔딩",
    "happy hour": "해피 아워",
    "happy new year": "해피 뉴 이어",
    "have a good time": "해브 어 굿 타임",
    "have a nice day": "해브 어 나이스 데이",
    "head hunting": "헤드헌팅",
    "head line": "헤드라인",
    "health club": "헬스클럽",
    "hehe": "헤헤",
    "hello": "헬로",
    "here we go": "히어 위 고",
    "hey": "헤이",
    "hi": "하이",
    "high five": "하이파이브",
    "hit and run": "히트 앤 런",
    "hold on": "홀드 온",
    "home page": "홈페이지",
    "home run": "홈런",
    "home shopping": "홈쇼핑",
    "hot dog": "핫도그",
    "hot issue": "핫이슈",
    "hot line": "핫라인",
    "hot place": "핫플레이스",
    "how are you": "하우 아 유",
    "how do you do": "하우 두 유 두",
    "hurry up": "허리 업",
    "i love you": "아이 러브 유",
    "ice breaking": "아이스브레이킹",
    "ice coffee": "아이스커피",
    "ice cream": "아이스크림",
    "idk": "아이디케이",
    "imo": "아이엠오",
    "in and out": "인 앤 아웃",
    "in house": "인하우스",
    "incredible": "인크레더블",
    "indeed": "인디드",
    "jackpot": "잭팟",
    "just do it": "저스트 두 잇",
    "keep going": "킵 고잉",
    "key holder": "키홀더",
    "key point": "키포인트",
    "kick board": "킥보드",
    "kick off": "킥오프",
    "klaxon": "클랙슨",
    "know how": "노하우",
    "last minute": "라스트 미닛",
    "lay off": "레이오프",
    "lemon tea": "레몬티",
    "let's do it": "렛츠 두 잇",
    "let's go": "렛츠 고",
    "level up": "레벨업",
    "life style": "라이프스타일",
    "log in": "로그인",
    "log out": "로그아웃",
    "lol": "엘오엘",
    "long term": "롱 텀",
    "long time no see": "롱 타임 노 시",
    "love story": "러브 스토리",
    "lucky": "럭키",
    "make up": "메이크업",
    "manicure": "매니큐어",
    "mass com": "매스컴",
    "master piece": "마스터피스",
    "me too": "미 투",
    "meeting": "미팅",
    "mental": "멘탈",
    "merry christmas": "메리 크리스마스",
    "morning call": "모닝콜",
    "must have": "머스트 해브",
    "must see": "머스트 시",
    "mvp": "엠브이피",
    "my pleasure": "마이 플레저",
    "name value": "네임 밸류",
    "never mind": "네버 마인드",
    "next level": "넥스트 레벨",
    "nice": "나이스",
    "nice to meet you": "나이스 투 미트 유",
    "no comment": "노 코멘트",
    "no more": "노 모어",
    "no problem": "노 프로블럼",
    "no smoking": "노 스모킹",
    "no thanks": "노 땡스",
    "no touch": "노터치",
    "no way": "노 웨이",
    "non stop": "논스톱",
    "nope": "놉",
    "not bad": "낫 배드",
    "note book": "노트북",
    "notebook": "노트북",
    "number one": "넘버원",
    "of course": "오브 코스",
    "off the record": "오프 더 레코드",
    "officetel": "오피스텔",
    "oh": "오",
    "oh my god": "오 마이 갓",
    "oh no": "오 노",
    "okay": "오케이",
    "old school": "올드 스쿨",
    "omg": "오엠지",
    "on air": "온에어",
    "on and off": "온 앤 오프",
    "on time": "온 타임",
    "one and only": "원 앤 온리",
    "one by one": "원 바이 원",
    "one day": "원데이",
    "one more": "원 모어",
    "one more time": "원 모어 타임",
    "one on one": "원 온 원",
    "one piece": "원피스",
    "one plus one": "원 플러스 원",
    "one room": "원룸",
    "one shot": "원샷",
    "one stop": "원스톱",
    "oops": "웁스",
    "ootd": "오오티디",
    "open car": "오픈카",
    "open mind": "오픈 마인드",
    "ost": "오에스티",
    "over": "오버",
    "over time": "오버타임",
    "package tour": "패키지 투어",
    "panty stocking": "팬티스타킹",
    "part time": "파트타임",
    "pay back": "페이백",
    "perfect": "퍼펙트",
    "photo shop": "포토샵",
    "pick up": "픽업",
    "pierce": "피어스",
    "play list": "플레이리스트",
    "please": "플리즈",
    "pls": "플리즈",
    "plz": "플리즈",
    "pocket ball": "포켓볼",
    "pocket money": "포켓 머니",
    "pop corn": "팝콘",
    "pop song": "팝송",
    "power point": "파워포인트",
    "power up": "파워업",
    "ppl": "피피엘",
    "press release": "프레스 릴리스",
    "prime time": "프라임 타임",
    "pros and cons": "프로스 앤 콘스",
    "quick service": "퀵서비스",
    "ready go": "레디 고",
    "ready made": "레디메이드",
    "real time": "리얼타임",
    "really": "리얼리",
    "remote con": "리모컨",
    "rent car": "렌트카",
    "right now": "라이트 나우",
    "rip": "알아이피",
    "rock and roll": "로큰롤",
    "role model": "롤 모델",
    "roll cake": "롤케이크",
    "room service": "룸서비스",
    "running machine": "러닝머신",
    "sale": "세일",
    "sand bag": "샌드백",
    "scale up": "스케일업",
    "sea food": "시푸드",
    "second hand": "세컨드 핸드",
    "see you": "시 유",
    "see you again": "시 유 어게인",
    "see you later": "시 유 레이터",
    "see you soon": "시 유 순",
    "selca": "셀카",
    "self camera": "셀프 카메라",
    "self service": "셀프서비스",
    "seriously": "시리어슬리",
    "service": "서비스",
    "set up": "셋업",
    "sharp pencil": "샤프펜슬",
    "shocking": "쇼킹",
    "shopping mall": "쇼핑몰",
    "short cut": "숏컷",
    "show case": "쇼케이스",
    "show time": "쇼타임",
    "side by side": "사이드 바이 사이드",
    "sign pen": "사인펜",
    "sign up": "사인업",
    "silver town": "실버타운",
    "skinship": "스킨십",
    "smart phone": "스마트폰",
    "so so": "쏘쏘",
    "so what": "소 왓",
    "social media": "소셜 미디어",
    "sold out": "솔드 아웃",
    "sorry": "쏘리",
    "soul mate": "소울메이트",
    "sound track": "사운드트랙",
    "sounds good": "사운즈 굿",
    "spec": "스펙",
    "spin off": "스핀오프",
    "spot light": "스포트라이트",
    "stainless": "스테인리스",
    "stand by": "스탠바이",
    "stand up": "스탠드업",
    "start up": "스타트업",
    "step by step": "스텝 바이 스텝",
    "sun cream": "선크림",
    "super": "슈퍼",
    "sure": "슈어",
    "surprise": "서프라이즈",
    "table manner": "테이블 매너",
    "take care": "테이크 케어",
    "take off": "테이크오프",
    "take out": "테이크아웃",
    "talent": "탤런트",
    "talk show": "토크쇼",
    "tbh": "티비에이치",
    "tea time": "티타임",
    "team work": "팀워크",
    "terrible": "테러블",
    "test drive": "테스트 드라이브",
    "thank god": "땡 갓",
    "thank you": "땡큐",
    "thank you very much": "땡큐 베리 머치",
    "thanks": "땡스",
    "thanks a lot": "땡스 어 랏",
    "the best": "더 베스트",
    "the end": "디 엔드",
    "thumbs up": "섬즈 업",
    "thx": "땡스",
    "time out": "타임아웃",
    "tmi": "티엠아이",
    "to go": "투 고",
    "top class": "톱클래스",
    "top down": "톱다운",
    "top secret": "톱 시크릿",
    "trade off": "트레이드오프",
    "trial and error": "트라이얼 앤 에러",
    "trot": "트로트",
    "trust me": "트러스트 미",
    "ttyl": "티티와이엘",
    "turn over": "턴오버",
    "turning point": "터닝 포인트",
    "two way": "투웨이",
    "unbelievable": "언빌리버블",
    "under ground": "언더그라운드",
    "up and down": "업 앤 다운",
    "up grade": "업그레이드",
    "up to date": "업 투 데이트",
    "very good": "베리 굿",
    "very nice": "베리 나이스",
    "villa": "빌라",
    "vinyl": "비닐",
    "vinyl house": "비닐하우스",
    "vip": "브이아이피",
    "wait": "웨이트",
    "wake up": "웨이크업",
    "wanna be": "워너비",
    "warm up": "웜업",
    "water park": "워터파크",
    "webtoon": "웹툰",
    "week end": "위크엔드",
    "welcome": "웰컴",
    "welcome back": "웰컴 백",
    "well done": "웰던",
    "what's up": "왓츠 업",
    "whatever": "왓에버",
    "why not": "와이 낫",
    "wifi": "와이파이",
    "win win": "윈윈",
    "wine glass": "와인 글라스",
    "wish list": "위시 리스트",
    "wonderful": "원더풀",
    "work life balance": "워크 라이프 밸런스",
    "work out": "워크아웃",
    "work shop": "워크숍",
    "world class": "월드 클래스",
    "world cup": "월드컵",
    "wow": "와우",
    "y shirt": "와이셔츠",
    "yay": "예이",
    "yeah": "예",
    "yep": "옙",
    "yes": "예스",
    "yes or no": "예스 오어 노",
    "yolo": "욜로",
    "you know": "유 노",
    "you too": "유 투",
    "you're welcome": "유어 웰컴",
    "yummy": "야미",
}

__all__ = ["EXPRESSIONS"]
