"""Medical, health, and fitness vocabulary appearing in Korean text."""
from __future__ import annotations

from typing import Dict

MEDICINE: Dict[str, str] = {
    "abortion": "낙태",
    "acetaminophen": "아세트아미노펜",
    "achilles tendon": "아킬레스건",
    "acid reflux": "역류성 식도염",
    "acne": "여드름",
    "acupuncture": "침",
    "acute": "급성",
    "adhd": "에이디에이치디",
    "adrenaline": "아드레날린",
    "aids": "에이즈",
    "alcoholism": "알코올 중독",
    "allergen": "알레르겐",
    "allergy": "알레르기",
    "alzheimer": "알츠하이머",
    "ambulance": "구급차",
    "amino acid": "아미노산",
    "analgesic": "진통제",
    "anaphylaxis": "아나필락시스",
    "anemia": "빈혈",
    "anesthesia": "마취",
    "anesthesiologist": "마취과 의사",
    "aneurysm": "동맥류",
    "angina": "협심증",
    "anorexia": "거식증",
    "antacid": "제산제",
    "antibiotic": "항생제",
    "antibody": "항체",
    "antidepressant": "항우울제",
    "antigen": "항원",
    "antihistamine": "항히스타민제",
    "antioxidant": "항산화제",
    "antiseptic": "소독약",
    "antiviral": "항바이러스제",
    "anxiety": "불안",
    "anxiety disorder": "불안장애",
    "aorta": "대동맥",
    "appendicitis": "맹장염",
    "appetite": "식욕",
    "arrhythmia": "부정맥",
    "artery": "동맥",
    "arthritis": "관절염",
    "aspirin": "아스피린",
    "asthma": "천식",
    "astigmatism": "난시",
    "atherosclerosis": "동맥경화",
    "atopy": "아토피",
    "autism": "자폐증",
    "bandage": "붕대",
    "barbell": "바벨",
    "bench press": "벤치 프레스",
    "biceps": "이두근",
    "biopsy": "조직검사",
    "bipolar disorder": "양극성 장애",
    "birth rate": "출산율",
    "bladder": "방광",
    "blood clot": "혈전",
    "blood donation": "헌혈",
    "blood pressure": "혈압",
    "blood sugar": "혈당",
    "blood test": "혈액검사",
    "blood type": "혈액형",
    "blood vessel": "혈관",
    "bmi": "비엠아이",
    "body fat": "체지방",
    "body temperature": "체온",
    "bodybuilding": "보디빌딩",
    "bone": "뼈",
    "bone marrow": "골수",
    "booster shot": "부스터 샷",
    "botox": "보톡스",
    "brain tumor": "뇌종양",
    "breast cancer": "유방암",
    "breastfeeding": "모유 수유",
    "bronchitis": "기관지염",
    "bronchus": "기관지",
    "bruise": "멍",
    "bulimia": "폭식증",
    "burnout": "번아웃",
    "burpee": "버피",
    "caffeine": "카페인",
    "calcium": "칼슘",
    "calorie": "칼로리",
    "capillary": "모세혈관",
    "capsule": "캡슐",
    "carbohydrate": "탄수화물",
    "cardio": "유산소 운동",
    "cardiology": "심장내과",
    "cartilage": "연골",
    "cataract": "백내장",
    "catheter": "카테터",
    "cavity": "충치",
    "cdc": "씨디씨",
    "cerebellum": "소뇌",
    "cerebral palsy": "뇌성마비",
    "cervical cancer": "자궁경부암",
    "cesarean section": "제왕절개",
    "chemotherapy": "항암 치료",
    "chest pain": "흉통",
    "chickenpox": "수두",
    "childbirth": "출산",
    "chills": "오한",
    "chiropractic": "카이로프랙틱",
    "cholesterol": "콜레스테롤",
    "chronic": "만성",
    "cirrhosis": "간경화",
    "clinic": "클리닉",
    "clinical trial": "임상시험",
    "collagen": "콜라겐",
    "colon cancer": "대장암",
    "concussion": "뇌진탕",
    "constipation": "변비",
    "copd": "씨오피디",
    "cornea": "각막",
    "cortisol": "코르티솔",
    "cough syrup": "기침약",
    "counseling": "상담",
    "counselor": "상담사",
    "covid": "코로나",
    "covid-19": "코로나 일구",
    "cpr": "씨피알",
    "creatine": "크레아틴",
    "crohn's disease": "크론병",
    "crutch": "목발",
    "ct": "씨티",
    "ct scan": "씨티 촬영",
    "dandruff": "비듬",
    "deadlift": "데드리프트",
    "defibrillator": "제세동기",
    "dehydration": "탈수",
    "deltoid": "삼각근",
    "dementia": "치매",
    "dental": "치과",
    "dentist": "치과의사",
    "depression": "우울증",
    "dermatitis": "피부염",
    "dermatology": "피부과",
    "detox": "디톡스",
    "diabetes": "당뇨병",
    "dialysis": "투석",
    "diaphragm": "횡격막",
    "diarrhea": "설사",
    "dietitian": "영양사",
    "digestion": "소화",
    "disinfectant": "소독제",
    "disinfection": "소독",
    "dizziness": "어지럼증",
    "dna": "디엔에이",
    "dopamine": "도파민",
    "dosage": "복용량",
    "down syndrome": "다운 증후군",
    "dumbbell": "덤벨",
    "dust mite": "집먼지진드기",
    "eardrum": "고막",
    "eczema": "습진",
    "electrolyte": "전해질",
    "emergency medicine": "응급의학과",
    "emergency room": "응급실",
    "endorphin": "엔도르핀",
    "endoscopy": "내시경",
    "endurance": "지구력",
    "enzyme": "효소",
    "epidemic": "전염병",
    "epidemiologist": "역학조사관",
    "epidemiology": "역학",
    "epilepsy": "뇌전증",
    "esophagus": "식도",
    "estrogen": "에스트로겐",
    "eye drop": "안약",
    "fainting": "실신",
    "family medicine": "가정의학과",
    "fasting": "단식",
    "fatality rate": "치명률",
    "fatigue": "피로",
    "fatty liver": "지방간",
    "fda": "에프디에이",
    "fiber": "식이섬유",
    "fibromyalgia": "섬유근육통",
    "first aid": "응급처치",
    "fitness": "피트니스",
    "flexibility": "유연성",
    "flu": "독감",
    "foam roller": "폼롤러",
    "folic acid": "엽산",
    "food poisoning": "식중독",
    "fracture": "골절",
    "frozen shoulder": "오십견",
    "fructose": "과당",
    "gallbladder": "담낭",
    "gallstone": "담석",
    "gastritis": "위염",
    "gauze": "거즈",
    "ginseng": "인삼",
    "glaucoma": "녹내장",
    "glucose": "포도당",
    "gluten": "글루텐",
    "glutes": "둔근",
    "gout": "통풍",
    "gum disease": "잇몸병",
    "hair loss": "탈모",
    "hamstring": "햄스트링",
    "hangover": "숙취",
    "headache": "두통",
    "health insurance": "건강보험",
    "healthcare": "의료",
    "hearing aid": "보청기",
    "heart attack": "심장마비",
    "heart failure": "심부전",
    "heart rate": "심박수",
    "heartburn": "속쓰림",
    "hemoglobin": "헤모글로빈",
    "hemorrhoid": "치질",
    "hepatitis": "간염",
    "herbal medicine": "한약",
    "herd immunity": "집단면역",
    "hernia": "탈장",
    "herniated disc": "허리 디스크",
    "high blood pressure": "고혈압",
    "hiv": "에이치아이브이",
    "hormone": "호르몬",
    "hospice": "호스피스",
    "hygiene": "위생",
    "hypertension": "고혈압",
    "hypothalamus": "시상하부",
    "hypothermia": "저체온증",
    "ibuprofen": "이부프로펜",
    "icu": "아이씨유",
    "immune system": "면역 체계",
    "immunity": "면역",
    "immunization": "예방접종",
    "immunotherapy": "면역치료",
    "implant": "임플란트",
    "incubation period": "잠복기",
    "indigestion": "소화불량",
    "infection rate": "감염률",
    "infertility": "난임",
    "influenza": "인플루엔자",
    "inhaler": "흡입기",
    "inpatient": "입원 환자",
    "insomnia": "불면증",
    "insulin": "인슐린",
    "intensive care": "중환자실",
    "intermittent fasting": "간헐적 단식",
    "internal medicine": "내과",
    "interval training": "인터벌 트레이닝",
    "intestine": "장",
    "irritable bowel syndrome": "과민성 대장 증후군",
    "itching": "가려움",
    "ketogenic diet": "케토제닉 다이어트",
    "kettlebell": "케틀벨",
    "kidney": "신장",
    "kidney failure": "신부전",
    "kidney stone": "신장결석",
    "lactose": "유당",
    "lactose intolerance": "유당불내증",
    "laparoscopy": "복강경 수술",
    "larynx": "후두",
    "laser surgery": "레이저 수술",
    "laxative": "변비약",
    "leukemia": "백혈병",
    "life expectancy": "기대수명",
    "ligament": "인대",
    "liposuction": "지방흡입",
    "liver": "간",
    "liver cancer": "간암",
    "lung": "폐",
    "lung cancer": "폐암",
    "lunge": "런지",
    "lupus": "루푸스",
    "lymph": "림프",
    "lymph node": "림프절",
    "lymphoma": "림프종",
    "magnesium": "마그네슘",
    "malaria": "말라리아",
    "malnutrition": "영양실조",
    "marathon": "마라톤",
    "medical school": "의대",
    "meditation": "명상",
    "melanoma": "흑색종",
    "melatonin": "멜라토닌",
    "meningitis": "뇌수막염",
    "menopause": "폐경",
    "menstruation": "생리",
    "mental health": "정신건강",
    "mers": "메르스",
    "metabolism": "신진대사",
    "metastasis": "전이",
    "migraine": "편두통",
    "mindfulness": "마음챙김",
    "minoxidil": "미녹시딜",
    "miscarriage": "유산",
    "moisturizer": "보습제",
    "mortality rate": "사망률",
    "mri": "엠알아이",
    "mrna": "엠알엔에이",
    "multiple sclerosis": "다발성 경화증",
    "multivitamin": "종합비타민",
    "muscle": "근육",
    "muscle mass": "근육량",
    "muscle pain": "근육통",
    "mutation": "변이",
    "myocardial infarction": "심근경색",
    "myopia": "근시",
    "nausea": "메스꺼움",
    "nerve": "신경",
    "neurology": "신경과",
    "neuron": "뉴런",
    "neurosurgery": "신경외과",
    "newborn": "신생아",
    "nicotine": "니코틴",
    "numbness": "저림",
    "nutrition": "영양",
    "nutritionist": "영양사",
    "obesity": "비만",
    "obstetrics": "산부인과",
    "ocd": "오씨디",
    "ointment": "연고",
    "omega three": "오메가 쓰리",
    "omega-3": "오메가 쓰리",
    "oncology": "종양내과",
    "operating room": "수술실",
    "ophthalmology": "안과",
    "organ donation": "장기기증",
    "oriental medicine": "한의학",
    "orthopedics": "정형외과",
    "osteoarthritis": "퇴행성 관절염",
    "osteoporosis": "골다공증",
    "outbreak": "발병",
    "outpatient": "외래",
    "ovary": "난소",
    "overdose": "과다복용",
    "overweight": "과체중",
    "ovulation": "배란",
    "oxygen saturation": "산소포화도",
    "oxytocin": "옥시토신",
    "painkiller": "진통제",
    "pancreas": "췌장",
    "pancreatic cancer": "췌장암",
    "pandemic": "팬데믹",
    "panic attack": "공황 발작",
    "panic disorder": "공황장애",
    "paramedic": "응급구조사",
    "parkinson": "파킨슨",
    "pathology": "병리학",
    "pcr": "피씨알",
    "pediatrician": "소아과 의사",
    "pediatrics": "소아과",
    "penicillin": "페니실린",
    "personal trainer": "퍼스널 트레이너",
    "personal training": "퍼스널 트레이닝",
    "pharmacist": "약사",
    "pharmacy": "약국",
    "phobia": "공포증",
    "physical therapy": "물리치료",
    "pilates": "필라테스",
    "pill": "알약",
    "placebo": "플라시보",
    "placebo effect": "플라시보 효과",
    "plank": "플랭크",
    "plantar fasciitis": "족저근막염",
    "plastic surgery": "성형외과",
    "platelet": "혈소판",
    "pneumonia": "폐렴",
    "pollen": "꽃가루",
    "potassium": "칼륨",
    "powerlifting": "파워리프팅",
    "prebiotics": "프리바이오틱스",
    "pregnancy": "임신",
    "premature birth": "조산",
    "presbyopia": "노안",
    "probiotics": "프로바이오틱스",
    "prognosis": "예후",
    "prostate": "전립선",
    "prostate cancer": "전립선암",
    "protein": "단백질",
    "protein shake": "프로틴 셰이크",
    "psoriasis": "건선",
    "psychiatrist": "정신과 의사",
    "psychiatry": "정신과",
    "psychologist": "심리학자",
    "psychotherapy": "심리치료",
    "ptsd": "피티에스디",
    "public health": "공중보건",
    "pull-up": "턱걸이",
    "push-up": "팔굽혀펴기",
    "quadriceps": "대퇴사두근",
    "quarantine": "격리",
    "radiation therapy": "방사선 치료",
    "radiology": "영상의학과",
    "rash": "발진",
    "rectum": "직장",
    "red blood cell": "적혈구",
    "rehabilitation": "재활",
    "relapse": "재발",
    "retina": "망막",
    "rheumatoid arthritis": "류마티스 관절염",
    "rhinitis": "비염",
    "rna": "알엔에이",
    "root canal": "신경치료",
    "runny nose": "콧물",
    "sanitizer": "손소독제",
    "sars": "사스",
    "saturated fat": "포화지방",
    "scar": "흉터",
    "schizophrenia": "조현병",
    "sciatica": "좌골신경통",
    "scoliosis": "척추측만증",
    "seizure": "발작",
    "self-esteem": "자존감",
    "sepsis": "패혈증",
    "serotonin": "세로토닌",
    "shortness of breath": "호흡곤란",
    "side effect": "부작용",
    "sinusitis": "축농증",
    "sit-up": "윗몸일으키기",
    "six pack": "식스팩",
    "skin cancer": "피부암",
    "sleep apnea": "수면무호흡증",
    "smoking cessation": "금연",
    "snoring": "코골이",
    "social distancing": "사회적 거리두기",
    "sodium": "나트륨",
    "sore throat": "인후통",
    "spinal cord": "척수",
    "spine": "척추",
    "spleen": "비장",
    "sprain": "염좌",
    "squat": "스쿼트",
    "stem cell": "줄기세포",
    "stent": "스텐트",
    "steroid": "스테로이드",
    "stethoscope": "청진기",
    "stomach": "위",
    "stomach cancer": "위암",
    "strength training": "근력 운동",
    "stretching": "스트레칭",
    "suicide": "자살",
    "sunscreen": "선크림",
    "supplement": "영양제",
    "surgeon": "외과 의사",
    "suture": "봉합",
    "swab": "면봉",
    "swelling": "부종",
    "syringe": "주사기",
    "telemedicine": "원격진료",
    "tendon": "힘줄",
    "tennis elbow": "테니스 엘보",
    "testosterone": "테스토스테론",
    "thermometer": "체온계",
    "thrombosis": "혈전증",
    "thyroid": "갑상선",
    "thyroid cancer": "갑상선암",
    "tinnitus": "이명",
    "tonsil": "편도선",
    "tooth": "치아",
    "toothache": "치통",
    "trainer": "트레이너",
    "trans fat": "트랜스지방",
    "transfusion": "수혈",
    "transplant": "이식",
    "treadmill": "러닝머신",
    "triceps": "삼두근",
    "triglyceride": "중성지방",
    "tuberculosis": "결핵",
    "tylenol": "타이레놀",
    "ulcer": "궤양",
    "ultrasound": "초음파",
    "underweight": "저체중",
    "unsaturated fat": "불포화지방",
    "urine test": "소변검사",
    "urology": "비뇨기과",
    "uterus": "자궁",
    "vaccination": "예방접종",
    "vaccine": "백신",
    "varicose vein": "하지정맥류",
    "vegan": "비건",
    "vegetarian": "채식주의자",
    "vein": "정맥",
    "ventilator": "인공호흡기",
    "vertigo": "현기증",
    "veterinarian": "수의사",
    "vitamin": "비타민",
    "vitamin a": "비타민 에이",
    "vitamin c": "비타민 씨",
    "vitamin d": "비타민 디",
    "vomiting": "구토",
    "warm-up": "준비운동",
    "weight gain": "체중 증가",
    "weight loss": "체중 감량",
    "weight training": "웨이트 트레이닝",
    "wellness": "웰니스",
    "wheelchair": "휠체어",
    "whey protein": "웨이 프로틴",
    "white blood cell": "백혈구",
    "whitening": "미백",
    "wisdom tooth": "사랑니",
    "withdrawal symptom": "금단 증상",
    "wound": "상처",
    "x-ray": "엑스레이",
    "yoga": "요가",
    "zinc": "아연",
}

__all__ = ["MEDICINE"]
