"""Personal names, famous figures, and fictional characters as Koreans read them."""
from __future__ import annotations

from typing import Dict

PEOPLE: Dict[str, str] = {
    "aaron": "애런",
    "abigail": "애비게일",
    "abraham lincoln": "에이브러햄 링컨",
    "achilles": "아킬레우스",
    "adam": "애덤",
    "adam smith": "애덤 스미스",
    "adele": "아델",
    "adrian": "에이드리언",
    "akira kurosawa": "구로사와 아키라",
    "aladdin": "알라딘",
    "alan": "앨런",
    "albert": "앨버트",
    "albert einstein": "알베르트 아인슈타인",
    "alessandro": "알레산드로",
    "alex": "알렉스",
    "alexander": "알렉산더",
    "alexander graham bell": "알렉산더 그레이엄 벨",
    "alexander the great": "알렉산더 대왕",
    "alfred": "앨프리드",
    "alfred hitchcock": "앨프리드 히치콕",
    "alice": "앨리스",
    "alice in wonderland": "이상한 나라의 앨리스",
    "altman": "올트먼",
    "amanda": "어맨다",
    "amelia": "아멜리아",
    "amundsen": "아문센",
    "amy": "에이미",
    "anastasia": "아나스타샤",
    "anderson": "앤더슨",
    "andre": "앙드레",
    "andrea": "안드레아",
    "andrew": "앤드루",
    "andy warhol": "앤디 워홀",
    "angela": "앤절라",
    "angela merkel": "앙겔라 메르켈",
    "angelina jolie": "앤젤리나 졸리",
    "anna": "안나",
    "anne": "앤",
    "anthony": "앤서니",
    "antonio": "안토니오",
    "aphrodite": "아프로디테",
    "apollo": "아폴로",
    "aragorn": "아라고른",
    "archimedes": "아르키메데스",
    "ares": "아레스",
    "aristotle": "아리스토텔레스",
    "artemis": "아르테미스",
    "arthur": "아서",
    "athena": "아테나",
    "audrey": "오드리",
    "augustus": "아우구스투스",
    "austen": "오스틴",
    "bach": "바흐",
    "baker": "베이커",
    "barack obama": "버락 오바마",
    "barbara": "바버라",
    "barbie": "바비",
    "bart simpson": "바트 심슨",
    "batman": "배트맨",
    "bauer": "바우어",
    "becker": "베커",
    "beckham": "베컴",
    "beethoven": "베토벤",
    "bell": "벨",
    "bella": "벨라",
    "benjamin": "벤저민",
    "benjamin franklin": "벤저민 프랭클린",
    "bennett": "베넷",
    "bernard": "버나드",
    "betty": "베티",
    "beyonce": "비욘세",
    "bezos": "베이조스",
    "bianchi": "비앙키",
    "biden": "바이든",
    "bieber": "비버",
    "bill": "빌",
    "bill clinton": "빌 클린턴",
    "bill gates": "빌 게이츠",
    "bismarck": "비스마르크",
    "bob dylan": "밥 딜런",
    "bohr": "보어",
    "borges": "보르헤스",
    "boris": "보리스",
    "bowie": "보위",
    "brad pitt": "브래드 피트",
    "brahms": "브람스",
    "braun": "브라운",
    "brian": "브라이언",
    "brown": "브라운",
    "bruce": "브루스",
    "bruno mars": "브루노 마스",
    "buddha": "부처",
    "buffett": "버핏",
    "buzz lightyear": "버즈 라이트이어",
    "caesar": "카이사르",
    "campbell": "캠벨",
    "captain america": "캡틴 아메리카",
    "captain hook": "후크 선장",
    "carl": "칼",
    "carlos": "카를로스",
    "carmen": "카르멘",
    "carol": "캐럴",
    "caroline": "캐럴라인",
    "carter": "카터",
    "catherine": "캐서린",
    "cervantes": "세르반테스",
    "cezanne": "세잔",
    "chaplin": "채플린",
    "charles": "찰스",
    "charles darwin": "찰스 다윈",
    "charles de gaulle": "샤를 드골",
    "charlie": "찰리",
    "charlie brown": "찰리 브라운",
    "charlie chaplin": "찰리 채플린",
    "charlotte": "샬럿",
    "che guevara": "체 게바라",
    "chekhov": "체호프",
    "chen": "천",
    "chloe": "클로이",
    "chopin": "쇼팽",
    "chris": "크리스",
    "christina": "크리스티나",
    "christine": "크리스틴",
    "christopher": "크리스토퍼",
    "christopher nolan": "크리스토퍼 놀런",
    "churchill": "처칠",
    "cinderella": "신데렐라",
    "claire": "클레어",
    "clara": "클라라",
    "clark": "클라크",
    "cleopatra": "클레오파트라",
    "clinton": "클린턴",
    "collins": "콜린스",
    "columbus": "콜럼버스",
    "confucius": "공자",
    "cook": "쿡",
    "cooper": "쿠퍼",
    "copernicus": "코페르니쿠스",
    "cristiano ronaldo": "크리스티아누 호날두",
    "cruz": "크루스",
    "curie": "퀴리",
    "da vinci": "다빈치",
    "daisy": "데이지",
    "dali": "달리",
    "daniel": "대니얼",
    "dante": "단테",
    "darth vader": "다스 베이더",
    "darwin": "다윈",
    "david": "데이비드",
    "david beckham": "데이비드 베컴",
    "david bowie": "데이비드 보위",
    "davis": "데이비스",
    "de gaulle": "드골",
    "dennis": "데니스",
    "descartes": "데카르트",
    "diana": "다이애나",
    "dicaprio": "디카프리오",
    "dickens": "디킨스",
    "diego": "디에고",
    "djokovic": "조코비치",
    "dmitri": "드미트리",
    "don quixote": "돈키호테",
    "donald": "도널드",
    "donald duck": "도널드 덕",
    "donald trump": "도널드 트럼프",
    "doraemon": "도라에몽",
    "dorothy": "도러시",
    "dostoevsky": "도스토옙스키",
    "douglas": "더글러스",
    "dracula": "드라큘라",
    "dubois": "뒤부아",
    "dumbledore": "덤블도어",
    "durand": "뒤랑",
    "ed sheeran": "에드 시런",
    "edgar allan poe": "에드거 앨런 포",
    "edison": "에디슨",
    "edward": "에드워드",
    "edwards": "에드워즈",
    "edwin": "에드윈",
    "einstein": "아인슈타인",
    "eisenhower": "아이젠하워",
    "elena": "엘레나",
    "elizabeth": "엘리자베스",
    "ella": "엘라",
    "ellen": "엘런",
    "elon musk": "일론 머스크",
    "elsa": "엘사",
    "elvis presley": "엘비스 프레슬리",
    "emily": "에밀리",
    "emma": "에마",
    "emma watson": "에마 왓슨",
    "eric": "에릭",
    "erik": "에릭",
    "ernest": "어니스트",
    "euclid": "유클리드",
    "eugene": "유진",
    "euler": "오일러",
    "eva": "에바",
    "evans": "에번스",
    "evelyn": "에벌린",
    "faraday": "패러데이",
    "federer": "페더러",
    "felix": "펠릭스",
    "fermi": "페르미",
    "fernandez": "페르난데스",
    "ferrari": "페라리",
    "feynman": "파인먼",
    "fibonacci": "피보나치",
    "fidel castro": "피델 카스트로",
    "fiona": "피오나",
    "fischer": "피셔",
    "florence nightingale": "플로렌스 나이팅게일",
    "ford": "포드",
    "foster": "포스터",
    "francis": "프랜시스",
    "francisco": "프란시스코",
    "frank": "프랭크",
    "frankenstein": "프랑켄슈타인",
    "franklin": "프랭클린",
    "fred": "프레드",
    "freddie mercury": "프레디 머큐리",
    "frederick": "프레더릭",
    "freud": "프로이트",
    "fritz": "프리츠",
    "frodo": "프로도",
    "gabriel": "가브리엘",
    "gabriela": "가브리엘라",
    "galileo": "갈릴레오",
    "gandalf": "간달프",
    "gandhi": "간디",
    "garcia": "가르시아",
    "garfield": "가필드",
    "gauss": "가우스",
    "genghis khan": "칭기즈 칸",
    "george": "조지",
    "george orwell": "조지 오웰",
    "george washington": "조지 워싱턴",
    "gerald": "제럴드",
    "giovanni": "조반니",
    "giuseppe": "주세페",
    "godzilla": "고질라",
    "goethe": "괴테",
    "gogh": "고흐",
    "gogol": "고골",
    "gollum": "골룸",
    "gonzalez": "곤살레스",
    "gorbachev": "고르바초프",
    "gordon": "고든",
    "goya": "고야",
    "grace": "그레이스",
    "gray": "그레이",
    "green": "그린",
    "gregory": "그레고리",
    "guevara": "게바라",
    "gutenberg": "구텐베르크",
    "hades": "하데스",
    "hall": "홀",
    "hamlet": "햄릿",
    "handel": "헨델",
    "hannah": "해나",
    "hans": "한스",
    "harold": "해럴드",
    "harris": "해리스",
    "harry": "해리",
    "harry potter": "해리 포터",
    "hartmann": "하르트만",
    "haruki murakami": "무라카미 하루키",
    "hawking": "호킹",
    "hayao miyazaki": "미야자키 하야오",
    "hegel": "헤겔",
    "heisenberg": "하이젠베르크",
    "helen": "헬렌",
    "helen keller": "헬렌 켈러",
    "helena": "헬레나",
    "hello kitty": "헬로 키티",
    "helmut": "헬무트",
    "hemingway": "헤밍웨이",
    "henri": "앙리",
    "henrik": "헨리크",
    "henry": "헨리",
    "henry ford": "헨리 포드",
    "herbert": "허버트",
    "hercules": "헤라클레스",
    "hermione": "헤르미온느",
    "hernandez": "에르난데스",
    "herodotus": "헤로도토스",
    "hill": "힐",
    "hippocrates": "히포크라테스",
    "hitchcock": "히치콕",
    "hitler": "히틀러",
    "hoffmann": "호프만",
    "holmes": "홈스",
    "homer": "호메로스",
    "homer simpson": "호머 심슨",
    "howard": "하워드",
    "huang": "황",
    "hughes": "휴스",
    "hulk": "헐크",
    "hume": "흄",
    "icarus": "이카로스",
    "indiana jones": "인디아나 존스",
    "irene": "아이린",
    "iron man": "아이언맨",
    "isaac newton": "아이작 뉴턴",
    "isabella": "이사벨라",
    "ivan": "이반",
    "ivanov": "이바노프",
    "jack": "잭",
    "jackson": "잭슨",
    "jacob": "제이컵",
    "james": "제임스",
    "james bond": "제임스 본드",
    "jane": "제인",
    "jane austen": "제인 오스틴",
    "janet": "재닛",
    "jasmine": "재스민",
    "jason": "제이슨",
    "javier": "하비에르",
    "jean": "장",
    "jeff": "제프",
    "jeff bezos": "제프 베이조스",
    "jeffrey": "제프리",
    "jenkins": "젠킨스",
    "jennifer": "제니퍼",
    "jensen huang": "젠슨 황",
    "jeremy": "제러미",
    "jerry": "제리",
    "jesse": "제시",
    "jessica": "제시카",
    "jesus": "예수",
    "jimmy": "지미",
    "jimmy carter": "지미 카터",
    "joan": "조앤",
    "joan of arc": "잔 다르크",
    "joel": "조엘",
    "johan": "요한",
    "johann": "요한",
    "john": "존",
    "john f. kennedy": "존 에프 케네디",
    "johnny": "조니",
    "johnny depp": "조니 뎁",
    "johnson": "존슨",
    "joker": "조커",
    "jonathan": "조너선",
    "jones": "존스",
    "jorge": "호르헤",
    "jose": "호세",
    "joseph": "조지프",
    "josephine": "조지핀",
    "joshua": "조슈아",
    "juan": "후안",
    "judith": "주디스",
    "judy": "주디",
    "julia": "줄리아",
    "julian": "줄리언",
    "julie": "줄리",
    "juliet": "줄리엣",
    "julius caesar": "율리우스 카이사르",
    "justin": "저스틴",
    "kafka": "카프카",
    "kant": "칸트",
    "karen": "캐런",
    "karl": "카를",
    "karl marx": "카를 마르크스",
    "kate": "케이트",
    "katherine": "캐서린",
    "kathleen": "캐슬린",
    "katie": "케이티",
    "keanu reeves": "키아누 리브스",
    "keith": "키스",
    "keller": "켈러",
    "kelly": "켈리",
    "kennedy": "케네디",
    "kenneth": "케네스",
    "kepler": "케플러",
    "kevin": "케빈",
    "keynes": "케인스",
    "khrushchev": "흐루쇼프",
    "kim": "김",
    "king": "킹",
    "king kong": "킹콩",
    "klaus": "클라우스",
    "klein": "클라인",
    "kobayashi": "고바야시",
    "kobe bryant": "코비 브라이언트",
    "koch": "코흐",
    "kublai khan": "쿠빌라이 칸",
    "kuznetsov": "쿠즈네초프",
    "lady gaga": "레이디 가가",
    "larry": "래리",
    "larry page": "래리 페이지",
    "lars": "라르스",
    "laura": "로라",
    "lauren": "로런",
    "laurent": "로랑",
    "lawrence": "로런스",
    "lebron james": "르브론 제임스",
    "lehmann": "레만",
    "lenin": "레닌",
    "leo": "레오",
    "leonard": "레너드",
    "leonardo": "레오나르도",
    "leonardo da vinci": "레오나르도 다빈치",
    "leonardo dicaprio": "레오나르도 디카프리오",
    "lewis": "루이스",
    "lily": "릴리",
    "lincoln": "링컨",
    "linda": "린다",
    "linus torvalds": "리누스 토르발스",
    "lionel messi": "리오넬 메시",
    "lisa": "리사",
    "liszt": "리스트",
    "little mermaid": "인어공주",
    "liu": "류",
    "loki": "로키",
    "lopez": "로페스",
    "lorenzo": "로렌초",
    "louis": "루이",
    "luca": "루카",
    "lucas": "루카스",
    "lucy": "루시",
    "luigi": "루이지",
    "luis": "루이스",
    "luke": "루크",
    "luke skywalker": "루크 스카이워커",
    "luther": "루터",
    "lydia": "리디아",
    "macbeth": "맥베스",
    "machiavelli": "마키아벨리",
    "macron": "마크롱",
    "madonna": "마돈나",
    "magellan": "마젤란",
    "mandela": "만델라",
    "manuel": "마누엘",
    "mao zedong": "마오쩌둥",
    "maradona": "마라도나",
    "marco": "마르코",
    "marco polo": "마르코 폴로",
    "marconi": "마르코니",
    "marcus": "마커스",
    "margaret": "마거릿",
    "maria": "마리아",
    "marie": "마리",
    "marie curie": "마리 퀴리",
    "marilyn monroe": "메릴린 먼로",
    "mario": "마리오",
    "mark": "마크",
    "mark twain": "마크 트웨인",
    "mark zuckerberg": "마크 저커버그",
    "martha": "마사",
    "martin": "마틴",
    "martin luther king": "마틴 루서 킹",
    "martinez": "마르티네스",
    "mary": "메리",
    "mateo": "마테오",
    "matisse": "마티스",
    "matteo": "마테오",
    "matthew": "매슈",
    "maurice": "모리스",
    "max": "맥스",
    "maxwell": "맥스웰",
    "mbappe": "음바페",
    "medusa": "메두사",
    "megan": "메건",
    "melissa": "멜리사",
    "mendel": "멘델",
    "mendoza": "멘도사",
    "merkel": "메르켈",
    "meryl streep": "메릴 스트립",
    "messi": "메시",
    "meyer": "마이어",
    "mia": "미아",
    "michael": "마이클",
    "michael jackson": "마이클 잭슨",
    "michael jordan": "마이클 조던",
    "michelangelo": "미켈란젤로",
    "michelle": "미셸",
    "mickey mouse": "미키 마우스",
    "miguel": "미겔",
    "mike": "마이크",
    "miller": "밀러",
    "mitchell": "미첼",
    "miyazaki": "미야자키",
    "moana": "모아나",
    "modi": "모디",
    "mohammed": "무함마드",
    "monet": "모네",
    "monica": "모니카",
    "monroe": "먼로",
    "moore": "무어",
    "moreau": "모로",
    "moretti": "모레티",
    "morgan": "모건",
    "morris": "모리스",
    "morse": "모스",
    "moses": "모세",
    "mother teresa": "마더 테레사",
    "mozart": "모차르트",
    "mueller": "뮐러",
    "muhammad ali": "무하마드 알리",
    "muller": "뮐러",
    "murakami": "무라카미",
    "murphy": "머피",
    "musk": "머스크",
    "mussolini": "무솔리니",
    "nadal": "나달",
    "nakamura": "나카무라",
    "nancy": "낸시",
    "naomi": "나오미",
    "napoleon": "나폴레옹",
    "naruto": "나루토",
    "natalie": "나탈리",
    "natasha": "나타샤",
    "nathan": "네이선",
    "neil": "닐",
    "nelson": "넬슨",
    "nelson mandela": "넬슨 만델라",
    "nemo": "니모",
    "neumann": "노이만",
    "newton": "뉴턴",
    "neymar": "네이마르",
    "nguyen": "응우옌",
    "nicholas": "니컬러스",
    "nick": "닉",
    "nicole": "니콜",
    "nietzsche": "니체",
    "nightingale": "나이팅게일",
    "nikola tesla": "니콜라 테슬라",
    "nikolai": "니콜라이",
    "nils": "닐스",
    "nina": "니나",
    "nixon": "닉슨",
    "noah": "노아",
    "nobel": "노벨",
    "nolan": "놀런",
    "norman": "노먼",
    "obama": "오바마",
    "odin": "오딘",
    "odysseus": "오디세우스",
    "olaf": "올라프",
    "olga": "올가",
    "oliver": "올리버",
    "olivia": "올리비아",
    "oppenheimer": "오펜하이머",
    "oprah winfrey": "오프라 윈프리",
    "orwell": "오웰",
    "oscar": "오스카",
    "othello": "오셀로",
    "otto": "오토",
    "pablo": "파블로",
    "pablo picasso": "파블로 피카소",
    "pandora": "판도라",
    "parker": "파커",
    "pascal": "파스칼",
    "pasteur": "파스퇴르",
    "patricia": "패트리샤",
    "patrick": "패트릭",
    "paul": "폴",
    "paul mccartney": "폴 매카트니",
    "paula": "폴라",
    "pavlov": "파블로프",
    "pedro": "페드로",
    "pele": "펠레",
    "perez": "페레스",
    "perry": "페리",
    "peter": "피터",
    "peter pan": "피터 팬",
    "peterson": "피터슨",
    "petrov": "페트로프",
    "philip": "필립",
    "phillips": "필립스",
    "picasso": "피카소",
    "pierre": "피에르",
    "pikachu": "피카츄",
    "pinocchio": "피노키오",
    "planck": "플랑크",
    "plato": "플라톤",
    "pokemon": "포켓몬",
    "popov": "포포프",
    "poseidon": "포세이돈",
    "powell": "파월",
    "price": "프라이스",
    "prometheus": "프로메테우스",
    "ptolemy": "프톨레마이오스",
    "pushkin": "푸시킨",
    "putin": "푸틴",
    "pythagoras": "피타고라스",
    "quentin tarantino": "쿠엔틴 타란티노",
    "rachel": "레이철",
    "rafael": "라파엘",
    "ralph": "랠프",
    "ramirez": "라미레스",
    "rapunzel": "라푼젤",
    "raul": "라울",
    "raymond": "레이먼드",
    "reagan": "레이건",
    "rebecca": "리베카",
    "reed": "리드",
    "rembrandt": "렘브란트",
    "renoir": "르누아르",
    "reyes": "레예스",
    "ricardo": "리카르도",
    "richard": "리처드",
    "richardson": "리처드슨",
    "richter": "리히터",
    "rihanna": "리한나",
    "rivera": "리베라",
    "robert": "로버트",
    "roberto": "로베르토",
    "roberts": "로버츠",
    "robin hood": "로빈 후드",
    "robinson": "로빈슨",
    "rockefeller": "록펠러",
    "rodriguez": "로드리게스",
    "roger": "로저",
    "roger federer": "로저 페더러",
    "rogers": "로저스",
    "romano": "로마노",
    "romeo": "로미오",
    "ronald": "로널드",
    "ronald reagan": "로널드 레이건",
    "ronaldo": "호날두",
    "roosevelt": "루스벨트",
    "rosa": "로사",
    "rose": "로즈",
    "rossi": "로시",
    "rousseau": "루소",
    "rowling": "롤링",
    "russell": "러셀",
    "ruth": "루스",
    "rutherford": "러더퍼드",
    "ryan": "라이언",
    "salvador dali": "살바도르 달리",
    "sam altman": "샘 올트먼",
    "samuel": "새뮤얼",
    "sanchez": "산체스",
    "sanders": "샌더스",
    "sandra": "산드라",
    "santa claus": "산타클로스",
    "santos": "산토스",
    "sarah": "사라",
    "sato": "사토",
    "satya nadella": "사티아 나델라",
    "scarlett johansson": "스칼릿 요한슨",
    "schmidt": "슈미트",
    "schneider": "슈나이더",
    "schrodinger": "슈뢰딩거",
    "schubert": "슈베르트",
    "schulz": "슐츠",
    "scott": "스콧",
    "sean": "션",
    "sergei": "세르게이",
    "sergio": "세르히오",
    "shakespeare": "셰익스피어",
    "sherlock": "셜록",
    "sherlock holmes": "셜록 홈스",
    "shrek": "슈렉",
    "sigmund freud": "지크문트 프로이트",
    "silva": "실바",
    "simba": "심바",
    "simmons": "시먼스",
    "simon": "사이먼",
    "smirnov": "스미르노프",
    "smith": "스미스",
    "snoopy": "스누피",
    "snow white": "백설공주",
    "socrates": "소크라테스",
    "sofia": "소피아",
    "sokolov": "소콜로프",
    "solomon": "솔로몬",
    "sonic": "소닉",
    "sophia": "소피아",
    "sophie": "소피",
    "spider-man": "스파이더맨",
    "spielberg": "스필버그",
    "stalin": "스탈린",
    "stan lee": "스탠 리",
    "stanley": "스탠리",
    "stefan": "슈테판",
    "stella": "스텔라",
    "stephen": "스티븐",
    "stephen hawking": "스티븐 호킹",
    "stephen king": "스티븐 킹",
    "steve": "스티브",
    "steve jobs": "스티브 잡스",
    "steve wozniak": "스티브 워즈니악",
    "steven": "스티븐",
    "steven spielberg": "스티븐 스필버그",
    "stewart": "스튜어트",
    "stuart": "스튜어트",
    "sullivan": "설리번",
    "sundar pichai": "순다르 피차이",
    "super mario": "슈퍼 마리오",
    "superman": "슈퍼맨",
    "susan": "수전",
    "suzuki": "스즈키",
    "sven": "스벤",
    "svetlana": "스베틀라나",
    "sylvia": "실비아",
    "takahashi": "다카하시",
    "tanaka": "다나카",
    "tarantino": "타란티노",
    "tarzan": "타잔",
    "tatiana": "타티아나",
    "taylor": "테일러",
    "taylor swift": "테일러 스위프트",
    "tchaikovsky": "차이콥스키",
    "teresa": "테레사",
    "terminator": "터미네이터",
    "terry": "테리",
    "tesla": "테슬라",
    "theodore": "시어도어",
    "thomas": "토머스",
    "thomas edison": "토머스 에디슨",
    "thompson": "톰프슨",
    "thor": "토르",
    "tiffany": "티파니",
    "tiger woods": "타이거 우즈",
    "tim cook": "팀 쿡",
    "timothy": "티머시",
    "tinker bell": "팅커벨",
    "tolkien": "톨킨",
    "tolstoy": "톨스토이",
    "tom cruise": "톰 크루즈",
    "tony": "토니",
    "torres": "토레스",
    "trotsky": "트로츠키",
    "truman": "트루먼",
    "trump": "트럼프",
    "turing": "튜링",
    "turner": "터너",
    "twain": "트웨인",
    "usain bolt": "우사인 볼트",
    "valentina": "발렌티나",
    "van gogh": "반 고흐",
    "vanessa": "바네사",
    "venus williams": "비너스 윌리엄스",
    "vera": "베라",
    "verdi": "베르디",
    "veronica": "베로니카",
    "victor": "빅터",
    "victoria": "빅토리아",
    "vincent": "빈센트",
    "violet": "바이올렛",
    "virginia": "버지니아",
    "vivaldi": "비발디",
    "vivian": "비비안",
    "vladimir": "블라디미르",
    "vladimir putin": "블라디미르 푸틴",
    "voldemort": "볼드모트",
    "voltaire": "볼테르",
    "wagner": "바그너",
    "walker": "워커",
    "walt disney": "월트 디즈니",
    "walter": "월터",
    "wang": "왕",
    "ward": "워드",
    "warren buffett": "워런 버핏",
    "washington": "워싱턴",
    "watanabe": "와타나베",
    "watson": "왓슨",
    "watt": "와트",
    "wayne": "웨인",
    "weber": "베버",
    "wendy": "웬디",
    "werner": "베르너",
    "white": "화이트",
    "will smith": "윌 스미스",
    "william": "윌리엄",
    "william shakespeare": "윌리엄 셰익스피어",
    "williams": "윌리엄스",
    "wilson": "윌슨",
    "winnie the pooh": "곰돌이 푸",
    "winston churchill": "윈스턴 처칠",
    "wittgenstein": "비트겐슈타인",
    "wizard of oz": "오즈의 마법사",
    "wolfgang": "볼프강",
    "wonder woman": "원더우먼",
    "wood": "우드",
    "wright": "라이트",
    "wright brothers": "라이트 형제",
    "xi jinping": "시진핑",
    "yamada": "야마다",
    "yamamoto": "야마모토",
    "yoda": "요다",
    "yuri": "유리",
    "yvonne": "이본",
    "zachary": "재커리",
    "zelda": "젤다",
    "zelensky": "젤렌스키",
    "zeus": "제우스",
    "zhang": "장",
    "zhao": "자오",
    "zidane": "지단",
    "zimmermann": "치머만",
    "zuckerberg": "저커버그",
}

__all__ = ["PEOPLE"]
