"""Geographic names, nationalities and languages as Koreans read them aloud."""
from __future__ import annotations

from typing import Dict

PLACES: Dict[str, str] = {
    "abidjan": "아비장",
    "abu dhabi": "아부다비",
    "abuja": "아부자",
    "accra": "아크라",
    "addis ababa": "아디스아바바",
    "afghanistan": "아프가니스탄",
    "africa": "아프리카",
    "akihabara": "아키하바라",
    "alabama": "앨라배마",
    "alaska": "알래스카",
    "albania": "알바니아",
    "alberta": "앨버타",
    "algeria": "알제리",
    "alps": "알프스",
    "amazon": "아마존",
    "america": "미국",
    "american": "미국",
    "amman": "암만",
    "amsterdam": "암스테르담",
    "andes": "안데스",
    "andorra": "안도라",
    "angkor wat": "앙코르와트",
    "angola": "앙골라",
    "ankara": "앙카라",
    "antarctica": "남극",
    "antigua and barbuda": "앤티가 바부다",
    "apgujeong": "압구정",
    "arabic": "아랍어",
    "arctic": "북극",
    "arctic ocean": "북극해",
    "argentina": "아르헨티나",
    "argentinian": "아르헨티나",
    "arizona": "애리조나",
    "arkansas": "아칸소",
    "armenia": "아르메니아",
    "asia": "아시아",
    "astana": "아스타나",
    "asuncion": "아순시온",
    "athens": "아테네",
    "atlanta": "애틀랜타",
    "atlantic": "대서양",
    "atlantic ocean": "대서양",
    "auckland": "오클랜드",
    "austin": "오스틴",
    "australia": "호주",
    "australian": "호주",
    "austria": "오스트리아",
    "azerbaijan": "아제르바이잔",
    "baekdusan": "백두산",
    "baghdad": "바그다드",
    "bahamas": "바하마",
    "bahrain": "바레인",
    "baku": "바쿠",
    "bali": "발리",
    "balkans": "발칸반도",
    "baltic sea": "발트해",
    "baltimore": "볼티모어",
    "bamako": "바마코",
    "bangkok": "방콕",
    "bangladesh": "방글라데시",
    "barbados": "바베이도스",
    "barcelona": "바르셀로나",
    "basque": "바스크",
    "bavaria": "바이에른",
    "beijing": "베이징",
    "beirut": "베이루트",
    "belarus": "벨라루스",
    "belgium": "벨기에",
    "belgrade": "베오그라드",
    "belize": "벨리즈",
    "bengaluru": "벵갈루루",
    "benin": "베냉",
    "bering strait": "베링 해협",
    "berlin": "베를린",
    "bern": "베른",
    "beverly hills": "베벌리힐스",
    "bhutan": "부탄",
    "big ben": "빅벤",
    "bishkek": "비슈케크",
    "black sea": "흑해",
    "bogota": "보고타",
    "bolivia": "볼리비아",
    "bosnia and herzegovina": "보스니아 헤르체고비나",
    "boston": "보스턴",
    "botswana": "보츠와나",
    "brasilia": "브라질리아",
    "bratislava": "브라티슬라바",
    "brazil": "브라질",
    "brazilian": "브라질",
    "brazzaville": "브라자빌",
    "brisbane": "브리즈번",
    "britain": "영국",
    "british": "영국",
    "broadway": "브로드웨이",
    "bronx": "브롱크스",
    "brooklyn": "브루클린",
    "brunei": "브루나이",
    "brussels": "브뤼셀",
    "bucharest": "부쿠레슈티",
    "budapest": "부다페스트",
    "buenos aires": "부에노스아이레스",
    "bukchon": "북촌",
    "bukhansan": "북한산",
    "bulgaria": "불가리아",
    "burkina faso": "부르키나파소",
    "burma": "미얀마",
    "burundi": "부룬디",
    "busan": "부산",
    "cairo": "카이로",
    "calgary": "캘거리",
    "california": "캘리포니아",
    "cambodia": "캄보디아",
    "cameroon": "카메룬",
    "canada": "캐나다",
    "canadian": "캐나다",
    "canberra": "캔버라",
    "cantonese": "광둥어",
    "cape town": "케이프타운",
    "cape verde": "카보베르데",
    "caracas": "카라카스",
    "caribbean": "카리브해",
    "caspian sea": "카스피해",
    "catalonia": "카탈루냐",
    "central african republic": "중앙아프리카 공화국",
    "central asia": "중앙아시아",
    "central park": "센트럴파크",
    "chad": "차드",
    "champs elysees": "샹젤리제",
    "changdeokgung": "창덕궁",
    "chengdu": "청두",
    "chennai": "첸나이",
    "cheongdam": "청담",
    "chicago": "시카고",
    "chile": "칠레",
    "china": "중국",
    "chinatown": "차이나타운",
    "chinese": "중국",
    "chongqing": "충칭",
    "chungcheong": "충청",
    "chungcheongbuk-do": "충청북도",
    "chungcheongnam-do": "충청남도",
    "cologne": "쾰른",
    "colombia": "콜롬비아",
    "colombo": "콜롬보",
    "colorado": "콜로라도",
    "colosseum": "콜로세움",
    "comoros": "코모로",
    "conakry": "코나크리",
    "congo": "콩고",
    "connecticut": "코네티컷",
    "copenhagen": "코펜하겐",
    "costa rica": "코스타리카",
    "crete": "크레타",
    "croatia": "크로아티아",
    "cuba": "쿠바",
    "cyprus": "키프로스",
    "czech": "체코",
    "czechia": "체코",
    "daegu": "대구",
    "daejeon": "대전",
    "dakar": "다카르",
    "dallas": "댈러스",
    "damascus": "다마스쿠스",
    "danang": "다낭",
    "danube": "다뉴브강",
    "dead sea": "사해",
    "delaware": "델라웨어",
    "delhi": "델리",
    "denmark": "덴마크",
    "denver": "덴버",
    "detroit": "디트로이트",
    "dhaka": "다카",
    "djibouti": "지부티",
    "dmz": "디엠지",
    "doha": "도하",
    "dokdo": "독도",
    "dominica": "도미니카",
    "dominican republic": "도미니카 공화국",
    "dongdaemun": "동대문",
    "dotonbori": "도톤보리",
    "dubai": "두바이",
    "dublin": "더블린",
    "dushanbe": "두샨베",
    "dusseldorf": "뒤셀도르프",
    "dutch": "네덜란드",
    "east asia": "동아시아",
    "east sea": "동해",
    "east timor": "동티모르",
    "ecuador": "에콰도르",
    "edinburgh": "에든버러",
    "egypt": "이집트",
    "egyptian": "이집트",
    "eiffel tower": "에펠탑",
    "el salvador": "엘살바도르",
    "empire state building": "엠파이어스테이트 빌딩",
    "england": "잉글랜드",
    "english": "영어",
    "english channel": "영국 해협",
    "equatorial guinea": "적도 기니",
    "eritrea": "에리트레아",
    "estonia": "에스토니아",
    "eswatini": "에스와티니",
    "ethiopia": "에티오피아",
    "europe": "유럽",
    "everest": "에베레스트",
    "fiji": "피지",
    "finland": "핀란드",
    "florence": "피렌체",
    "florida": "플로리다",
    "france": "프랑스",
    "frankfurt": "프랑크푸르트",
    "freetown": "프리타운",
    "french": "프랑스",
    "fuji": "후지",
    "fukuoka": "후쿠오카",
    "gabon": "가봉",
    "gaborone": "가보로네",
    "gaeseong": "개성",
    "galapagos": "갈라파고스",
    "gambia": "감비아",
    "ganges": "갠지스강",
    "gangnam": "강남",
    "gangneung": "강릉",
    "gangwon": "강원",
    "gangwon-do": "강원도",
    "gaza": "가자",
    "geneva": "제네바",
    "georgia": "조지아",
    "german": "독일",
    "germany": "독일",
    "ghana": "가나",
    "ginza": "긴자",
    "glasgow": "글래스고",
    "gobi desert": "고비 사막",
    "golden gate bridge": "금문교",
    "grand canyon": "그랜드캐니언",
    "great barrier reef": "그레이트배리어리프",
    "great britain": "영국",
    "great lakes": "오대호",
    "great wall": "만리장성",
    "greece": "그리스",
    "greek": "그리스",
    "greenland": "그린란드",
    "grenada": "그레나다",
    "guangzhou": "광저우",
    "guatemala": "과테말라",
    "guinea": "기니",
    "guinea-bissau": "기니비사우",
    "gulf of mexico": "멕시코만",
    "guyana": "가이아나",
    "gwanghwamun": "광화문",
    "gwangju": "광주",
    "gyeongbokgung": "경복궁",
    "gyeonggi": "경기",
    "gyeonggi-do": "경기도",
    "gyeongju": "경주",
    "gyeongsang": "경상",
    "gyeongsangbuk-do": "경상북도",
    "gyeongsangnam-do": "경상남도",
    "hague": "헤이그",
    "haiti": "아이티",
    "hallasan": "한라산",
    "hamburg": "함부르크",
    "han river": "한강",
    "hangang": "한강",
    "hangul": "한글",
    "hanja": "한자",
    "hanoi": "하노이",
    "harajuku": "하라주쿠",
    "harare": "하라레",
    "harlem": "할렘",
    "havana": "아바나",
    "hawaii": "하와이",
    "hebrew": "히브리어",
    "helsinki": "헬싱키",
    "himalayas": "히말라야",
    "hindi": "힌디어",
    "hiroshima": "히로시마",
    "ho chi minh": "호찌민",
    "ho chi minh city": "호찌민시",
    "hokkaido": "홋카이도",
    "holland": "네덜란드",
    "hollywood": "할리우드",
    "honduras": "온두라스",
    "hong kong": "홍콩",
    "hongdae": "홍대",
    "honolulu": "호놀룰루",
    "houston": "휴스턴",
    "hungary": "헝가리",
    "iceland": "아이슬란드",
    "idaho": "아이다호",
    "illinois": "일리노이",
    "incheon": "인천",
    "india": "인도",
    "indian": "인도",
    "indian ocean": "인도양",
    "indiana": "인디애나",
    "indonesia": "인도네시아",
    "indonesian": "인도네시아",
    "insadong": "인사동",
    "iowa": "아이오와",
    "iran": "이란",
    "iraq": "이라크",
    "ireland": "아일랜드",
    "irish": "아일랜드",
    "islamabad": "이슬라마바드",
    "israel": "이스라엘",
    "israeli": "이스라엘",
    "istanbul": "이스탄불",
    "itaewon": "이태원",
    "italian": "이탈리아",
    "italy": "이탈리아",
    "ivory coast": "코트디부아르",
    "jakarta": "자카르타",
    "jamaica": "자메이카",
    "jamsil": "잠실",
    "japan": "일본",
    "japanese": "일본",
    "jeju": "제주",
    "jeju island": "제주도",
    "jeju-do": "제주도",
    "jejudo": "제주도",
    "jeolla": "전라",
    "jeollabuk-do": "전라북도",
    "jeollanam-do": "전라남도",
    "jeonju": "전주",
    "jerusalem": "예루살렘",
    "johannesburg": "요하네스버그",
    "jongno": "종로",
    "jordan": "요르단",
    "kabul": "카불",
    "kaesong": "개성",
    "kampala": "캄팔라",
    "kansas": "캔자스",
    "karachi": "카라치",
    "kashmir": "카슈미르",
    "kathmandu": "카트만두",
    "kazakhstan": "카자흐스탄",
    "kentucky": "켄터키",
    "kenya": "케냐",
    "khartoum": "하르툼",
    "kigali": "키갈리",
    "kilimanjaro": "킬리만자로",
    "kingston": "킹스턴",
    "kinshasa": "킨샤사",
    "kiribati": "키리바시",
    "kolkata": "콜카타",
    "korea": "한국",
    "korean": "한국",
    "kosovo": "코소보",
    "kuala lumpur": "쿠알라룸푸르",
    "kuwait": "쿠웨이트",
    "kuwait city": "쿠웨이트시티",
    "kyiv": "키이우",
    "kyoto": "교토",
    "kyrgyzstan": "키르기스스탄",
    "la paz": "라파스",
    "lagos": "라고스",
    "lahore": "라호르",
    "laos": "라오스",
    "las vegas": "라스베이거스",
    "latin": "라틴",
    "latin america": "라틴 아메리카",
    "latvia": "라트비아",
    "lebanon": "레바논",
    "lesotho": "레소토",
    "liberia": "라이베리아",
    "libreville": "리브르빌",
    "libya": "리비아",
    "liechtenstein": "리히텐슈타인",
    "lima": "리마",
    "lisbon": "리스본",
    "lithuania": "리투아니아",
    "liverpool": "리버풀",
    "ljubljana": "류블랴나",
    "london": "런던",
    "los angeles": "로스앤젤레스",
    "louisiana": "루이지애나",
    "louvre": "루브르",
    "luanda": "루안다",
    "lusaka": "루사카",
    "luxembourg": "룩셈부르크",
    "lyon": "리옹",
    "macau": "마카오",
    "machu picchu": "마추픽추",
    "madagascar": "마다가스카르",
    "madrid": "마드리드",
    "malawi": "말라위",
    "malaysia": "말레이시아",
    "maldives": "몰디브",
    "mali": "말리",
    "malta": "몰타",
    "manama": "마나마",
    "manchester": "맨체스터",
    "mandarin": "중국어",
    "manhattan": "맨해튼",
    "manila": "마닐라",
    "mapo": "마포",
    "maputo": "마푸투",
    "marseille": "마르세유",
    "marshall islands": "마셜 제도",
    "maryland": "메릴랜드",
    "massachusetts": "매사추세츠",
    "mauritania": "모리타니",
    "mauritius": "모리셔스",
    "mecca": "메카",
    "mediterranean": "지중해",
    "mekong": "메콩강",
    "melbourne": "멜버른",
    "mexican": "멕시코",
    "mexico": "멕시코",
    "mexico city": "멕시코시티",
    "miami": "마이애미",
    "michigan": "미시간",
    "micronesia": "미크로네시아",
    "middle east": "중동",
    "milan": "밀라노",
    "minneapolis": "미니애폴리스",
    "minnesota": "미네소타",
    "minsk": "민스크",
    "mississippi": "미시시피",
    "mississippi river": "미시시피강",
    "missouri": "미주리",
    "mogadishu": "모가디슈",
    "moldova": "몰도바",
    "monaco": "모나코",
    "mongolia": "몽골",
    "monrovia": "몬로비아",
    "montana": "몬태나",
    "montenegro": "몬테네그로",
    "montevideo": "몬테비데오",
    "montmartre": "몽마르트르",
    "montreal": "몬트리올",
    "morocco": "모로코",
    "moscow": "모스크바",
    "mount everest": "에베레스트산",
    "mount fuji": "후지산",
    "mount rushmore": "러시모어산",
    "mozambique": "모잠비크",
    "mumbai": "뭄바이",
    "munich": "뮌헨",
    "muscat": "무스카트",
    "myanmar": "미얀마",
    "myeong-dong": "명동",
    "myeongdong": "명동",
    "nagasaki": "나가사키",
    "nagoya": "나고야",
    "nairobi": "나이로비",
    "namdaemun": "남대문",
    "namibia": "나미비아",
    "namsan": "남산",
    "naples": "나폴리",
    "nauru": "나우루",
    "naypyidaw": "네피도",
    "nebraska": "네브래스카",
    "nepal": "네팔",
    "netherlands": "네덜란드",
    "nevada": "네바다",
    "new delhi": "뉴델리",
    "new hampshire": "뉴햄프셔",
    "new jersey": "뉴저지",
    "new mexico": "뉴멕시코",
    "new orleans": "뉴올리언스",
    "new york": "뉴욕",
    "new york city": "뉴욕시",
    "new zealand": "뉴질랜드",
    "niagara falls": "나이아가라 폭포",
    "nicaragua": "니카라과",
    "nicosia": "니코시아",
    "niger": "니제르",
    "nigeria": "나이지리아",
    "nile": "나일강",
    "normandy": "노르망디",
    "north america": "북아메리카",
    "north carolina": "노스캐롤라이나",
    "north chungcheong": "충청북도",
    "north dakota": "노스다코타",
    "north gyeongsang": "경상북도",
    "north jeolla": "전라북도",
    "north korea": "북한",
    "north macedonia": "북마케도니아",
    "north sea": "북해",
    "northern ireland": "북아일랜드",
    "norway": "노르웨이",
    "oceania": "오세아니아",
    "ohio": "오하이오",
    "okinawa": "오키나와",
    "oklahoma": "오클라호마",
    "oman": "오만",
    "ontario": "온타리오",
    "oregon": "오리건",
    "orlando": "올랜도",
    "osaka": "오사카",
    "oslo": "오슬로",
    "ottawa": "오타와",
    "ouagadougou": "와가두구",
    "oxford": "옥스퍼드",
    "pacific": "태평양",
    "pacific ocean": "태평양",
    "pakistan": "파키스탄",
    "palau": "팔라우",
    "palestine": "팔레스타인",
    "panama": "파나마",
    "panama canal": "파나마 운하",
    "panama city": "파나마시티",
    "panmunjom": "판문점",
    "papua new guinea": "파푸아뉴기니",
    "paraguay": "파라과이",
    "paramaribo": "파라마리보",
    "paris": "파리",
    "patagonia": "파타고니아",
    "pennsylvania": "펜실베이니아",
    "persia": "페르시아",
    "persian": "페르시아어",
    "persian gulf": "페르시아만",
    "perth": "퍼스",
    "peru": "페루",
    "philadelphia": "필라델피아",
    "philippines": "필리핀",
    "phnom penh": "프놈펜",
    "phoenix": "피닉스",
    "phuket": "푸껫",
    "podgorica": "포드고리차",
    "poland": "폴란드",
    "porto": "포르투",
    "portugal": "포르투갈",
    "prague": "프라하",
    "pretoria": "프리토리아",
    "provence": "프로방스",
    "pusan": "부산",
    "pyongyang": "평양",
    "pyramids": "피라미드",
    "qatar": "카타르",
    "quebec": "퀘벡",
    "queens": "퀸스",
    "quito": "키토",
    "rabat": "라바트",
    "ramallah": "라말라",
    "red sea": "홍해",
    "republic of korea": "대한민국",
    "reykjavik": "레이캬비크",
    "rhine": "라인강",
    "rhode island": "로드아일랜드",
    "riga": "리가",
    "rio de janeiro": "리우데자네이루",
    "riyadh": "리야드",
    "rockies": "로키산맥",
    "rocky mountains": "로키산맥",
    "romania": "루마니아",
    "rome": "로마",
    "roppongi": "롯폰기",
    "russia": "러시아",
    "russian": "러시아",
    "rwanda": "르완다",
    "sahara": "사하라",
    "sahara desert": "사하라 사막",
    "saigon": "사이공",
    "saint kitts and nevis": "세인트키츠 네비스",
    "saint lucia": "세인트루시아",
    "samoa": "사모아",
    "san diego": "샌디에이고",
    "san francisco": "샌프란시스코",
    "san jose": "새너제이",
    "san marino": "산마리노",
    "sanaa": "사나",
    "santiago": "산티아고",
    "sao paulo": "상파울루",
    "sao tome and principe": "상투메 프린시페",
    "sapporo": "삿포로",
    "sarajevo": "사라예보",
    "sardinia": "사르데냐",
    "saudi": "사우디",
    "saudi arabia": "사우디아라비아",
    "scandinavia": "스칸디나비아",
    "scotland": "스코틀랜드",
    "sea of japan": "동해",
    "seattle": "시애틀",
    "seine": "센강",
    "sejong": "세종",
    "senegal": "세네갈",
    "seocho": "서초",
    "seongsu": "성수",
    "seoraksan": "설악산",
    "seoul": "서울",
    "serbia": "세르비아",
    "seville": "세비야",
    "seychelles": "세이셸",
    "shanghai": "상하이",
    "shenzhen": "선전",
    "shibuya": "시부야",
    "shinjuku": "신주쿠",
    "siberia": "시베리아",
    "sicily": "시칠리아",
    "sierra leone": "시에라리온",
    "silicon valley": "실리콘밸리",
    "sinchon": "신촌",
    "singapore": "싱가포르",
    "skopje": "스코페",
    "slovakia": "슬로바키아",
    "slovenia": "슬로베니아",
    "sofia": "소피아",
    "soho": "소호",
    "sokcho": "속초",
    "solomon islands": "솔로몬 제도",
    "somalia": "소말리아",
    "songpa": "송파",
    "south africa": "남아프리카 공화국",
    "south america": "남아메리카",
    "south carolina": "사우스캐롤라이나",
    "south chungcheong": "충청남도",
    "south dakota": "사우스다코타",
    "south gyeongsang": "경상남도",
    "south jeolla": "전라남도",
    "south korea": "한국",
    "south sudan": "남수단",
    "southeast asia": "동남아시아",
    "southern ocean": "남극해",
    "spain": "스페인",
    "spanish": "스페인",
    "sri lanka": "스리랑카",
    "st. louis": "세인트루이스",
    "statue of liberty": "자유의 여신상",
    "stockholm": "스톡홀름",
    "stonehenge": "스톤헨지",
    "strait of hormuz": "호르무즈 해협",
    "stuttgart": "슈투트가르트",
    "sudan": "수단",
    "suez canal": "수에즈 운하",
    "suriname": "수리남",
    "suva": "수바",
    "suwon": "수원",
    "sweden": "스웨덴",
    "swiss": "스위스",
    "switzerland": "스위스",
    "sydney": "시드니",
    "syria": "시리아",
    "taipei": "타이베이",
    "taiwan": "대만",
    "taj mahal": "타지마할",
    "tajikistan": "타지키스탄",
    "tallinn": "탈린",
    "tanzania": "탄자니아",
    "tashkent": "타슈켄트",
    "tbilisi": "트빌리시",
    "tehran": "테헤란",
    "tel aviv": "텔아비브",
    "tennessee": "테네시",
    "texas": "텍사스",
    "thai": "태국",
    "thailand": "태국",
    "thames": "템스강",
    "the hague": "헤이그",
    "tibet": "티베트",
    "times square": "타임스스퀘어",
    "tirana": "티라나",
    "togo": "토고",
    "tokyo": "도쿄",
    "tonga": "통가",
    "toronto": "토론토",
    "trinidad and tobago": "트리니다드 토바고",
    "tripoli": "트리폴리",
    "tunis": "튀니스",
    "tunisia": "튀니지",
    "turkey": "튀르키예",
    "turkish": "튀르키예",
    "turkmenistan": "투르크메니스탄",
    "tuscany": "토스카나",
    "tuvalu": "투발루",
    "u.s.": "미국",
    "u.s.a.": "미국",
    "uae": "아랍에미리트",
    "uganda": "우간다",
    "uk": "영국",
    "ukraine": "우크라이나",
    "ukrainian": "우크라이나",
    "ulaanbaatar": "울란바토르",
    "ulsan": "울산",
    "united arab emirates": "아랍에미리트",
    "united kingdom": "영국",
    "united states": "미국",
    "uruguay": "우루과이",
    "usa": "미국",
    "utah": "유타",
    "uzbekistan": "우즈베키스탄",
    "valletta": "발레타",
    "vancouver": "밴쿠버",
    "vanuatu": "바누아투",
    "vatican": "바티칸",
    "vatican city": "바티칸시티",
    "venezuela": "베네수엘라",
    "vermont": "버몬트",
    "versailles": "베르사유",
    "victoria falls": "빅토리아 폭포",
    "vienna": "빈",
    "vientiane": "비엔티안",
    "vietnam": "베트남",
    "vietnamese": "베트남",
    "vilnius": "빌뉴스",
    "virginia": "버지니아",
    "vladivostok": "블라디보스토크",
    "wales": "웨일스",
    "wall street": "월가",
    "warsaw": "바르샤바",
    "washington": "워싱턴",
    "washington d.c.": "워싱턴 디시",
    "wellington": "웰링턴",
    "west sea": "서해",
    "west virginia": "웨스트버지니아",
    "windhoek": "빈트후크",
    "wisconsin": "위스콘신",
    "wyoming": "와이오밍",
    "xinjiang": "신장",
    "yangon": "양곤",
    "yangtze": "양쯔강",
    "yaounde": "야운데",
    "yellow sea": "황해",
    "yemen": "예멘",
    "yeouido": "여의도",
    "yerevan": "예레반",
    "yokohama": "요코하마",
    "yongin": "용인",
    "yongsan": "용산",
    "zagreb": "자그레브",
    "zambia": "잠비아",
    "zimbabwe": "짐바브웨",
    "zurich": "취리히",
}

__all__ = ["PLACES"]
