"""Romanized Korean words and names restored to their original Hangul."""
from __future__ import annotations

from typing import Dict

ROMANIZED: Dict[str, str] = {
    "aegukga": "애국가",
    "aegyo": "애교",
    "aegyosal": "애교살",
    "aespa": "에스파",
    "agujjim": "아귀찜",
    "ahjumma": "아줌마",
    "ahjussi": "아저씨",
    "ahn": "안",
    "aigo": "아이고",
    "aigoo": "아이고",
    "ajeossi": "아저씨",
    "ajumma": "아줌마",
    "ajussi": "아저씨",
    "andong jjimdak": "안동찜닭",
    "ani": "아니",
    "aniyo": "아니요",
    "anju": "안주",
    "annyeong": "안녕",
    "annyeonghaseyo": "안녕하세요",
    "annyeonghi gaseyo": "안녕히 가세요",
    "annyeonghi gyeseyo": "안녕히 계세요",
    "apgujeong": "압구정",
    "appa": "아빠",
    "ateez": "에이티즈",
    "babo": "바보",
    "baduk": "바둑",
    "bae": "배",
    "baechu": "배추",
    "baechu kimchi": "배추김치",
    "baek": "백",
    "baekban": "백반",
    "baekje": "백제",
    "baekseju": "백세주",
    "banchan": "반찬",
    "bangtan": "방탄",
    "bangtan sonyeondan": "방탄소년단",
    "banmal": "반말",
    "bballi": "빨리",
    "bibim guksu": "비빔국수",
    "bibimbap": "비빔밥",
    "bigbang": "빅뱅",
    "bindaetteok": "빈대떡",
    "bingsu": "빙수",
    "blackpink": "블랙핑크",
    "bogoshipeo": "보고 싶어",
    "bogosipda": "보고 싶다",
    "bokbunja": "복분자",
    "bokkeumbap": "볶음밥",
    "bossam": "보쌈",
    "bts": "비티에스",
    "budae jjigae": "부대찌개",
    "bulgogi": "불고기",
    "bungeoppang": "붕어빵",
    "busan": "부산",
    "byeon": "변",
    "byun": "변",
    "cha": "차",
    "chae": "채",
    "chaebol": "재벌",
    "chapssaltteok": "찹쌀떡",
    "cheonggukjang": "청국장",
    "cheongwadae": "청와대",
    "chimaek": "치맥",
    "chincha": "진짜",
    "cho": "조",
    "chobap": "초밥",
    "choi": "최",
    "chueotang": "추어탕",
    "chukhahae": "축하해",
    "chukhahamnida": "축하합니다",
    "chung": "정",
    "chuseok": "추석",
    "cj": "씨제이",
    "comeback": "컴백",
    "coupang": "쿠팡",
    "daebak": "대박",
    "daegu": "대구",
    "daehan": "대한",
    "daejeon": "대전",
    "dakbal": "닭발",
    "dakdoritang": "닭도리탕",
    "dakgalbi": "닭갈비",
    "dakkochi": "닭꼬치",
    "dalgona": "달고나",
    "daum": "다음",
    "doenjang": "된장",
    "doenjang jjigae": "된장찌개",
    "dokdo": "독도",
    "doljanchi": "돌잔치",
    "dolsot bibimbap": "돌솥비빔밥",
    "dongan": "동안",
    "dongchimi": "동치미",
    "dongdaemun": "동대문",
    "dongdongju": "동동주",
    "dongsaeng": "동생",
    "doosan": "두산",
    "doshirak": "도시락",
    "dubu": "두부",
    "dwaeji gukbap": "돼지국밥",
    "emart": "이마트",
    "enhypen": "엔하이픈",
    "eom": "엄",
    "eomeo": "어머",
    "eomma": "엄마",
    "eomuk": "어묵",
    "eonni": "언니",
    "eoseo oseyo": "어서 오세요",
    "eottae": "어때",
    "eotteokhae": "어떡해",
    "exo": "엑소",
    "fan meeting": "팬 미팅",
    "fancam": "팬캠",
    "galbi": "갈비",
    "galbijjim": "갈비찜",
    "galbitang": "갈비탕",
    "gamjatang": "감자탕",
    "gamsahamnida": "감사합니다",
    "gangnam": "강남",
    "gangnam style": "강남스타일",
    "gangwon": "강원",
    "ganjang": "간장",
    "ganjang gejang": "간장게장",
    "gapjil": "갑질",
    "gaya": "가야",
    "gayageum": "가야금",
    "gejang": "게장",
    "geomungo": "거문고",
    "geonbae": "건배",
    "gimbap": "김밥",
    "girls generation": "소녀시대",
    "gmarket": "지마켓",
    "gochu": "고추",
    "gochugaru": "고춧가루",
    "gochujang": "고추장",
    "goguryeo": "고구려",
    "gomapseumnida": "고맙습니다",
    "gomawo": "고마워",
    "gomo": "고모",
    "goo": "구",
    "gopchang": "곱창",
    "goryeo": "고려",
    "gosiwon": "고시원",
    "gostop": "고스톱",
    "got7": "갓세븐",
    "gukak": "국악",
    "gukbap": "국밥",
    "gukhoe": "국회",
    "gwaenchana": "괜찮아",
    "gwaenchanayo": "괜찮아요",
    "gwak": "곽",
    "gwangju": "광주",
    "gwiyeowo": "귀여워",
    "gwon": "권",
    "gyeong": "경",
    "gyeongbokgung": "경복궁",
    "gyeonggi": "경기",
    "gyeongju": "경주",
    "gyeran": "계란",
    "gyeranmari": "계란말이",
    "gyeranppang": "계란빵",
    "gyopo": "교포",
    "haegeum": "해금",
    "haejangguk": "해장국",
    "haemul pajeon": "해물파전",
    "haemultang": "해물탕",
    "hagwon": "학원",
    "hallasan": "한라산",
    "hallyu": "한류",
    "halmeoni": "할머니",
    "han": "한",
    "han river": "한강",
    "hanbando": "한반도",
    "hanbok": "한복",
    "hangang": "한강",
    "hangeul": "한글",
    "hangugeo": "한국어",
    "hanguk": "한국",
    "hanguk saram": "한국 사람",
    "hangukmal": "한국말",
    "hangul": "한글",
    "hangwa": "한과",
    "hanja": "한자",
    "hanjeongsik": "한정식",
    "hanji": "한지",
    "hanok": "한옥",
    "hansik": "한식",
    "hanwha": "한화",
    "hapkido": "합기도",
    "harabeoji": "할아버지",
    "heo": "허",
    "heol": "헐",
    "himnae": "힘내",
    "hobakjuk": "호박죽",
    "hodu gwaja": "호두과자",
    "hoesik": "회식",
    "honbap": "혼밥",
    "hong": "홍",
    "hongdae": "홍대",
    "hongeo": "홍어",
    "honsul": "혼술",
    "hoobae": "후배",
    "hotteok": "호떡",
    "hubae": "후배",
    "huh": "허",
    "hwabyeong": "화병",
    "hwaiting": "화이팅",
    "hwang": "황",
    "hwatu": "화투",
    "hyeon": "현",
    "hyeong": "형",
    "hyun": "현",
    "hyundai": "현대",
    "hyung": "형",
    "idol": "아이돌",
    "incheon": "인천",
    "injeolmi": "인절미",
    "insadong": "인사동",
    "itaewon": "이태원",
    "itzy": "있지",
    "iu": "아이유",
    "ive": "아이브",
    "jajangmyeon": "짜장면",
    "jal jinaesseoyo": "잘 지냈어요",
    "jal meokgesseumnida": "잘 먹겠습니다",
    "jang": "장",
    "jangajji": "장아찌",
    "janggu": "장구",
    "japchae": "잡채",
    "jebal": "제발",
    "jeju": "제주",
    "jeju island": "제주도",
    "jeon": "전",
    "jeong": "정",
    "jeongmal": "정말",
    "jeongol": "전골",
    "jeonju": "전주",
    "jeonse": "전세",
    "jeotgal": "젓갈",
    "jesa": "제사",
    "jin": "진",
    "jinjja": "진짜",
    "jjajangmyeon": "짜장면",
    "jjamppong": "짬뽕",
    "jjang": "짱",
    "jjapaguri": "짜파구리",
    "jjigae": "찌개",
    "jjimdak": "찜닭",
    "jjimjilbang": "찜질방",
    "jo": "조",
    "joa": "좋아",
    "joayo": "좋아요",
    "joesonghamnida": "죄송합니다",
    "jokbal": "족발",
    "jondaemal": "존댓말",
    "jongno": "종로",
    "joon": "준",
    "joseon": "조선",
    "jtbc": "제이티비씨",
    "ju": "주",
    "juk": "죽",
    "jun": "준",
    "jung": "정",
    "juseyo": "주세요",
    "k-drama": "케이드라마",
    "k-pop": "케이팝",
    "kakao": "카카오",
    "kakaotalk": "카카오톡",
    "kalguksu": "칼국수",
    "kamsahamnida": "감사합니다",
    "kang": "강",
    "katalk": "카톡",
    "kbeauty": "케이뷰티",
    "kbs": "케이비에스",
    "kdrama": "케이드라마",
    "kia": "기아",
    "kibun": "기분",
    "kim": "김",
    "kimbap": "김밥",
    "kimchi": "김치",
    "kimchi bokkeumbap": "김치볶음밥",
    "kimchi jjigae": "김치찌개",
    "kimchi mandu": "김치만두",
    "kimjang": "김장",
    "kkakdugi": "깍두기",
    "kkondae": "꼰대",
    "ko": "고",
    "komawo": "고마워",
    "kongguksu": "콩국수",
    "konglish": "콩글리시",
    "kongnamul": "콩나물",
    "koo": "구",
    "korail": "코레일",
    "kpop": "케이팝",
    "kt": "케이티",
    "ktx": "케이티엑스",
    "kwak": "곽",
    "kwon": "권",
    "kyopo": "교포",
    "kyung": "경",
    "le sserafim": "르세라핌",
    "lee": "이",
    "lg": "엘지",
    "lim": "임",
    "lotte": "롯데",
    "maekju": "맥주",
    "maeuntang": "매운탕",
    "makchang": "막창",
    "makgeolli": "막걸리",
    "makguksu": "막국수",
    "maknae": "막내",
    "mandu": "만두",
    "manduguk": "만둣국",
    "manhwa": "만화",
    "mashisseoyo": "맛있어요",
    "masisseo": "맛있어",
    "masisseoyo": "맛있어요",
    "mbc": "엠비씨",
    "meokbang": "먹방",
    "meosisseo": "멋있어",
    "mianhae": "미안해",
    "mianhaeyo": "미안해요",
    "michin": "미친",
    "michyeosseo": "미쳤어",
    "minhwa": "민화",
    "misugaru": "미숫가루",
    "mokyoktang": "목욕탕",
    "molla": "몰라",
    "momzzang": "몸짱",
    "monsta x": "몬스타엑스",
    "mugunghwa": "무궁화",
    "mukbang": "먹방",
    "mul naengmyeon": "물냉면",
    "myeong": "명",
    "myeongdong": "명동",
    "myung": "명",
    "naengmyeon": "냉면",
    "nam": "남",
    "namdaemun": "남대문",
    "namsan": "남산",
    "naver": "네이버",
    "nct": "엔씨티",
    "newjeans": "뉴진스",
    "nmixx": "엔믹스",
    "noh": "노",
    "noona": "누나",
    "noraebang": "노래방",
    "norigae": "노리개",
    "nuna": "누나",
    "nunchi": "눈치",
    "nurungji": "누룽지",
    "odeng": "오뎅",
    "oi sobagi": "오이소박이",
    "omo": "어머",
    "omurice": "오므라이스",
    "ondol": "온돌",
    "oppa": "오빠",
    "ottoke": "어떡해",
    "paiting": "파이팅",
    "pajeon": "파전",
    "palli": "빨리",
    "panmunjom": "판문점",
    "pansori": "판소리",
    "patbingsu": "팥빙수",
    "patjuk": "팥죽",
    "pc bang": "피씨방",
    "pojangmacha": "포장마차",
    "posco": "포스코",
    "psy": "싸이",
    "pyeongchang": "평창",
    "pyeonuijeom": "편의점",
    "rabokki": "라볶이",
    "ramyeon": "라면",
    "ramyun": "라면",
    "red velvet": "레드벨벳",
    "roh": "노",
    "ryu": "류",
    "saengil": "생일",
    "saengil chukha": "생일 축하",
    "sageuk": "사극",
    "samchon": "삼촌",
    "samgyeopsal": "삼겹살",
    "samgyetang": "삼계탕",
    "samsung": "삼성",
    "samulnori": "사물놀이",
    "sannakji": "산낙지",
    "sarang": "사랑",
    "saranghae": "사랑해",
    "saranghaeyo": "사랑해요",
    "sasaeng": "사생",
    "sbs": "에스비에스",
    "sebae": "세배",
    "selca": "셀카",
    "seo": "서",
    "seollal": "설날",
    "seolleongtang": "설렁탕",
    "seong": "성",
    "seonsaengnim": "선생님",
    "seorak": "설악",
    "seoraksan": "설악산",
    "seoul": "서울",
    "seventeen": "세븐틴",
    "shim": "심",
    "shin": "신",
    "shinee": "샤이니",
    "shinsegae": "신세계",
    "sikhye": "식혜",
    "silla": "신라",
    "sim": "심",
    "sinchon": "신촌",
    "soju": "소주",
    "sokcho": "속초",
    "somaek": "소맥",
    "song": "송",
    "sonsaengnim": "선생님",
    "soondae": "순대",
    "soondubu": "순두부",
    "ssam": "쌈",
    "ssamjang": "쌈장",
    "ssireum": "씨름",
    "stray kids": "스트레이 키즈",
    "sugohaseyo": "수고하세요",
    "suh": "서",
    "sujebi": "수제비",
    "sujeonggwa": "수정과",
    "sunbae": "선배",
    "sundubu": "순두부",
    "sundubu jjigae": "순두부찌개",
    "suneung": "수능",
    "super junior": "슈퍼주니어",
    "taegeuk": "태극",
    "taegeukgi": "태극기",
    "taekkyeon": "택견",
    "taekwondo": "태권도",
    "tak": "탁",
    "talchum": "탈춤",
    "trot": "트로트",
    "tteok": "떡",
    "tteokbokki": "떡볶이",
    "tteokgalbi": "떡갈비",
    "tteokguk": "떡국",
    "ttukbaegi": "뚝배기",
    "tvn": "티비엔",
    "twice": "트와이스",
    "twigim": "튀김",
    "uhm": "엄",
    "ulsan": "울산",
    "ulzzang": "얼짱",
    "wae": "왜",
    "webtoon": "웹툰",
    "wolse": "월세",
    "won": "원",
    "woo": "우",
    "yakgwa": "약과",
    "yang": "양",
    "yangnyeom chicken": "양념치킨",
    "yeo": "여",
    "yeoboseyo": "여보세요",
    "yeom": "염",
    "yeong": "영",
    "yeouido": "여의도",
    "yeppeo": "예뻐",
    "yoo": "유",
    "yoon": "윤",
    "yu": "유",
    "yubu chobap": "유부초밥",
    "yuja": "유자",
    "yuja tea": "유자차",
    "yukhoe": "육회",
    "yun": "윤",
    "yutnori": "윷놀이",
}

__all__ = ["ROMANIZED"]
