"""Computing and technology vocabulary."""
from __future__ import annotations

from typing import Dict

TECHNOLOGY: Dict[str, str] = {
    "3d printer": "쓰리디 프린터",
    "4k": "포케이",
    "5g": "오지",
    "8k": "팔케이",
    "abstraction": "앱스트랙션",
    "account": "어카운트",
    "activation": "액티베이션",
    "adapter": "어댑터",
    "admin": "어드민",
    "administrator": "어드미니스트레이터",
    "adware": "애드웨어",
    "after effects": "애프터 이펙트",
    "agent": "에이전트",
    "agentic": "에이전틱",
    "agile": "애자일",
    "ai": "에이아이",
    "airpods": "에어팟",
    "alert": "얼럿",
    "alexa": "알렉사",
    "algorithm": "알고리즘",
    "alignment": "얼라인먼트",
    "alpha": "알파",
    "amazon": "아마존",
    "amd": "에이엠디",
    "ampere": "암페어",
    "anaconda": "아나콘다",
    "analog": "아날로그",
    "analytics": "애널리틱스",
    "android": "안드로이드",
    "android studio": "안드로이드 스튜디오",
    "angular": "앵귤러",
    "animation": "애니메이션",
    "ansible": "앤서블",
    "antenna": "안테나",
    "anthropic": "앤스로픽",
    "antivirus": "안티바이러스",
    "apache": "아파치",
    "api": "에이피아이",
    "api gateway": "에이피아이 게이트웨이",
    "api key": "에이피아이 키",
    "apk": "에이피케이",
    "app": "앱",
    "app store": "앱 스토어",
    "apple": "애플",
    "apple watch": "애플 워치",
    "application": "애플리케이션",
    "ar": "에이알",
    "arcade": "아케이드",
    "archive": "아카이브",
    "arduino": "아두이노",
    "argument": "아규먼트",
    "array": "어레이",
    "artificial intelligence": "아티피셜 인텔리전스",
    "asana": "아사나",
    "ascii": "아스키",
    "assembler": "어셈블러",
    "assembly": "어셈블리",
    "assistant": "어시스턴트",
    "attention": "어텐션",
    "audio": "오디오",
    "authentication": "어센티케이션",
    "authorization": "어서라이제이션",
    "autocad": "오토캐드",
    "automation": "오토메이션",
    "autopilot": "오토파일럿",
    "autoscaling": "오토스케일링",
    "avatar": "아바타",
    "aws": "에이더블유에스",
    "azure": "애저",
    "babel": "바벨",
    "backdoor": "백도어",
    "backend": "백엔드",
    "backlog": "백로그",
    "backspace": "백스페이스",
    "backup": "백업",
    "badge": "배지",
    "bandwidth": "밴드위스",
    "banner": "배너",
    "barcode": "바코드",
    "batch": "배치",
    "batch size": "배치 사이즈",
    "battery": "배터리",
    "battle royale": "배틀 로열",
    "benchmark": "벤치마크",
    "beta": "베타",
    "beta test": "베타 테스트",
    "big data": "빅 데이터",
    "binary": "바이너리",
    "biometric": "바이오메트릭",
    "bios": "바이오스",
    "bit": "비트",
    "bitbucket": "비트버킷",
    "bitcoin": "비트코인",
    "bitrate": "비트레이트",
    "bixby": "빅스비",
    "blender": "블렌더",
    "blockchain": "블록체인",
    "blog": "블로그",
    "bluetooth": "블루투스",
    "boilerplate": "보일러플레이트",
    "bold": "볼드",
    "bookmark": "북마크",
    "boolean": "불리언",
    "boot": "부트",
    "bootcamp": "부트캠프",
    "border": "보더",
    "boss": "보스",
    "bot": "봇",
    "botnet": "봇넷",
    "branch": "브랜치",
    "breakpoint": "브레이크포인트",
    "broadband": "브로드밴드",
    "browser": "브라우저",
    "buffer": "버퍼",
    "bug": "버그",
    "build": "빌드",
    "bundle": "번들",
    "button": "버튼",
    "byte": "바이트",
    "bytecode": "바이트코드",
    "cable": "케이블",
    "cache": "캐시",
    "callback": "콜백",
    "camera": "카메라",
    "capacitor": "커패시터",
    "captcha": "캡차",
    "caption": "캡션",
    "carrier": "캐리어",
    "cdn": "씨디엔",
    "centos": "센트오에스",
    "charger": "차저",
    "chatbot": "챗봇",
    "chatgpt": "챗지피티",
    "cheat": "치트",
    "checkbox": "체크박스",
    "checkout": "체크아웃",
    "checkpoint": "체크포인트",
    "chip": "칩",
    "chipset": "칩셋",
    "chrome": "크롬",
    "chromebook": "크롬북",
    "ci/cd": "씨아이 씨디",
    "circuit": "서킷",
    "class": "클래스",
    "classifier": "클래시파이어",
    "claude": "클로드",
    "cli": "씨엘아이",
    "click": "클릭",
    "client": "클라이언트",
    "clipboard": "클립보드",
    "clone": "클론",
    "closure": "클로저",
    "cloud": "클라우드",
    "cloud computing": "클라우드 컴퓨팅",
    "cloud storage": "클라우드 스토리지",
    "cluster": "클러스터",
    "clustering": "클러스터링",
    "cms": "씨엠에스",
    "cobol": "코볼",
    "code": "코드",
    "code review": "코드 리뷰",
    "codebase": "코드베이스",
    "codec": "코덱",
    "coder": "코더",
    "coding": "코딩",
    "colab": "코랩",
    "color": "컬러",
    "column": "칼럼",
    "command": "커맨드",
    "comment": "코멘트",
    "commit": "커밋",
    "compile": "컴파일",
    "compiler": "컴파일러",
    "component": "컴포넌트",
    "compression": "컴프레션",
    "computer": "컴퓨터",
    "computer science": "컴퓨터 사이언스",
    "computer vision": "컴퓨터 비전",
    "condition": "컨디션",
    "config": "컨피그",
    "configuration": "컨피규레이션",
    "confluence": "컨플루언스",
    "console": "콘솔",
    "constant": "콘스턴트",
    "container": "컨테이너",
    "context window": "컨텍스트 윈도우",
    "contributor": "컨트리뷰터",
    "controller": "컨트롤러",
    "cookie": "쿠키",
    "cooling fan": "쿨링 팬",
    "copilot": "코파일럿",
    "copy": "카피",
    "copyright": "카피라이트",
    "cpu": "씨피유",
    "crash": "크래시",
    "crawler": "크롤러",
    "crawling": "크롤링",
    "credential": "크리덴셜",
    "crm": "씨알엠",
    "cron": "크론",
    "crypto": "크립토",
    "cryptocurrency": "크립토커런시",
    "css": "씨에스에스",
    "csv": "씨에스브이",
    "cuda": "쿠다",
    "cyber": "사이버",
    "cyberattack": "사이버 어택",
    "cybersecurity": "사이버 시큐리티",
    "daemon": "데몬",
    "dark mode": "다크 모드",
    "dart": "다트",
    "dashboard": "대시보드",
    "data": "데이터",
    "data center": "데이터 센터",
    "data mining": "데이터 마이닝",
    "data science": "데이터 사이언스",
    "database": "데이터베이스",
    "dataset": "데이터셋",
    "ddos": "디도스",
    "deadlock": "데드락",
    "debian": "데비안",
    "debug": "디버그",
    "debugger": "디버거",
    "debugging": "디버깅",
    "decode": "디코드",
    "decrypt": "디크립트",
    "deep learning": "딥 러닝",
    "deepmind": "딥마인드",
    "default": "디폴트",
    "demo": "데모",
    "deno": "데노",
    "dependency": "디펜던시",
    "deploy": "디플로이",
    "deployment": "디플로이먼트",
    "design pattern": "디자인 패턴",
    "desktop": "데스크톱",
    "developer": "디벨로퍼",
    "device": "디바이스",
    "devops": "데브옵스",
    "diff": "디프",
    "diffusion": "디퓨전",
    "diffusion model": "디퓨전 모델",
    "digital": "디지털",
    "digital nomad": "디지털 노마드",
    "digital signature": "디지털 시그니처",
    "digital transformation": "디지털 트랜스포메이션",
    "digital twin": "디지털 트윈",
    "directory": "디렉터리",
    "discord": "디스코드",
    "display": "디스플레이",
    "django": "장고",
    "dlc": "디엘씨",
    "dns": "디엔에스",
    "docker": "도커",
    "documentation": "도큐멘테이션",
    "dom": "돔",
    "domain": "도메인",
    "dongle": "동글",
    "double click": "더블 클릭",
    "download": "다운로드",
    "downtime": "다운타임",
    "drag": "드래그",
    "driver": "드라이버",
    "drone": "드론",
    "drop": "드롭",
    "dropbox": "드롭박스",
    "dropdown": "드롭다운",
    "earbuds": "이어버드",
    "earphone": "이어폰",
    "eclipse": "이클립스",
    "ecosystem": "에코시스템",
    "edge": "엣지",
    "edge computing": "엣지 컴퓨팅",
    "elasticsearch": "엘라스틱서치",
    "electronic": "일렉트로닉",
    "elixir": "엘릭서",
    "emacs": "이맥스",
    "email": "이메일",
    "embedded": "임베디드",
    "embedding": "임베딩",
    "emoji": "이모지",
    "emulator": "에뮬레이터",
    "encode": "인코드",
    "encoding": "인코딩",
    "encryption": "인크립션",
    "endpoint": "엔드포인트",
    "engineer": "엔지니어",
    "enter": "엔터",
    "enum": "이넘",
    "environment": "인바이런먼트",
    "epic games": "에픽 게임즈",
    "epoch": "에포크",
    "erlang": "얼랭",
    "erp": "이알피",
    "error": "에러",
    "escape": "이스케이프",
    "esports": "이스포츠",
    "ethereum": "이더리움",
    "ethernet": "이더넷",
    "event": "이벤트",
    "excel": "엑셀",
    "exception": "익셉션",
    "exploit": "익스플로잇",
    "export": "익스포트",
    "express": "익스프레스",
    "facebook": "페이스북",
    "factory": "팩토리",
    "factory reset": "팩토리 리셋",
    "fallback": "폴백",
    "fast charging": "패스트 차징",
    "fastapi": "패스트에이피아이",
    "fedora": "페도라",
    "feed": "피드",
    "field": "필드",
    "figma": "피그마",
    "file": "파일",
    "filesystem": "파일 시스템",
    "filter": "필터",
    "fine tuning": "파인 튜닝",
    "fingerprint": "핑거프린트",
    "firebase": "파이어베이스",
    "firefox": "파이어폭스",
    "firewall": "파이어월",
    "firmware": "펌웨어",
    "flash": "플래시",
    "flash drive": "플래시 드라이브",
    "flash memory": "플래시 메모리",
    "flask": "플라스크",
    "flexbox": "플렉스박스",
    "float": "플로트",
    "flowchart": "플로차트",
    "folder": "폴더",
    "font": "폰트",
    "footer": "푸터",
    "foreign key": "포린 키",
    "fork": "포크",
    "form": "폼",
    "fortran": "포트란",
    "forum": "포럼",
    "fps": "에프피에스",
    "frame rate": "프레임 레이트",
    "framework": "프레임워크",
    "frequency": "프리퀀시",
    "frontend": "프론트엔드",
    "ftp": "에프티피",
    "full hd": "풀 에이치디",
    "full stack": "풀 스택",
    "function": "펑션",
    "gadget": "가젯",
    "galaxy": "갤럭시",
    "game": "게임",
    "gamepad": "게임패드",
    "gamer": "게이머",
    "gaming": "게이밍",
    "garbage collection": "가비지 컬렉션",
    "gateway": "게이트웨이",
    "gcp": "지씨피",
    "gemini": "제미나이",
    "generative ai": "제너레이티브 에이아이",
    "generic": "제네릭",
    "gigabyte": "기가바이트",
    "gigahertz": "기가헤르츠",
    "git": "깃",
    "github": "깃허브",
    "gitlab": "깃랩",
    "golang": "고랭",
    "google": "구글",
    "google drive": "구글 드라이브",
    "gps": "지피에스",
    "gpt": "지피티",
    "gpu": "지피유",
    "gradient": "그래디언트",
    "graphics card": "그래픽 카드",
    "graphql": "그래프큐엘",
    "grid": "그리드",
    "grpc": "지알피씨",
    "gui": "지유아이",
    "gyroscope": "자이로스코프",
    "hackathon": "해커톤",
    "hacker": "해커",
    "hacking": "해킹",
    "hallucination": "할루시네이션",
    "handler": "핸들러",
    "hard disk": "하드 디스크",
    "hard drive": "하드 드라이브",
    "hardware": "하드웨어",
    "hash": "해시",
    "hashtag": "해시태그",
    "haskell": "하스켈",
    "hd": "에이치디",
    "hdd": "에이치디디",
    "hdmi": "에이치디엠아이",
    "header": "헤더",
    "headphone": "헤드폰",
    "headset": "헤드셋",
    "heap": "힙",
    "heatsink": "히트싱크",
    "heroku": "헤로쿠",
    "hertz": "헤르츠",
    "hologram": "홀로그램",
    "hook": "훅",
    "host": "호스트",
    "hosting": "호스팅",
    "hotspot": "핫스폿",
    "html": "에이치티엠엘",
    "http": "에이치티티피",
    "https": "에이치티티피에스",
    "hugging face": "허깅 페이스",
    "hyperlink": "하이퍼링크",
    "icloud": "아이클라우드",
    "icon": "아이콘",
    "ide": "아이디이",
    "illustrator": "일러스트레이터",
    "immutable": "이뮤터블",
    "import": "임포트",
    "inbox": "인박스",
    "index": "인덱스",
    "inference": "인퍼런스",
    "influencer": "인플루언서",
    "information technology": "인포메이션 테크놀로지",
    "infrastructure": "인프라스트럭처",
    "injection": "인젝션",
    "innovation": "이노베이션",
    "input": "인풋",
    "instagram": "인스타그램",
    "install": "인스톨",
    "instance": "인스턴스",
    "integer": "인티저",
    "intel": "인텔",
    "intellij": "인텔리제이",
    "interface": "인터페이스",
    "internet": "인터넷",
    "internet of things": "인터넷 오브 싱스",
    "interpreter": "인터프리터",
    "ios": "아이오에스",
    "iot": "아이오티",
    "ip": "아이피",
    "ipad": "아이패드",
    "iphone": "아이폰",
    "issue": "이슈",
    "italic": "이탤릭",
    "iteration": "이터레이션",
    "java": "자바",
    "javascript": "자바스크립트",
    "jenkins": "젠킨스",
    "jira": "지라",
    "joystick": "조이스틱",
    "jpeg": "제이펙",
    "jpg": "제이피지",
    "jquery": "제이쿼리",
    "json": "제이슨",
    "julia": "줄리아",
    "jupyter": "주피터",
    "jvm": "제이브이엠",
    "kafka": "카프카",
    "kaggle": "캐글",
    "kakao": "카카오",
    "kanban": "칸반",
    "keras": "케라스",
    "kernel": "커널",
    "keyboard": "키보드",
    "keyframe": "키프레임",
    "keyword": "키워드",
    "kilobyte": "킬로바이트",
    "kindle": "킨들",
    "kotlin": "코틀린",
    "kubernetes": "쿠버네티스",
    "label": "레이블",
    "lag": "랙",
    "lambda": "람다",
    "lan": "랜",
    "laptop": "랩톱",
    "laravel": "라라벨",
    "large language model": "라지 랭귀지 모델",
    "latency": "레이턴시",
    "launch": "론치",
    "layout": "레이아웃",
    "lcd": "엘씨디",
    "leaderboard": "리더보드",
    "learning rate": "러닝 레이트",
    "led": "엘이디",
    "legacy": "레거시",
    "lens": "렌즈",
    "level up": "레벨 업",
    "library": "라이브러리",
    "license": "라이선스",
    "lidar": "라이다",
    "link": "링크",
    "linkedin": "링크드인",
    "linker": "링커",
    "linter": "린터",
    "linux": "리눅스",
    "listener": "리스너",
    "livestream": "라이브 스트림",
    "llm": "엘엘엠",
    "load balancer": "로드 밸런서",
    "localhost": "로컬호스트",
    "log": "로그",
    "logging": "로깅",
    "login": "로그인",
    "logout": "로그아웃",
    "loop": "루프",
    "loss function": "로스 펑션",
    "lte": "엘티이",
    "lua": "루아",
    "mac": "맥",
    "mac address": "맥 어드레스",
    "macbook": "맥북",
    "machine learning": "머신 러닝",
    "macos": "맥오에스",
    "mainboard": "메인보드",
    "mainframe": "메인프레임",
    "maintainer": "메인테이너",
    "malware": "멀웨어",
    "margin": "마진",
    "markdown": "마크다운",
    "matchmaking": "매치메이킹",
    "matlab": "매트랩",
    "mechanical keyboard": "메커니컬 키보드",
    "media": "미디어",
    "media query": "미디어 쿼리",
    "megabyte": "메가바이트",
    "megahertz": "메가헤르츠",
    "megapixel": "메가픽셀",
    "meme": "밈",
    "memory": "메모리",
    "memory leak": "메모리 리크",
    "menu": "메뉴",
    "merge": "머지",
    "merge conflict": "머지 컨플릭트",
    "meta": "메타",
    "metadata": "메타데이터",
    "metaverse": "메타버스",
    "method": "메서드",
    "metric": "메트릭",
    "mic": "마이크",
    "micro sd": "마이크로 에스디",
    "microcontroller": "마이크로컨트롤러",
    "microphone": "마이크로폰",
    "microservice": "마이크로서비스",
    "microsoft": "마이크로소프트",
    "middleware": "미들웨어",
    "midjourney": "미드저니",
    "migration": "마이그레이션",
    "milestone": "마일스톤",
    "mining": "마이닝",
    "mmorpg": "엠엠오알피지",
    "mms": "엠엠에스",
    "mockup": "목업",
    "mod": "모드",
    "modal": "모달",
    "model": "모델",
    "modem": "모뎀",
    "module": "모듈",
    "mongodb": "몽고디비",
    "monitor": "모니터",
    "monitoring": "모니터링",
    "motherboard": "마더보드",
    "mouse": "마우스",
    "mp3": "엠피쓰리",
    "mp4": "엠피포",
    "multimedia": "멀티미디어",
    "multimodal": "멀티모달",
    "multiplayer": "멀티플레이어",
    "mutation": "뮤테이션",
    "mute": "뮤트",
    "mutex": "뮤텍스",
    "mysql": "마이에스큐엘",
    "namespace": "네임스페이스",
    "natural language processing": "내추럴 랭귀지 프로세싱",
    "naver": "네이버",
    "netflix": "넷플릭스",
    "netlify": "넷리파이",
    "network": "네트워크",
    "neural network": "뉴럴 네트워크",
    "newsletter": "뉴스레터",
    "next.js": "넥스트 제이에스",
    "nfc": "엔에프씨",
    "nft": "엔에프티",
    "nginx": "엔진엑스",
    "nintendo": "닌텐도",
    "nlp": "엔엘피",
    "node": "노드",
    "nodejs": "노드제이에스",
    "nosql": "노에스큐엘",
    "notebook": "노트북",
    "notepad": "노트패드",
    "notification": "노티피케이션",
    "notion": "노션",
    "npc": "엔피씨",
    "npm": "엔피엠",
    "null": "널",
    "numpy": "넘파이",
    "nvidia": "엔비디아",
    "object": "오브젝트",
    "objective c": "오브젝티브 씨",
    "ocr": "오씨알",
    "office": "오피스",
    "oled": "오엘이디",
    "onedrive": "원드라이브",
    "online game": "온라인 게임",
    "opacity": "오퍼시티",
    "open source": "오픈 소스",
    "open world": "오픈 월드",
    "openai": "오픈에이아이",
    "operating system": "오퍼레이팅 시스템",
    "optional": "옵셔널",
    "oracle": "오라클",
    "orchestration": "오케스트레이션",
    "outlook": "아웃룩",
    "output": "아웃풋",
    "overclock": "오버클록",
    "overfitting": "오버피팅",
    "packet": "패킷",
    "padding": "패딩",
    "pair programming": "페어 프로그래밍",
    "pandas": "판다스",
    "parameter": "파라미터",
    "parser": "파서",
    "parsing": "파싱",
    "partition": "파티션",
    "pascal": "파스칼",
    "password": "패스워드",
    "paste": "페이스트",
    "patch": "패치",
    "payload": "페이로드",
    "paypal": "페이팔",
    "pdf": "피디에프",
    "perl": "펄",
    "permission": "퍼미션",
    "petabyte": "페타바이트",
    "phishing": "피싱",
    "photoshop": "포토샵",
    "php": "피에이치피",
    "ping": "핑",
    "pip": "핍",
    "pipe": "파이프",
    "pipeline": "파이프라인",
    "pixel": "픽셀",
    "placeholder": "플레이스홀더",
    "platform": "플랫폼",
    "play store": "플레이 스토어",
    "playlist": "플레이리스트",
    "playstation": "플레이스테이션",
    "png": "피엔지",
    "pod": "파드",
    "podcast": "팟캐스트",
    "pointer": "포인터",
    "polyfill": "폴리필",
    "popup": "팝업",
    "port": "포트",
    "postgres": "포스트그레스",
    "postgresql": "포스트그레스큐엘",
    "postman": "포스트맨",
    "power bank": "파워 뱅크",
    "power supply": "파워 서플라이",
    "powerpoint": "파워포인트",
    "premiere": "프리미어",
    "premium": "프리미엄",
    "pretraining": "프리트레이닝",
    "preview": "프리뷰",
    "primary key": "프라이머리 키",
    "printer": "프린터",
    "privacy": "프라이버시",
    "private key": "프라이빗 키",
    "process": "프로세스",
    "processor": "프로세서",
    "production": "프로덕션",
    "profile": "프로필",
    "program": "프로그램",
    "programmer": "프로그래머",
    "programming": "프로그래밍",
    "projector": "프로젝터",
    "promise": "프로미스",
    "prompt": "프롬프트",
    "prompt engineering": "프롬프트 엔지니어링",
    "props": "프롭스",
    "protocol": "프로토콜",
    "prototype": "프로토타입",
    "provisioning": "프로비저닝",
    "proxy": "프록시",
    "pseudocode": "슈도코드",
    "public key": "퍼블릭 키",
    "pull request": "풀 리퀘스트",
    "push": "푸시",
    "push notification": "푸시 노티피케이션",
    "python": "파이썬",
    "pytorch": "파이토치",
    "qr code": "큐알 코드",
    "qualcomm": "퀄컴",
    "quantum": "퀀텀",
    "quantum computing": "퀀텀 컴퓨팅",
    "query": "쿼리",
    "queue": "큐",
    "qwerty": "쿼티",
    "race condition": "레이스 컨디션",
    "rack": "랙",
    "radar": "레이더",
    "rails": "레일스",
    "ram": "램",
    "ransomware": "랜섬웨어",
    "raspberry pi": "라즈베리 파이",
    "react": "리액트",
    "readme": "리드미",
    "rebase": "리베이스",
    "reboot": "리부트",
    "recursion": "리커전",
    "reddit": "레딧",
    "redhat": "레드햇",
    "redis": "레디스",
    "redo": "리두",
    "refactoring": "리팩터링",
    "refresh": "리프레시",
    "register": "레지스터",
    "regression": "리그레션",
    "reinforcement learning": "리인포스먼트 러닝",
    "release": "릴리스",
    "reload": "리로드",
    "remote control": "리모트 컨트롤",
    "remote work": "리모트 워크",
    "render": "렌더",
    "rendering": "렌더링",
    "replication": "리플리케이션",
    "repo": "레포",
    "repository": "리포지토리",
    "request": "리퀘스트",
    "reset": "리셋",
    "respawn": "리스폰",
    "response": "리스폰스",
    "rest api": "레스트 에이피아이",
    "restart": "리스타트",
    "restore": "리스토어",
    "retina": "레티나",
    "retry": "리트라이",
    "return": "리턴",
    "reverse proxy": "리버스 프록시",
    "rfid": "알에프아이디",
    "rgb": "알지비",
    "roadmap": "로드맵",
    "roaming": "로밍",
    "robot": "로봇",
    "rollback": "롤백",
    "rollout": "롤아웃",
    "rom": "롬",
    "router": "라우터",
    "row": "로우",
    "rpg": "알피지",
    "ruby": "루비",
    "runtime": "런타임",
    "rust": "러스트",
    "safari": "사파리",
    "salesforce": "세일즈포스",
    "samsung": "삼성",
    "sandbox": "샌드박스",
    "satellite": "새틀라이트",
    "save": "세이브",
    "scala": "스칼라",
    "scaling": "스케일링",
    "scanner": "스캐너",
    "schema": "스키마",
    "scikit learn": "사이킷런",
    "scope": "스코프",
    "scraping": "스크래핑",
    "screen": "스크린",
    "screenshot": "스크린샷",
    "script": "스크립트",
    "scroll": "스크롤",
    "scrum": "스크럼",
    "sd card": "에스디 카드",
    "search": "서치",
    "search engine": "서치 엔진",
    "secret": "시크릿",
    "security": "시큐리티",
    "self driving": "셀프 드라이빙",
    "selfie": "셀피",
    "semantic": "시맨틱",
    "semaphore": "세마포어",
    "semiconductor": "세미컨덕터",
    "sensor": "센서",
    "serial number": "시리얼 넘버",
    "server": "서버",
    "serverless": "서버리스",
    "session": "세션",
    "setting": "세팅",
    "setup": "셋업",
    "shadow": "섀도",
    "sharding": "샤딩",
    "share": "셰어",
    "shell": "셸",
    "shift": "시프트",
    "shopify": "쇼피파이",
    "shortcut": "숏컷",
    "shuffle": "셔플",
    "shutdown": "셧다운",
    "shutter": "셔터",
    "sidebar": "사이드바",
    "signal": "시그널",
    "sim card": "심 카드",
    "simulation": "시뮬레이션",
    "single player": "싱글 플레이어",
    "singleton": "싱글턴",
    "siri": "시리",
    "slack": "슬랙",
    "sleep mode": "슬립 모드",
    "slider": "슬라이더",
    "smart": "스마트",
    "smart home": "스마트 홈",
    "smart speaker": "스마트 스피커",
    "smart tv": "스마트 티브이",
    "smartphone": "스마트폰",
    "smartwatch": "스마트워치",
    "smishing": "스미싱",
    "sms": "에스엠에스",
    "snippet": "스니펫",
    "socket": "소켓",
    "software": "소프트웨어",
    "software engineer": "소프트웨어 엔지니어",
    "soundbar": "사운드바",
    "source code": "소스 코드",
    "spacebar": "스페이스바",
    "spam": "스팸",
    "speaker": "스피커",
    "speech recognition": "스피치 리코그니션",
    "speedrun": "스피드런",
    "spotify": "스포티파이",
    "spreadsheet": "스프레드시트",
    "spring": "스프링",
    "sprint": "스프린트",
    "spyware": "스파이웨어",
    "sql": "에스큐엘",
    "sqlite": "에스큐엘라이트",
    "ssd": "에스에스디",
    "ssh": "에스에스에이치",
    "ssl": "에스에스엘",
    "stable diffusion": "스테이블 디퓨전",
    "stack": "스택",
    "stack overflow": "스택 오버플로",
    "staging": "스테이징",
    "standby": "스탠바이",
    "startup": "스타트업",
    "state": "스테이트",
    "steam": "스팀",
    "stereo": "스테레오",
    "storage": "스토리지",
    "streamer": "스트리머",
    "streaming": "스트리밍",
    "string": "스트링",
    "stripe": "스트라이프",
    "struct": "스트럭트",
    "stylus": "스타일러스",
    "subdomain": "서브도메인",
    "subnet": "서브넷",
    "subscription": "서브스크립션",
    "subtitle": "서브타이틀",
    "supabase": "수파베이스",
    "supercomputer": "슈퍼컴퓨터",
    "supervised learning": "슈퍼바이즈드 러닝",
    "surround": "서라운드",
    "svelte": "스벨트",
    "svg": "에스브이지",
    "swift": "스위프트",
    "swipe": "스와이프",
    "switch": "스위치",
    "sync": "싱크",
    "syntax": "신택스",
    "system": "시스템",
    "table": "테이블",
    "tablet": "태블릿",
    "tag": "태그",
    "tap": "탭",
    "tcp": "티씨피",
    "tech": "테크",
    "technology": "테크놀로지",
    "telecom": "텔레콤",
    "telegram": "텔레그램",
    "template": "템플릿",
    "tensor": "텐서",
    "tensorflow": "텐서플로",
    "terabyte": "테라바이트",
    "terminal": "터미널",
    "terraform": "테라폼",
    "tesla": "테슬라",
    "test": "테스트",
    "tethering": "테더링",
    "text to speech": "텍스트 투 스피치",
    "theme": "테마",
    "thread": "스레드",
    "throttling": "스로틀링",
    "throughput": "스루풋",
    "thumbnail": "썸네일",
    "thunderbolt": "썬더볼트",
    "ticket": "티켓",
    "tiktok": "틱톡",
    "timeline": "타임라인",
    "timeout": "타임아웃",
    "toggle": "토글",
    "token": "토큰",
    "tokenizer": "토크나이저",
    "tomcat": "톰캣",
    "toolbar": "툴바",
    "tooltip": "툴팁",
    "touchpad": "터치패드",
    "touchscreen": "터치스크린",
    "trackpad": "트랙패드",
    "training": "트레이닝",
    "transaction": "트랜잭션",
    "transcript": "트랜스크립트",
    "transformer": "트랜스포머",
    "transistor": "트랜지스터",
    "transition": "트랜지션",
    "trello": "트렐로",
    "trial": "트라이얼",
    "tts": "티티에스",
    "twitch": "트위치",
    "twitter": "트위터",
    "type": "타입",
    "typescript": "타입스크립트",
    "typing": "타이핑",
    "ubuntu": "우분투",
    "udp": "유디피",
    "ui": "유아이",
    "undefined": "언디파인드",
    "undo": "언두",
    "unicode": "유니코드",
    "unit test": "유닛 테스트",
    "unity": "유니티",
    "unix": "유닉스",
    "unreal": "언리얼",
    "unsupervised learning": "언슈퍼바이즈드 러닝",
    "update": "업데이트",
    "upgrade": "업그레이드",
    "upload": "업로드",
    "uptime": "업타임",
    "url": "유알엘",
    "usb": "유에스비",
    "usb drive": "유에스비 드라이브",
    "usb-c": "유에스비 씨",
    "user": "유저",
    "user experience": "유저 익스피리언스",
    "user interface": "유저 인터페이스",
    "username": "유저네임",
    "ux": "유엑스",
    "validation": "밸리데이션",
    "variable": "베리어블",
    "vector": "벡터",
    "vercel": "버셀",
    "version": "버전",
    "version control": "버전 컨트롤",
    "video": "비디오",
    "video call": "비디오 콜",
    "video card": "비디오 카드",
    "viewport": "뷰포트",
    "vim": "빔",
    "viral": "바이럴",
    "virtual dom": "버추얼 돔",
    "virtual machine": "버추얼 머신",
    "virtualization": "버추얼라이제이션",
    "virus": "바이러스",
    "visual studio": "비주얼 스튜디오",
    "visualization": "비주얼라이제이션",
    "vlog": "브이로그",
    "vm": "브이엠",
    "voice assistant": "보이스 어시스턴트",
    "voice recognition": "보이스 리코그니션",
    "volt": "볼트",
    "volume": "볼륨",
    "vpn": "브이피엔",
    "vr": "브이알",
    "vscode": "브이에스코드",
    "vue": "뷰",
    "wallet": "월렛",
    "warning": "워닝",
    "watermark": "워터마크",
    "watt": "와트",
    "wearable": "웨어러블",
    "web": "웹",
    "web hosting": "웹 호스팅",
    "webcam": "웹캠",
    "webhook": "웹훅",
    "webinar": "웨비나",
    "webpack": "웹팩",
    "webpage": "웹페이지",
    "website": "웹사이트",
    "websocket": "웹소켓",
    "whatsapp": "왓츠앱",
    "whiteboard": "화이트보드",
    "wi-fi": "와이파이",
    "widget": "위젯",
    "wifi": "와이파이",
    "windows": "윈도우",
    "wireframe": "와이어프레임",
    "wireless": "와이어리스",
    "wireless charging": "와이어리스 차징",
    "workflow": "워크플로",
    "workstation": "워크스테이션",
    "worm": "웜",
    "xbox": "엑스박스",
    "xcode": "엑스코드",
    "xml": "엑스엠엘",
    "yaml": "야믈",
    "yarn": "얀",
    "youtube": "유튜브",
    "zip": "집",
    "zoom": "줌",
}

__all__ = ["TECHNOLOGY"]
